### ISSUE TITLE
Can you add save as pdf function?

### ISSUE THREAD

**Issue by sun11** [ZachSaucier/Just-Read#1]
This extension is exactly what i need. The format for text and images is just right.

But i want to save some web pages to pdf format, i tried the chrome's save to pdf function but it still save the original web pages, so i hope you can add this function.

I know a little about css, so i think the problem may be the simple-article's height is just the screen size(100%), and the chrome's save to pdf cannot detect the 2nd page...But i don't know how to fix it...

**Comment by ZachSaucier** [comment]
Hey sun11, thanks for the feedback.

This was one of the features I was planning on adding, I just hadn't gotten around to it (after finals a few more features should be added). But I went ahead and added this in the [most recent commit](https://github.com/ZachSaucier/Just-Read/commit/ad68856dbd04e51b301231ea21c6b31ee61b3995). It should be rolling out to the Chromestore and auto-update in your browser soon.

Feedback on the design/usability is welcome!
