### ISSUE TITLE
New York Times has a defeater for this plugin.

### ISSUE THREAD

**Issue by DevBrent** [ZachSaucier/Just-Read#101]
I'm not clicking close or performing any other actions than clicking JustRead. If you click it once, it does not open. If you click twice, it attempts to open then disappears.

This only occurs on [NYT](https://www.nytimes.com/2017/08/30/sports/espn-ed-cunningham-football-concussions.html?mtrref=news.ycombinator.com&gwh=72C412CDFBE58EF053C5DA9E432980AB&gwt=pay). 

Short video: https://gfycat.com/gifs/detail/CavernousPoisedAmazonparrot

I really can't wait for accessibility to take precedence over their intention to prevent clean article readers. There is just way too much going on with most news websites, auto playing videos and the like to be able to read the article content.

**Comment by ZachSaucier** [comment]
Thanks for the report! I'm not seeing the behavior that you show at all on my side (Win 10 Chrome). What system are you on?

**Comment by DevBrent** [comment]
Disabling javascript on the domain allows me to read the article, but I still can't use JustRead. I don't think it's them.

Windows 10 Chrome Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by ZachSaucier** [comment]
Interesting. I'm guessing you don't use any form of ad blocker?

**Comment by dhalarewich** [comment]
I'm experiencing the same or a similar problem. I'm on Chrome/Mac, running an ad blocker (2 of them), and the JustRead extension is not pulling up the article contents. Here's an example article that doesn't work: https://www.nytimes.com/2017/09/04/opinion/middlemarch-college-fame.html

Here's an example of this article in JustRead:

<img width="768" alt="screenshot 2017-09-06 08 58 49" src="https://user-images.githubusercontent.com/1108337/30121868-aa8866a4-92e1-11e7-8a14-1556ad8b3dac.png">

**Comment by zoqaeski** [comment]
A work-around for this is to use the "Select Text to Read" option. It's a bit fiddly, but it works for me.

**Comment by ZachSaucier** [comment]
I have made some updates to Just Read that may help fix this issue in version 1.1.6. Can you please test and get back to me (since I can't reproduce)?

**Comment by dhalarewich** [comment]
@ZachSaucier The article link I posted above appears to work now using the JustRead plugin. The full article contents seem to be there 👍

**Comment by ZachSaucier** [comment]
@dhalarewich I'm glad to hear it! Thanks for getting back to me.
