### ISSUE TITLE
shows only comments section for Medium.com article

### ISSUE THREAD

**Issue by mozai** [ZachSaucier/Just-Read#103]
For [this one article](https://medium.com/personal-growth/5-mental-biases-that-cause-poor-decisions-6ebe559aaf8f) in Medium.com, Just-Read removes the body of the article, showing only a chopped-up version of the comments section.  Other similar pages on the same website do not evoke the same behaviour.  It's probably broken HTML in the one article, but I feel it's curious enough to examine.

**Comment by ZachSaucier** [comment]
Thanks for the report! I'll look into it when I get some time.

For now, you can use  [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select content on problematic pages like this.

**Comment by ZachSaucier** [comment]
This is a dupe of #94 but with a different site, so I'm going to close this issue and add this site to the list I've started there.
