### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by 2015xli** [ZachSaucier/Just-Read#105]
https://arstechnica.com/gadgets/2017/05/google-hopes-to-fix-android-updates-no-really-with-project-treble/ 

The reading mode with the page above is a little awkward. Thanks for your great work!

**Comment by ZachSaucier** [comment]
Thanks for the report. Unfortunately this is because of their bad markup and Just Read's goal is not to try to guess what the correct markup is, but only reformat the default markup. As such, I'm marking this as a won't-fix because the real issue is on their side, not Just Read's.
