### ISSUE TITLE
Font rules not applying in incognito mode

### ISSUE THREAD

**Issue by truth1ness** [ZachSaucier/Just-Read#106]
The font size rule doesn't seem to apply correctly in icognito mode. It shows the correct size in the upper right settings menu but the font is definitely much smaller than it is in regular browser windows which I presume is displaying correctly.

**Comment by ZachSaucier** [comment]
I'm sorry, I'm not seeing this issue at all. Can you please provide more information regarding the URL you are testing on, your system, and perhaps also a copy of your currently-applied stylesheet?

**Comment by ZachSaucier** [comment]
I'm closing this issue due to of response.
