### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by epardee** [ZachSaucier/Just-Read#107]
https://gizmodo.com/apple-tv-4k-is-a-damn-good-set-top-box-1818715662

The reading mode with the page above does not work.
[blank.pdf](https://github.com/ZachSaucier/Just-Read/files/1334409/blank.pdf)

Thanks for your great work!

**Comment by ZachSaucier** [comment]
Thanks for the report! The site works for me. What operating system and browser are you on?

**Comment by epardee** [comment]
OS: High Sierra (10.13)
Browser: Chrome Version 60.0.3112.113 (Official Build) (64-bit)

Coincidentally, I just tried again and it's working. Maybe it's in conflict with another extension of mine, I'll look into that. Thanks!
