### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by truth1ness** [ZachSaucier/Just-Read#108]
When I press backspace on my keyboard to go back to the previous page in my browser it gets blocked when Just Read is open. It'd be nice to be able to go back via the keyboard without having to take the extra step of exiting Just Read with the mouse first.

**Comment by ZachSaucier** [comment]
Thanks for the suggestion! When I find some time (probably next week) I'll implement this change.

**Comment by ZachSaucier** [comment]
Are you using a Chrome extension to add this functionality? AFAIK, this functionality was removed in a previous version of Chrome.

**Comment by ZachSaucier** [comment]
I'm closing this issue due to a lack of response and the fact that I think the requested feature doesn't exist any longer.
