### ISSUE TITLE
CSS colour properties accept invalid HEX data

### ISSUE THREAD

**Issue by Phil-Champ** [ZachSaucier/Just-Read#109]
The following example invalid HEX data is rendered correctly:
```
color: 003e74;
background-color: f9f5e8;
```

**Comment by Phil-Champ** [comment]
This may be a browser "feature". Inspecting the source for the Just Read version in both Opera 48.0 and Chrome 61.0 shows that both accept HEX data without the hash # character.

**Comment by ZachSaucier** [comment]
Yes, this isn't specific to Just Read. Thanks for taking the time to post about it and look into the issue though!
