### ISSUE TITLE
Context menu entry?

### ISSUE THREAD

**Issue by orschiro** [ZachSaucier/Just-Read#11]
Dear @ZachSaucier,

Thank you so much for your great extension!

May I suggest to add "Read selected text" to the context menu after having selected text?

Thankfully,

-Robert

**Comment by ZachSaucier** [comment]
Hey Richard, thanks for the suggestion!

I had thought about this before but couldn't think of a good way to integrate this functionality without restructuring massive parts of the code. However, after researching some more and giving it some thought I found a way to do this without changing much. 

So, this feature is available in version 1.0.4 of Just Read!

**Comment by orschiro** [comment]
Fantastic, thanks so much for the quick update! :-)

When will version 1.0.4 hit the Webstore?

-Robert

**Comment by ZachSaucier** [comment]
It should be within the next hour, though your browser might take a little longer than that to auto-update, I'm not sure

**Comment by orschiro** [comment]
Alright, great!

-Robert
