### ISSUE TITLE
Feature request: Zoom into images, lightbox

### ISSUE THREAD

**Issue by drreen** [ZachSaucier/Just-Read#110]
First: I love the plugin! Great for reading.

Especially when going through tutorials with screenshots, I would love to zoom in on them by clicking on them. There is no way at the moment besides zooming in with browser function

reference for usability: Medium.com

See here: https://thinkgrowth.org/the-iphone-x-is-the-beginning-of-the-end-for-phones-ab9ac8391a3

**Comment by ZachSaucier** [comment]
I'm not convinced I'll add this feature quite yet, but it's not a bad idea. Thanks for the suggestion!

**Comment by ZachSaucier** [comment]
This is now supported in the premium version of Just Read!
