### ISSUE TITLE
On this site, the entire page gets covered up by something.

### ISSUE THREAD

**Issue by KalmaroRauls** [ZachSaucier/Just-Read#111]
This has to do with www.ign.com. If you set the extension to work automatically you can only read for a few seconds.Then, entire page gets covered by the extension.

I have no idea why this happens. I thought it might actually be IGN's doing but when I used my adblock to discover the source, the extension is the culprit.

**Comment by ZachSaucier** [comment]
I believe this should be fixed as of JR version 1.1.6. Can you please confirm?

**Comment by ZachSaucier** [comment]
Closing due to lack of confirmation and the issue should being fixed.

**Comment by KalmaroRauls** [comment]
It's working fine now, I must have missed the notification.
