### ISSUE TITLE
Printing PDF Only Shows First Page

### ISSUE THREAD

**Issue by SOCPilot** [ZachSaucier/Just-Read#112]
My use case is that I will often use Good Read to create a readable version of a page and then print it to PDF for reading later.  Most of the time, this works fine but occassionally it only prints the first page of the PDF repeatedly (e.g. 20 pages consisting of just the first page.)  I haven't had this issue with non Good-read pages.  Thanks!

**Comment by ZachSaucier** [comment]
Hello and thanks for the report! 

Can you please include which website(s) this problem occurs on? And you do mean *Just Read*, not "Good Read", right? Haha.

**Comment by ZachSaucier** [comment]
I'm closing this issue due to a lack of feedback.

**Comment by jynnie** [comment]
Hello, I've also had this problem (but first two pages with a cut off) on this page: http://www.zephoria.org/thoughts/archives/2018/03/09/you-think-you-want-media-literacy-do-you.html

**Comment by ZachSaucier** [comment]
@jynnie Thanks so much for posting! I accidentally introduced this bug in yesterday's update and didn't check the print version. I've just uploaded a fix - the extension should update within an hour or two (JR version 1.1.15).

**Comment by danielzev** [comment]
@SOCPilot can you reach out to me danielzev [at] gmail [dot] com - looks like you're not using this GitHub account.
