### ISSUE TITLE
Wrong title displayed by Just-Read

### ISSUE THREAD

**Issue by ThurstonBT** [ZachSaucier/Just-Read#113]
When I attempt to view, via Just-Read, this page:
http://www.independent.co.uk/news/health/intelligence-mental-illness-iq-study-findings-depression-a8005801.html
... instead a page/story titled "'Universal cancer vaccine’ breakthrough claimed by experts" is displayed.

**Comment by ZachSaucier** [comment]
Hello and thanks for the report! I'll see if i can figure out what exactly is happening when I find some more free time. For now you can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to correctly select content on pages like this.

**Comment by ZachSaucier** [comment]
This should be fixed as of Just Read version 1.1.4.
