### ISSUE TITLE
Page does not display text

### ISSUE THREAD

**Issue by timbwana** [ZachSaucier/Just-Read#114]
https://technet.microsoft.com/en-us/library/2009.07.sqlbackup.aspx#Contents

**Comment by ZachSaucier** [comment]
Hey and thanks for the report.

What exactly do you mean "does not display text"? For me, Just Read fails the auto selection, but some text still shows. And carefully using [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) I was able to select the appropriate content.

**Comment by ZachSaucier** [comment]
I'm closing this issue due to a lack of feedback.
