### ISSUE TITLE
Issue with a RTL language page.

### ISSUE THREAD

**Issue by RoyeA** [ZachSaucier/Just-Read#116]
I love the products. I can read much faster without all the annoying artifacts on the page. 
When I  used the page right-to-left languages, I found the translated page doesn't align the text correctly. 
Would be nice to have auto language detection to correct the issue.

**Comment by ZachSaucier** [comment]
Hello and thanks for the report! Can you please include a link of the problematic site(s)? 

Some work on supporting RTL [has already been done](https://github.com/ZachSaucier/Just-Read/issues/37) and [updated a bit](https://github.com/ZachSaucier/Just-Read/issues/63).

**Comment by RoyeA** [comment]
http://www.ynet.co.il/articles/0,7340,L-5038055,00.html

When you open the article using "Just Read" you get a left-to-right alignment, instead of right-to-left. plus, special characters in a pair format like doublequote ("), parenthesis "(" are not in the correct place.

Thank you, 
Roye

**Comment by ZachSaucier** [comment]
That site fits under [the exception I mentioned when I implemented RTL](https://github.com/ZachSaucier/Just-Read/issues/37#issuecomment-274065486) of the page's body not saying it is RTL. 

When I get some time I'll look into a fix for cases like this where that's not true (it's a rare case AFAIK), but for now you can use your browser's dev tools to add `direction="rtl"` to the `body` element or use a userscript to add it for you on that site and any others you have problems with.

**Comment by ZachSaucier** [comment]
As of version 1.1.11, JR should check the first child of the selected content for any RTL characters. If any are found, JR will use its RTL mode.

**Comment by RoyeA** [comment]
Thank you. it looks great.
