### ISSUE TITLE
Gravity Tales navigation links missing

### ISSUE THREAD

**Issue by sagron** [ZachSaucier/Just-Read#117]
When viewing web novels on gravitytales.com the previous/next chapter and table of contents links are not displayed - even when using manual text selection mode with an empty style.

**Comment by sagron** [comment]
Hmmm, odd - I get the below (even after logging out, clearing cookies/cache, etc):
![gravity_bug](https://user-images.githubusercontent.com/219945/32382732-07eba9a8-c084-11e7-9baa-6fea1464916c.png)

**Comment by ZachSaucier** [comment]
What OS are you on?

**Comment by sagron** [comment]
Nevermind, updated to the latest default style css from the repo and it works fine. Not sure if I accidentally edited the default or if I just had an old version.

**Comment by sagron** [comment]
Looks like it may actually just be dependent on selecting the exact right part of the page... even though all the ones I'm selecting contain the area with the links sometimes they appear and sometimes they don't.
