### ISSUE TITLE
page is empty even with empty stylesheet

### ISSUE THREAD

**Issue by mozai** [ZachSaucier/Just-Read#118]
Steps to reproduce:
 - In JustRead options create a new stylesheet named "empty"
 - select the "empty.css" stylesheet, erase the contents.  The editor should show only a "1" for the sole empty line.
 - "save" this, then set it as "use current theme"
 - visit https://pactwebserial.wordpress.com/2014/10/07/histories-arc-11/ 
 - or visit https://pactwebserial.wordpress.com/2014/10/04/malfeasance-11-11/
 - turn on JustRead

Expected:
 - all of page contents are shown, since there are no rules to follow for hiding or reshaping page contents

Seen:
 - contents of \<div class=entry-content> is omitted, 
 - only contents of \<div id=comments class="comments-area"> is shown as the only content.

What if you used "default-styles.css" ?
 - \<h1 class=simple-title> is shown, nothing else on the page.

**Comment by ZachSaucier** [comment]
Hello and thanks for the report! It seems that JR auto selects the comments section on that page, which is the same issue as #94 so I'm going to close this issue as a dupicate. 

To work around the issue for now, you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the right content on pages like this one.
