### ISSUE TITLE
Activating Just-Read only displays the links at the bottom of the page

### ISSUE THREAD

**Issue by Peartato** [ZachSaucier/Just-Read#124]
I was browsing Encyclopedia Dramatica and wanted to read an article with no distractions. However, when I turned on Just-Read, all that was displayed were the links at the bottom of the page. This does not seem to happen on every page; without searching around too much, it only seemed to occur on pages within a "series" of articles. 
![snip](https://user-images.githubusercontent.com/34356237/33744542-832ccf6e-db66-11e7-8775-a69a7952f383.PNG)

**Comment by ZachSaucier** [comment]
Thanks for the report! Can you please provide a direct link to a problematic page on Encyclopedia Dramatica?

**Comment by Peartato** [comment]
Sorry for the delay!
Here's the link for the page I screencapped up there:
https://encyclopediadramatica.rs/Mighty_Number_9

**Comment by ZachSaucier** [comment]
What OS are you using? And have you made any changes to the stylesheet?

Using Windows, the default stylesheet, and JR's auto-selection, I am getting the full page's content, not just the links at the bottom

**Comment by Peartato** [comment]
I'm using Windows 7 and have made zero changes to anything. When I click the blue icon to active JR, I still get just the links. I just tested it again, following the link I'd provided.

**Comment by Peartato** [comment]
Am I just doing something wrong?

**Comment by ZachSaucier** [comment]
It doesn't sound like you're doing anything wrong. Maybe it's an OS specific error (I'm on Win 10).

For now you can work around the issue by using JR's [user-selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) but I'll see if I can eventually get a Win 7 PC to test on to look more deeply into the issue. 

Thanks again for the report!

**Comment by ZachSaucier** [comment]
I'm going to combine this with #94 as the core issue is the same.
