### ISSUE TITLE
Duplicated Article Header and Image

### ISSUE THREAD

**Issue by yanother1** [ZachSaucier/Just-Read#129]
http://fox2now.com/2018/01/05/man-charged-with-terrorism-in-stopping-of-amtrak-train/

This was the second article I read with Just-Read.  The article header and image are duplicated.
(Looking for alternatives to Clearly)

So far, other than this issue, Just-Read is looking good.

**Comment by ZachSaucier** [comment]
Thanks for the report! I'm glad you are liking Just Read. 

Could you please include an image of the effect that you're seeing? I am not understanding what exactly you're thinking should _not_ be included in the Just Read version.

**Comment by yanother1** [comment]
Interestingly enough the page has changed since yesterday.  Previously there was a static image of the man, today there is a video.  Today the page displays properly.

Thanks for your quick response.
