### ISSUE TITLE
Switch to full-screen when in reader mode

### ISSUE THREAD

**Issue by ljs** [ZachSaucier/Just-Read#130]
Hi,

Congrats for the nice plugin. I have used in my local copy of the extension this chunk of code, to automagically switch to full screen when activating reader mode.

[https://github.com/sindresorhus/screenfull.js/blob/gh-pages/src/screenfull.js](https://github.com/sindresorhus/screenfull.js/blob/gh-pages/src/screenfull.js)

It works very well (I guess I also turned-off some of your transitions.. the cool effects :) ).

But after your last update one-two weeks ago.. I've lost my local changes of course. Can I ask to add it with a check-box tick in the Options page may be. Or if you can add full-screen functionality via other means if this one does not suit you.

Thanks!
L.

**Comment by ZachSaucier** [comment]
I'm glad you like it! Thanks for the suggestion. 

Auto-enabling full-screen isn't a bad idea. The link you've provided seems to be a 404 page for me - is there another link to it?

**Comment by ljs** [comment]
Now the link works.

**Comment by ZachSaucier** [comment]
This feature was added under "Additional options" as of JR version 1.1.9

**Comment by ljs** [comment]
Hooray! Fantastic!

**Comment by ZachSaucier** [comment]
This functionality has stopped working in Chrome. Not sure why. It would never work in Firefox which I am now supporting as well, so going to drop support.
