### ISSUE TITLE
Please support Firefox with WebExtensions

### ISSUE THREAD

**Issue by andreicristianpetcu** [ZachSaucier/Just-Read#135]
Hello,

Chrome extensions just work in Firefox most of the time since Firefox has almost all Chrome API and a few added ones https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs conversion is usually very simple https://vimeo.com/241435808

Can you please support Firefox also? https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

Thank you!

**Comment by ZachSaucier** [comment]
Hello and thanks for the report! 

This has been at the top of my to-do list for Just Read for a while now, but I haven't taken a day of my free time to try and do this properly, especially because it would make maintaining the project more complex. Thanks for making a formal issue for it! 

I may not personally get around to doing this until the summer when I should have more free time.

**Comment by marcusnewton1** [comment]
Hi @ZachSaucier, bumping this. Would love to see this for Firefox. I'm incredibly impressed with how customisable this is.

**Comment by ZachSaucier** [comment]
I got around to porting JR to Firefox today. [Here's the free version](https://addons.mozilla.org/en-US/firefox/addon/just-read-ext/) - help finding any bugs is appreciated!

I ported Just Read Premium as well, but I haven't set up a way to handle payments so I can't just put it on Mozilla's add-on site.

**Comment by rodrigaj** [comment]
Would love to see JR Premium available for Firefox.

**Comment by andreicristianpetcu** [comment]
Thank you! @ZachSaucier

**Comment by MikeBlueberry** [comment]
Another vote from me.

**Comment by andreicristianpetcu** [comment]
@ZachSaucier why would it be so hard? the API differences between ff and chrome are minor.

**Comment by ZachSaucier** [comment]
The newest version of Just Read (v 5.0) now supports Premium features in every browser including Firefox 🥳 
Please let me know if you run into any issues.
