### ISSUE TITLE
 the paint brush icon it doesn't work  

### ISSUE THREAD

**Issue by fadyfaraday** [ZachSaucier/Just-Read#136]
when i i click on  the paint brush icon nothing happens 
please fix it  i really love  this extension

**Comment by ZachSaucier** [comment]
Thanks for the report. Does this happen for you on every webpage or just one site in particular?

**Comment by fadyfaraday** [comment]
yes,this happen on every webpage

**Comment by ZachSaucier** [comment]
What browser and OS are you using? Are you using any other extensions?

**Comment by fadyfaraday** [comment]
manjaro linux os and chrome , yes,i'm using other extensions like lastpass and  HTTPS Everywhere

**Comment by ZachSaucier** [comment]
Are you using a custom theme? Or the default one?

**Comment by fadyfaraday** [comment]
the default , here is a video about this problem
https://www.youtube.com/watch?v=re7AzZrclXo 
and thank you for replying

**Comment by ZachSaucier** [comment]
Thanks for the video! I'll see if I can find a Linux PC to test on at some point.

**Comment by fadyfaraday** [comment]
hey.. i fixed it.
the problem  was another extension 
in case if anyone have the same problem . it was the Dark Mode extension by Grephy
thank you for this  beautiful extension , Keep up the good work.
have a nice day.

**Comment by ZachSaucier** [comment]
Glad to hear you got it fixed! Thanks for commenting.
