### ISSUE TITLE
Saving customised CSS fails without warning when quota length exceeded

### ISSUE THREAD

**Issue by hyphenminus** [ZachSaucier/Just-Read#138]
As mentioned [on the Chrome webstore](https://chrome.google.com/webstore/detail/just-read/dgmanlpmmkibanfdgjocnabmcaclkmod/support?utm_source=chrome-app-launcher-info-dialog) (2017-12-28 and 2018-02-18), saving CSS still sometimes fails without any warning or error message. Thanks for your responses and your invitation to provide more detail here.

On checking the JavaScript console warnings, the following error is reported in `options.html:1`: 
`Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
at setStylesOfStorage (chrome-extension://.../options.js:103:29)
at HTMLButtonElement.saveTheme (chrome-extension://.../options.js:378:9)`

I am currently using JustRead 1.1.6 (released 2018-02-19) with Google Chrome (64.0.3282.167 64-bit on Windows 10 Home 1709).

Experimenting further, I find that I get the above problem if trying to save CSS with 8,117 characters. But if trying to save CSS with 9,583 characters I get a proper error message box as expected ("_Just Read / File did not save: Your stylesheet is too big. / Minifying it or removing lesser-used entries may help. You can minify it at: https://cssminifier.com/_").

So, at first glance, it seems likely that there is a problem area where CSS length is too long to save without exceeding the quota but too short to trigger the error message.

But note that in addition to the above custom CSS file, I have separately kept saved the default CSS of 7,588 characters (your `default-styles.css` in addition to my custom `default-styles(1).css`). So perhaps the quota is struggling with the combined length of multiple CSS files whereas the error message test is only counting the current CSS file. Or perhaps there is an issue with counting multi-byte characters (though I have only used common ASCII characters in my stylesheet).

**Comment by hyphenminus** [comment]
On looking at [your code](https://github.com/ZachSaucier/Just-Read/blob/master/options.js#L342), I see that you report an error if `byteLength(editor.getValue()) > 8000)`.

Comparing this with the `chrome.storage` [documentation](https://developer.chrome.com/extensions/storage#property-sync-QUOTA_BYTES_PER_ITEM), "_8,192 | `QUOTA_BYTES_PER_ITEM` | The maximum size (in bytes) of each individual item in sync storage, as measured by the JSON stringification of its value plus its key length...._"

So maybe there is some overhead from Chrome's JSON wrapper that causes the text to save to exceed 8,192 bytes even though the editor length of the CSS text is not more than 8,000 bytes. (The existence in my settings of another stylesheet seems to be irrelevant to my problem, as `QUOTA_BYTES` for all items is much higher: 102,400.)

Rather than arbitrarily lowering the 8,000 error threshold, a more robust fix might be to move the error trap to testing the return value of [`chrome.storage.sync.set(obj)`](https://github.com/ZachSaucier/Just-Read/blob/master/options.js#L103) in `function setStylesOfStorage()`.

As no one else has reported this, I guess I must be unusual in having both retained all your original CSS in one CSS file while also saving my derived custom CSS in a file of similar size. It had not occurred to me that this would be an extreme scenario!

Alternatively, if you simply wanted to reduce the size of your default CSS to leave greater margin for its customisation and avoid refatoring the code, I would suggest that the default styles relating to SVG images are relatively expendable given the number of bytes they take up.

I hope that is of assistance.

**Comment by ZachSaucier** [comment]
This should be fixed as of JR version 1.1.18. `chrome.storage`'s documentation is pretty bad, I had no idea it accepted a callback or how to catch an error using it until searching for a while.
