### ISSUE TITLE
How to remove "Viewed using Just Read . Report an error". Any permanent solution ?

### ISSUE THREAD

**Issue by AhmedNazir** [ZachSaucier/Just-Read#140]

**Comment by ZachSaucier** [comment]
The simplest way to remove this would be to add the following line to the stylesheet you're using in JR's options: `.simple-ext-info { display: none; }`

**Comment by AhmedNazir** [comment]
Not working

**Comment by ZachSaucier** [comment]
@AhmedNazir It works for me. How have you added it to your stylesheet? Have you changed any styles from the default?

**Comment by AhmedNazir** [comment]
working.....

Thanks.
