### ISSUE TITLE
Just Read doesn't render Ghostbin raw texts correctly

### ISSUE THREAD

**Issue by jp06** [ZachSaucier/Just-Read#141]
I mean it doesn't work on them. For example this page which is raw text: https://ghostbin.com/paste/7wtgd/raw

**Comment by ZachSaucier** [comment]
Something weird is going on with that site that's not allowing JR to work properly... I'll investigate more when I get more time.

**Comment by ZachSaucier** [comment]
This should be fixed as of JR version 1.1.10.
