### ISSUE TITLE
Feature suggestion: Deactivate links when delete is active

### ISSUE THREAD

**Issue by pato7** [ZachSaucier/Just-Read#143]
Would it be possible to deactivate links when delete is active? Sometimes it happens than when trying to delete some section I click on the link and it follows to new page.

**Comment by ZachSaucier** [comment]
That's a good idea! Thanks for the suggestion. I'll add that fix in the next JR version.

**Comment by ZachSaucier** [comment]
This should be added as of JR version 1.1.10.
