### ISSUE TITLE
just read on no fear shakespeare

### ISSUE THREAD

**Issue by indigobeam** [ZachSaucier/Just-Read#145]
the read tool doesn't filter out the adds on the side

**Comment by ZachSaucier** [comment]
Thanks for reporting this behavior! 

I assume you mean pages on SparkNotes [like this one](http://nfs.sparknotes.com/antony-and-cleopatra/page_2.html)? Unfortunately there's nothing in the markup of the page to describe them as being ads (essentially JR can't know generically that they're ads). 

As such, you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select just the content you'd like, edit your stylesheet in Just Read's options to hide them (using something like `#ad-skin-bg .sidebar-media { display: none; }`), or use [deletion mode](https://github.com/ZachSaucier/Just-Read#deletion-mode) to remove it once JR has already selected it. 

Given it's a very specific error limited to just SparkNotes, this is a won't-fix for now.
