### ISSUE TITLE
read mode looks weird 

### ISSUE THREAD

**Issue by phihh** [ZachSaucier/Just-Read#146]
https://docs.microsoft.com/en-us/visualstudio/debugger/getting-started-with-the-debugger

The above link looks weird in read mode .
There are a few pictures looks big

**Comment by ZachSaucier** [comment]
Which parts are looking weird to you, specifically? I'm not seeing any big red flags...

**Comment by ZachSaucier** [comment]
I'm closing this issue due to a lack of response and no clear issue.
