### ISSUE TITLE
Feedback requested: Page-Requested Reader Mode

### ISSUE THREAD

**Issue by jab** [ZachSaucier/Just-Read#149]
I just wrote up a proposal for a standard I think you'd find interesting: https://github.com/jab/reader-mode

If you have a moment, please take a peek and let me know what you think.

Thanks for any feedback, and thanks for the great work on this extension!

**Comment by jab** [comment]
Hi @ZachSaucier, since I opened this, several people I know who write well-read programming blogs (e.g. [1], [2], [3] etc.) have expressed interest in this, and seem willing to add the `Reader-Mode: true` header to their blogs. A lot more bloggers will do this too once word spreads and there's support from an extension or two.

Given that, would you accept a pull request that added support for automatically enabling Just Read on pages that include the PRRM header (or equivalent `<meta>` tag)?

[1] http://danluu.com/
[2] https://blog.bonnieeisenman.com/
[3] https://peterlyons.com/problog
et al.

**Comment by ZachSaucier** [comment]
No, I don't believe I will accept any pull request like this unless the meta tag gains a lot of popularity. I don't believe the concept of the meta tag is a good one in the first place - authors should seek to have their page formatted in a way that reader modes aren't necessary and reader extensions like Just Read should be able to auto-detect a true article in the first place.

**Comment by jab** [comment]
> authors should seek to have their page formatted in a way that reader modes aren't necessary

But this isn't possible without adding nontrivial page weight, slowing page load times for readers with poor internet connections and/or low-end devices. This has causes several blogs such as danluu.com to drop readability-improving styles. Having no option to improve readability without introducing page weight has caused the pendulum to swing too far in the other direction. This proposal provides the missing solution.

> reader extensions like Just Read should be able to auto-detect a true article in the first place.

I think auto-detection is orthogonal. Whether an extension can auto-detect or not, there should be a way for publishers to declare their preference for Reader Mode to be used when available. Different Reader Mode extensions may implement auto-detection/activation differently. But supporting some explicit syntax provides a common baseline that different implementations can all agree on.

I'm glad to hear you'd reconsider if the idea gains popularity.
