### ISSUE TITLE
Allow temporary disabling JustRead auto-run

### ISSUE THREAD

**Issue by Northnroro** [ZachSaucier/Just-Read#150]
Even a website is in the auto-run list, sometimes (at home) we need to perform some actions (eg. answer a thread), while sometimes (at work) we just need to read the posts and comments.

Therefore, I suggest a icon right-click option to have `Enable/Disable Auto-run` menu.

**Comment by ZachSaucier** [comment]
Thanks for the suggestion! It makes a lot of sense. There would likely have to be a checkbox on the Options page to allow this option to be found by people who aren't aware of the right click's context menu and an additional option in the "Additional options" section to hide the context menu entry for those who never use this feature. 

I'll give this some more thought and don't have time to implement it today, but this is likely something that will be added in the next version of Just Read. Thanks again for the suggestion!

**Comment by ZachSaucier** [comment]
Upon thinking about this request more in depth, an alternative would be to simply add a character to the entry (or entries) that you want to temporarily disable in the auto-run list. Then when you want to reactivate it, you simply remove the added character(s). This seems like just as much work as opening the Options page and clicking a checkbox to me, so I'm going to deny this feature request and close this issue.
