### ISSUE TITLE
Implement an "undo" functionality for deletion mode and editing meta information

### ISSUE THREAD

**Issue by ZachSaucier** [ZachSaucier/Just-Read#156]
It would be useful to have a "CTRL + Z" undo type of functionality when an element is accidentally clicked in deletion mode or edited incorrectly so that the whole page/selection would not have to be re-selected.

**Comment by ZachSaucier** [comment]
Undo now works as of JR version 1.2.1 and in all versions of Just Read Premium.

**Comment by pato7** [comment]
Would it be possible to add a dedicated icon for this action as well?

**Comment by ZachSaucier** [comment]
It's possible, but what's your reasoning behind wanting it? I think "Ctrl + Z" to undo is a well known action and adding a specific button for it would go unused the majority of the time, plus it'd make JR more cluttered.

**Comment by ZachSaucier** [comment]
I think that's reasonable and I can allow it to be disabled through the Options page. I'll implement it when I get some time. Thanks for suggesting it!

**Comment by ZachSaucier** [comment]
This should be live now! You should have access as soon as your JR version updates to the latest.

**Comment by pato7** [comment]
When printed, undo icon remains visible.

**Comment by ZachSaucier** [comment]
Oops, good call. I'll fix that now. Thanks!

**Comment by ZachSaucier** [comment]
Actually, that is likely because your setup is using a cached version of the required stylesheet (I had to update it due to recent changes). Can you try [hard refreshing](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/) by holding <kbd>Ctrl</kbd> while you press the refresh button?

**Comment by ZachSaucier** [comment]
I take that back. Yes, this is a but because of a missing `!important` in the free version. Updating now. Thanks for catching it!
