### ISSUE TITLE
Article text is ignored (theatlantic.com)

### ISSUE THREAD

**Issue by baz357** [ZachSaucier/Just-Read#157]
The article text is ignored, instead Just Read shows the "Most Popular" article previews from *below* the article. Weird.

https://www.theatlantic.com/technology/archive/2018/05/ring-ring-ring-ring/561545/

**Comment by ZachSaucier** [comment]
Thanks for the report! Until this is fixed, you can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select content on problematic pages like the one you linked.

**Comment by baz357** [comment]
Ah, cool, thanks for letting me know. Great extension!

**Comment by ZachSaucier** [comment]
Does this error still occur for you @baz357 ? I can't reproduce it any longer on the given page.

**Comment by baz357** [comment]
@ZachSaucier *That* issue is gone, but there are two other problems:
- the chart above "Chart derived from YouMail’s Robocall Index" is missing from the "Just Read" version of the page
- the small "MORE STORIES" list on the original page is blown up to more than a page in size in the "Just Read" version

**Comment by ZachSaucier** [comment]
- I see the chart in my version.
- The "more stories" is larger because they use CSS to make it smaller on the original page and that (all) CSS is removed in JR. You can completely hide that section or customize it to your liking in JR by editing your stylesheet on JR's Options page.

**Comment by diego898** [comment]
I dont know if I should make a new issue, but I see this happening (empty just read) on this page:

http://slatestarcodex.com/2018/07/03/ssc-journal-club-dissolving-the-fermi-paradox/

**Comment by ZachSaucier** [comment]
@diego898 Thanks for the report. That's actually a duplicate of issue of #94. I added the site you link to the list of problematic sites there.

**Comment by diego898** [comment]
thanks @ZachSaucier!
