### ISSUE TITLE
Doesn't work with ScriptSafe extension on some sites

### ISSUE THREAD

**Issue by batterscher** [ZachSaucier/Just-Read#161]
Hi Zach,

first of all: FINALLY! Searched for something like this for aeons!! Thanks!

When trying to let your extension make articles on heise.de (German IT news) readable, it results in an "Aw, Snap!" page. :(

Interestingly that doesn't happen when I have the Chrome dev tools opened - but the console doesn't show anything. Nevertheless I tested and found that ScriptSafe seems to be the source of the issue - after disabling it, there is no page error. Pages on other domains I tested worked although ScriptSafe was enabled.

Do you know anything about issues with that extension and/or do you have suggestions for a solution?

Thanks & Regards
Robert

**Comment by ZachSaucier** [comment]
Hello and thanks for the report.

I hadn't heard of ScriptSafe. Can you please provide a screenshot of the "aw, snap!" page that you're talking about? JR doesn't have a page like that built it, but it sounds like a Chrome error page.

**Comment by batterscher** [comment]
Hi Zach,

it is the Chrome error page alright - here is the screenshot (it's "aw, snap!"...just in German), but I don't think you can get much out of it.
![2018-06-26 17_06_29-clipboard](https://user-images.githubusercontent.com/38646857/41921534-5dce97f2-7963-11e8-8e5d-e5b3b65795aa.png)
Also this is the URL of an article I tested it with: https://www.heise.de/newsticker/meldung/In-eigener-Sache-Nvidia-NDA-als-Maulkorb-fuer-Journalisten-4091751.html?wt_mc=rss.ho.beitrag.atom

ScriptSafe is a Chrome-version of NoScript - I guess that's better known.

**Comment by ZachSaucier** [comment]
It's likely due to a rendering error in Chrome. Is it unacceptable for you to just whitelist heise.de in ScriptSafe?

**Comment by batterscher** [comment]
Heise.de itself is already whitelisted, but apparently some other removal done by the extensions breaks the code.
It's too bad that the console doesn't show anything and frankly my CSS skills are not up to the task of determining the source by hand :( 
Apart from that I am not (yet) annoyed enough to go for full trial and error ;)

Maybe someone with more know-how a/o time gets to google this and follow up on it - I'd appreciate that a lot!

@ZachSaucier: Thanks a lot for the very fast responses!

**Comment by ZachSaucier** [comment]
Alright, closing this for now then.
