### ISSUE TITLE
Incorrect Article Grabbed

### ISSUE THREAD

**Issue by vexir** [ZachSaucier/Just-Read#163]
Try it on this page: https://www.forbes.com/sites/amandagreenberg/2018/05/18/equity-crowdfunding-is-changing-the-funding-landscape-for-underrepresented-founders/3/#7e791191c4ea

For me, it grabs the article about compensation, not about equity crowdfunding. This could have been because I scrolled down by accident and then scrolled back up. When I refreshed the page, it was correct.

**Comment by vexir** [comment]
No problem. A refresh fixed it as it unloaded the second article.

E

**Comment by ZachSaucier** [comment]
Merging this into #331 which is a larger issue that contains this issue.

**Comment by ZachSaucier** [comment]
Another example of this sort of page: https://github.com/ZachSaucier/Just-Read/issues/331

**Comment by ZachSaucier** [comment]
Another example: https://github.com/ZachSaucier/Just-Read/issues/431
