### ISSUE TITLE
Conflict with Yet Another Hints Extension

### ISSUE THREAD

**Issue by vfaronov** [ZachSaucier/Just-Read#164]
Thank you for Just Read, it looks great.

However, it conflicts with a hit-a-hint extension named [Yet Another Hints Extension](https://github.com/Lepovirta/yahe). When I press the YAHE keyboard shortcut in JR mode, nothing happens. I’ve tried Ctrl+M (YAHE’s default) and Ctrl+Q. This seems to be a scripts conflict, not a styles conflict, because YAHE’s hints container element does not change from `display:none` to `display:block`. The devtools console shows nothing.

Of course, this might not be an issue with Just Read (although YAHE works for me nearly everywhere), but maybe you have some ideas, so I don’t have to debug?

**Comment by ZachSaucier** [comment]
Hello and thanks for the report! 

This limitation is on the other extension's side and has already been documented in issue #29. Please refer to that issue for more details. You should contact Yet Another Hints Extension if you want it to get it working with Just Read.

**Comment by ZachSaucier** [comment]
The shared version of Just Read pages in the premium version of Just Read now supports extensions like this one. See [this post](https://github.com/ZachSaucier/Just-Read/#q-x-extension-doesnt-work-with-the-just-read-version-of-my-page-how-can-i-get-it-to-work) for more information.
