### ISSUE TITLE
suggestion: auto-remove recurring blank lines

### ISSUE THREAD

**Issue by baz357** [ZachSaucier/Just-Read#167]
When you use JR on http://www.spiegel.de/international/world/world-trade-organization-in-trouble-amid-trump-trade-war-a-1215802.html you'll see a lot of blank lines/ white space.

How about auto-removing recurring blank lines? That would reduce this white space issue a lot.

**Comment by ZachSaucier** [comment]
Hello and thanks for the report.

Just Read should remove extra blank lines. I'm not seeing the blank lines that you're mentioning on the linked article. Can you please upload a screenshot of the spacing that you're talking about? And what operating system are you on?

**Comment by baz357** [comment]
Hey Zach, this is really weird: since I opened this issue Windows (10) crashed, and when I just now wanted to take a screenshot I saw that JR does *not* show those blank lines I mentioned!

JR's output now looks perfect :)

**Comment by ZachSaucier** [comment]
Glad to hear it!
