### ISSUE TITLE
mobile, save in txt

### ISSUE THREAD

**Issue by maxidax** [ZachSaucier/Just-Read#170]
Hi. Your application well works also in the mobile browser.
Only the press isnt necessary. Preservation of txt is very necessary.

Sorry my english :)

**Comment by ZachSaucier** [comment]
I'm sorry, I don't understand what you're trying to say. What do you mean by "press"? 

Is this a comment? An error? A recommendation?

**Comment by maxidax** [comment]
Sorry not press, - PRINT :) It isnt necessary
Simple preservation in txt is very necessary
For mobile devices

Mobile browser I use + Your application
https://play.google.com/store/apps/details?id=com.yandex.browser
20 июля 2018 г. 20:59 пользователь "Zach Saucier" <notifications@github.com>
написал:

**Comment by ZachSaucier** [comment]
Ah, so you're saying to not show the print button for mobile?

How are you using Just Read on a mobile device anyway? Extensions don't work on phones.

**Comment by maxidax** [comment]
An opportunity to change Print to Save is necessary
21 июля 2018 г. 16:01 пользователь "Zach Saucier" <notifications@github.com>
написал:

**Comment by ZachSaucier** [comment]
There's no way to programmatically call the browser's save functionality. As such, the "print" button can't be switched to a "save" button. With that being said, you can use the print functionality to "Save as PDF" which seems sufficient to me.
