### ISSUE TITLE
Send to Kindle and Gradient text

### ISSUE THREAD

**Issue by sorburu** [ZachSaucier/Just-Read#175]
Hi,

Testing the new Premium:
+ The send to Kindle is not working, after sharing the article and clicking "Send to kindle" it stays "Sending...." but does not send anything. Maybe problem is on Amazon side?? (have the permissions right)
+ I activated the "Gradient text" but don't see anything changed when reading articles wit JR...

Congrats and keep the good job!!

- Windows 10
- Google Chrome 67

**Comment by ZachSaucier** [comment]
Thanks for bearing with me in this. 

Apparently I forgot to set a default to the gradient colors. I updated it so future versions there is a default, but if you change one of the colors it should work for you right now.

As for the Kindle error, I'm seeing the same thing now. It worked in the past, so I'll try to figure out what's going on.

**Comment by sorburu** [comment]
Yes, changed a color and is working now. The extension is automatically updated right?

Ok will stay tunned for the Kindle option, thank you!!

**Comment by ZachSaucier** [comment]
Yes it updates automagically :smile:

**Comment by ZachSaucier** [comment]
Since the gradient part of this issue is fixed, I'm going to close this issue in favor of the more specific one to the Kindle issue: #180
