### ISSUE TITLE
Ability to don't apply Gradient text to images

### ISSUE THREAD

**Issue by sorburu** [ZachSaucier/Just-Read#177]
Hi Zach, is there a way for removing the gradient to images? not a big deal but images appear weird :)

https://ibb.co/mg2trK

**Comment by ZachSaucier** [comment]
Ya. I can probably detect when this is happening and work around most use cases. I'll get to it probably soon because it shouldn't be that hard but it's low priority.

**Comment by ZachSaucier** [comment]
JRP should not apply the gradient on stand alone images now (version 3.0.6+). Inline images (with text or other elements around it within a paragraph) will still have the gradient applied. If you come across use cases where this is much of a problem, please let me know and I can consider reworking the functionality.
