### ISSUE TITLE
Can't make Comments

### ISSUE THREAD

**Issue by sorburu** [ZachSaucier/Just-Read#178]
When clicking the "Add a comment" button to leave a comment a comment box appears and dissapears in less than a second...

**Comment by ZachSaucier** [comment]
This is due to a change in the default stylesheet that I implemented yesterday. Sorry about that. I should have tested more. I'll release a fixed version now.

**Comment by ZachSaucier** [comment]
I appreciate you helping test out JRP features and making reports though. I literally started a new job the day after I released JRP so it's been hectic doing a bunch of things for that while still trying to fix a few errors in it.

**Comment by MichaelW89** [comment]
I have the same problem.

**Comment by ZachSaucier** [comment]
@MichaelW89 Please stick to the issue you created, #236, because it is a different core issue than the one in this issue.
