### ISSUE TITLE
Ad won't go away

### ISSUE THREAD

**Issue by larilenao** [ZachSaucier/Just-Read#179]
"Thanks for using Just Read! I recently released a premium version of Just Read that has additional features like the ability to save and share Just Read versions of pages. I thought you might be interested in hearing about it." **text will not go away after I click 'not interested'. Is it on purpose? Defeats the purpose of the extension!**

**Comment by larilenao** [comment]
Aaand it's gone! Thanks :)

**Comment by ZachSaucier** [comment]
I'm glad it went away! Can you describe the issue you were seeing in a little bit more detail so I can try to make sure this won't happen for other users?

**Comment by larilenao** [comment]
Hi, Zach – sure! There was a pop up message at the bottom right of the screen announcing the premium version. Below the message I pasted above, there are two buttons – "I'm not interested" and "Tell me more". I **was** interested in learning more, so I clicked on the appropriate button and went to the premium version page – but the pop up never went away.

So I tried clicking "I'm not interested" as well, and still the pop up remained. It was there for a couple of days (I think). I turned the extension off and on, I tried reinstalling, tried looking at options and settings for a way of removing the message. 18 hours ago when I posted my message here was the first time I was able to use the extension without the pop up since it first appeared to me.

**Comment by ZachSaucier** [comment]
Ah, I think I understand what was going on. I released an update to the premium version that fixed the bug of it showing every time JR starts, so yours must have automatically updated sometime in between there. 

But this does help - I didn't think about how the notification should go away if users click on the "I'm interested" button. So the next version of Just Read will have this removed.
