### ISSUE TITLE
Does not send to Kindle

### ISSUE THREAD

**Issue by glacchia** [ZachSaucier/Just-Read#180]
> - Just Read version (free/premium version as well as the specific version number if possible)
Premium 3.0.6

> - Your operating system
Windows 10 - Chrome

I set the kindle sending with WiFi and one of my registered kindle devices.

The window stays forever with the message "Sending content..." but it is not sent: I do not receive anything on my kindle.

In some other instances the widget does not even load content.

Thanks,
Gilberto

![image](https://user-images.githubusercontent.com/42219853/43860124-04ba0342-9b53-11e8-9ce5-3011771fdbb3.png)

![image](https://user-images.githubusercontent.com/42219853/43860217-4dc4c360-9b53-11e8-94f9-d4464bf88667.png)

**Comment by ZachSaucier** [comment]
Thanks for the report! I've already started investigating this issue and can't find any issue on Just Read's side.

I contacted Amazon's support about 12 hours ago and am waiting to hear back from them about the Send to Kindle error.

**Comment by ZachSaucier** [comment]
I'm going to remove "support" for this until Amazon can get back to me. Until then, I've successfully been able to use the [Send to Kindle](https://chrome.google.com/webstore/detail/send-to-kindle-for-google/cgdjpilhipecahhcilnafpblkieebhea) Chrome extension on justread.link pages. I recommend that you do the same.

**Comment by ZachSaucier** [comment]
Closing this issue since it's no longer a built in functionality.
