### ISSUE TITLE
Georgia and Helvetica Over Linen

### ISSUE THREAD

**Issue by EverOmni** [ZachSaucier/Just-Read#182]
Here's my [Georgia-Helvetica](https://gist.github.com/EverOmni/b2af671427decd755dc9d63caa8d99a9) template for your viewing pleasure. I hope you enjoy it. 

### Specifications

**Body**
Font: Georgia
Background color: linen
Font color: dark olive green
Font size: 18px

**Headings**
Font: Helvetica
Font color: dark olive green

### Image Sample
![image](https://user-images.githubusercontent.com/28826690/43926963-c6fc10de-9be0-11e8-8b53-84a51b79d022.png)

**Comment by ZachSaucier** [comment]
I love you theme! But please copy and paste it to [the issue related to sharing themes](https://github.com/ZachSaucier/Just-Read/issues/4) by scrolling to the bottom and adding it there.
