### ISSUE TITLE
The annotation toolbar appears only in the first session(?)

### ISSUE THREAD

**Issue by sungwonida** [ZachSaucier/Just-Read#187]
First, I'm a Premium user, and once I turn a page into Just-Read mode, I can summon the toolbar [like this](https://i.imgur.com/goBVron.png) by dragging the sentence. But, when I turn the Just-Read mode off of the page by pressing ESC, and then re-enter the Just-Read mode again, I couldn't no longer see the toolbar.  
One naive way to solve this issue is to reload the page and then turn the page into Just-Read mode.

**Comment by ZachSaucier** [comment]
Thanks a lot for the report! I can reproduce this bug. 

I just fixed this in my local copy (it just took adding 1 line of code) so this should be fixed in the next version of JRP.

**Comment by ZachSaucier** [comment]
Just pushed this fix, available in JRP version 3.0.8.
