### ISSUE TITLE
Finding string in JR page doesn't focus to the position of the found string

### ISSUE THREAD

**Issue by sungwonida** [ZachSaucier/Just-Read#188]
When I 'Ctrl + F' and typed string I want to find in the JR page and then stroke RET, it turns out that it doesn't seem that JR focus on the position of the string. But it's obvious that JR found the string I want, which can be confirmed by dragging the mouse to the position of the string, I could see that string highlighted.  
Please have this issue reviewed.

Thanks.

**Comment by ZachSaucier** [comment]
This is a known functionality. I was essentially releasing an MVP of the Premium version in the initial release. I'll work on getting this implemented when I can find some time! Thanks for the report.

**Comment by ZachSaucier** [comment]
As of JRP version 3.0.10, it should jump to the first found instance of the searched string.
