### ISSUE TITLE
Too long Original URL in the dashboard

### ISSUE THREAD

**Issue by sungwonida** [ZachSaucier/Just-Read#190]
It would be pretty nice to have a fancier look of the dashboard since the 'Original URL' tab sometimes stretches too large.
Please refer below.
![image](https://user-images.githubusercontent.com/7530020/44640227-73d4a000-a9fb-11e8-90b8-0441b4c076ce.png)

**Comment by ZachSaucier** [comment]
Thanks for the report. I'm glad to see that someone is using the dashboard :smile:

This is a good idea and easily implemented. Can you please provide the long URL shown in a comment below so I don't have to go looking for another long one?

**Comment by sungwonida** [comment]
Sure. Here it is.
https://blog.ycombinator.com/learning-math-for-machine-learning/?utm_medium=email&utm_source=topic+optin&utm_campaign=awareness&utm_content=20180822+data+nl&mkt_tok=eyJpIjoiWVRnMFpHRTFNall5WkRCaSIsInQiOiJ6REFORXlCRWZmcGlmRWNLY081RXZkcVpESWVPMTAzeU4zZ0RsR2J4R21vOVVkYWhCdDJKeTFHZWc0Mys1dzA5VWgxTUR1djlPcU9nYmlUUHI0bWhheHI1YWtjT1ZBNnNKV1B3VDZvMzNJdnJ5QWNhWXpBMXdmMlRnaklESUFkSyJ9

**Comment by ZachSaucier** [comment]
Link text should truncate after 3 lines now. Thanks again for the suggestion!

**Comment by sungwonida** [comment]
Very nice. I'm satisfied with the current look. Thanks!
