### ISSUE TITLE
Just Read's auto selection on Q&A sites

### ISSUE THREAD

**Issue by ndaesik** [ZachSaucier/Just-Read#192]
- free version, current latest version.
- windows 10 with latest version of chrome.
- [link](http://www.korean.go.kr/front/onlineQna/onlineQnaView.do;front=E95C63820E40F58F9068B37F55520BBF?mn_id=61&qna_seq=89848&pageIndex=1)

the extension detected the post correctly, however on this site, on the link, a question and an answer is should be regarded as one article.
so "class=board_view" should be shown instead of "class=b_view_content" for this url. 
it's QnA and discussion site about whole grammatical Korean language issues ran by Korean government officially.
without displaying the answer on this site then this app is not usable on this url.
I don't know how many Korean people using this app and gonna try the site with this extension, but they would be pleasure to use if they wanted to do.
Thanks for the great extension however.

Best regards.

**Comment by ZachSaucier** [comment]
This is out of scope for Just Read given the extremely wide variety of ways that this sort of functionality can be implemented.
