### ISSUE TITLE
Just Read extraction stops mid-way through article

### ISSUE THREAD

**Issue by alexocampo** [ZachSaucier/Just-Read#195]
https://www.newyorker.com/sections/tech/insanely-good-making-big-business-out-of-social-philanthropy

The text provided by 'Just Read' stops at "This isn't philantrophy" midway through the article

**Comment by ZachSaucier** [comment]
Thanks for the report! This is the same as #95.

The work around for Just Read's auto-select fail is to use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode). 

Closing this as a duplicate.
