### ISSUE TITLE
White Style css not Working

### ISSUE THREAD

**Issue by Steiner29** [ZachSaucier/Just-Read#197]
This theme is not working for me. I just get an error message when I click the link. Can anyone assist?

Thank you for the amazing 👍 

Please find my white theme which I love to read, Hope you too like.

[white-style.css](https://gist.github.com/AhmedYahia-com/593cfe2d318318d9267e897219c73a55)

The style is :
1. dark background for the body.
2. white background for content only.
3. link mouse hover is red.
4. image is centered with light border.

Enjoy!

![screen shot 2017-02-07 at 10 53 08 am](https://cloud.githubusercontent.com/assets/1052415/22682636/c8303474-ed24-11e6-8267-01c519d54a17.png)

_Originally posted by @ayahia70 in https://github.com/ZachSaucier/Just-Read/issues/4#issuecomment-277927372_

**Comment by ZachSaucier** [comment]
Unfortunately that stylesheet link is now a 404 page. Do you have a copy of the CSS from that theme that you can share for me to test?

**Comment by Steiner29** [comment]
I unfortunately don't have a copy. I wish that I did.

*Jeffrey A. Steiner   *Analyst

Gallagher Fiduciary Advisors, LLC

**Comment by ZachSaucier** [comment]
I posted on the #4 thread asking the creator of this theme for the file. There isn't anything for me to do right now, so I'm going to close this issue.
