### ISSUE TITLE
A paid version of Just Read

### ISSUE THREAD

**Issue by ZachSaucier** [ZachSaucier/Just-Read#20]
### Edit: There's now a premium version of Just Read! See https://justread.link/ for more information.
___
After thinking about the future of Just Read and some requests that have been made (#8, #18, #34), I have decided to start work on a paid version of Just Read that would potentially have the following _additional_ features:
- Highlighting
- Annotations
- Saving the article in Just Read format (including edits, highlights, and annotations) to either a server or Google Drive (researching the feasibility currently)
- Sharing articles in a Just Read format, optionally including any highlights/annotations
- ---Searching through articles saved--- *This was too much of a technical issue to pursue right now.*

Possibly also:
- Edit-article-text ability
- Domain-specific (or partial URL specific) Just Read styles

___

**Question:**
Are there any other features that you'd like to see in a paid version?

__

**To be clear** I will continue to maintain and update the free version, it just won't have any of the specific features in the above list.

**Comment by brendanchua** [comment]
Loving the work you have done, Zach. Been searching for an app like this and would be happy to support/pay. 

Would be good to have the ability to add the main picture from the article.

**Comment by brendanchua** [comment]
Loving the work you have done, Zach. Been searching for an app like this and would be happy to support/pay.

Would be good to have the ability to add the main picture from the article.

**Comment by ZachSaucier** [comment]
Hey @brendanchua and thanks for the complement and suggestion! 

If the article formats their content well, Just Read should already pick up big images like that. I think it'd be best to create a new issue here on GitHub including details like the URL(s) that don't show this main image.

**Comment by Attelisk** [comment]
If you could save annotated pages directly to Google Drive as static .pdfs, it would be extremely convenient. I would gladly pay a monthly fee for that service, especially if you could in some way automate the date-tagging and parse LaTeX images.

**Comment by weaverhe** [comment]
If we can highlight in different colors I'd definitely pay for it. Also would love the ability to save to evernote with the highlights + annotations.

**Comment by iandunn** [comment]
I'm not sure if this would work [better as a paid feature or a free one](https://www.joelonsoftware.com/2013/04/30/free-as-in-fortune-cookies/), but I think it'd be helpful to have a quick/easy way to add a site to the `Auto-run domain list`.

Right now the flow is to:

1) Click on the `Chrome Settings` icon so that extension icons are visible. (I keep them hidden by default, to avoid distraction and clutter)
2) Right-click on the Just Read icon
3) Click on `Options`
4) Type the domain into the list
5) (Maybe?) hit `Save`? (It's not clear to me if the domain list is auto-saved or not)

So that's 3-4 clicks, plus manually typing out the domain name (or copy/pasting and removing the protocol & query string).

It'd be better for me if I just could right-click on the page and there'd be a menu item to add the current domain to the list (2 clicks); or if there was an option in the context menu for the `Just Read` icon (3 clicks).

**Comment by ZachSaucier** [comment]
Thanks for the suggestion! That's a good idea. I hardly ever add sites to the auto-run list so I hadn't thought about how long it takes. I think I'd add it to the right click context menu.

The auto-run list does not require saving FYI :)

**Comment by 8lall0** [comment]
I miss a lot a readability-style service for mobile devices.
I'd pay a fee for it.

**Comment by Phil-Champ** [comment]
Double-column reading format:

![image](https://user-images.githubusercontent.com/5921127/30860203-40aaead0-a2be-11e7-8c33-c339ec4caa41.png)

**Comment by drreen** [comment]
Just my 2 cents: At some point Google Chrome might compete with you if their data says that a reader feature resonates with the users. It takes them a tiny amount of resources to make your plugin obsolete.

Focus on features (such as integrations, interoperability, productivity), which Google might not be interested in implementing. That way you can move to their native solution and add value features on top of that - as soon as they enter the space.

**Comment by planotex** [comment]
Thanks for this extension, Zach.  I'm late to comment but was wondering if this could run automagically after loading a website?  I see a similar comment above about adding sites to autorun, but was thinking more along the lines of being able to browse websites and then have this extension run (without clicking).
Keep up the good work - we need extensions like this

**Comment by ZachSaucier** [comment]
@planotex Just Read already has an [auto run feature](https://github.com/ZachSaucier/Just-Read#auto-enable-just-read-on-specific-websites) as well as [hotkeys for running Just Read](https://github.com/ZachSaucier/Just-Read#use-just-reads-built-in-selection). What are you imagining differently than these features?

**Comment by planotex** [comment]
Thanks, I see that area now and I'm going to check it out.  
Was thinking about when I want to be in a read only mode and just want to catch up on stories without having to convert each website - maybe this fulfills that purpose.

**Comment by ZachSaucier** [comment]
@planotex Ah, I think I understand what you're wanting now. You want to navigate between all pages using the JR's view, right? 

I think this is a harder problem than you might imagine it would be across all websites. With the current functionality it can usually be done within a certain domain using the auto-run feature (I have an entry that is `nytimes.com/.+` which will run Just Read on any sub-page of the NY Times website, but not the homepage so that when I click on a direct link to an article it will open up in Just Read's view) and with links within an article (you can right click a link and click "View this page within Just Read"). 

But it is a very difficult problem to know which links are true navigation links and which ones are spam, unnecessary links to an article (at least without some ML algorithm checking all of the links - even then I'm sure the mistake rate would be relatively high). If someone can think of a good way to solve this, especially in a relatively simple way, I'd be happy to implement it, but as is I don't think Just Read can get much better at navigating between articles in its view than it currently does.

**Comment by planotex** [comment]
You got it. 
I see it would be a pain to figure out just legit links.  It's probably me just being lazy, lol and wanting to use JR for all pages.   Let's face it, the web sometimes is a pain with all the videos, audios, popups, advertisements, etc. for those of us that just like to "read" the web...

**Comment by ZachSaucier** [comment]
One user suggested having a way to send formatted content to Evernote to be saved as a note.

**Comment by sorburu** [comment]
Hi, great job here, thank you. Ideas for paid version:
- Deletion of a selection/multiple elements with one click (now i have to do lot of clics for deleting a list with various lines -one clic/line-), something like "drag and dellete" (like brushing) option?
- Save to pdf option (now im using the Print pdf)
- Saving to Evernote/G. Drive would be really nice too
- Ability to ignore embeded Vimeo/Youtube videos (now i get a black rectangle with Vimeo privacy alert -hidden videos- so ignoring this i wouldn`t have to Delete taht space)
- Ability to remove the "Viewed using Just Read" (i am mainly getting pdf-s from articles, so clearer is nicer :) )
Keep the good job!!

**Comment by sorburu** [comment]
Wow thank you very much, it worked with `iframe { display:none; }` i forgot that CSS was there!! ;)
Any news about the paid version?? i would love to be able to test the beta.
Best regards,

**Comment by ZachSaucier** [comment]
@sorburu I'll be turning my attention to Just Read after I complete a different personal project of mine. However, I am short on time so I can't make any promises in terms of a timeline. I'll keep this post updated.

**Comment by ZachSaucier** [comment]
## There's now a premium version of Just Read!

Included features: 

- Shareable Just Read pages including your custom theme
- Support for "Send to Kindle" (Google Drive is supported in regular Just Read and the premium version)
- Annotations, highlighting, and comments
- Linking to a specific part of the article
- Custom and customizable scrollbars
- Gradient text functionality for increased readability
- Auto-scrolling
- Image lightboxing
- Fixed <kbd>CTRL</kbd> + <kbd>F</kbd> functionality

For more information check out [Just Read's home page](https://justread.link/) or [the FAQ section](https://github.com/ZachSaucier/Just-Read/#faq).

**Comment by ZachSaucier** [comment]
To do on the premium version is to research the feasibility to create a way to share a page in the JR version for mobile Chrome. The mobile version wouldn't have the ability to customize all of the options like the Chrome extension has. 

Note that currently when you share a page in premium the link it creates is viewable in mobile.

**Comment by ZachSaucier** [comment]
The newest version of Just Read (v 5.0) now supports Premium features in every browser 🥳 
Please let me know if you run into any issues.
