### ISSUE TITLE
GUI open full styles button not working

### ISSUE THREAD

**Issue by WimDeBacker** [ZachSaucier/Just-Read#200]
Hi,

Possible bug:
- free version
- In the GUI, when I click 'open full styles', nothing happens

Wim

> Thanks for wanting to help improve Just Read! 
> 
> Looking through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) may help you with your request. Please look through [the existing posts](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed.
> 
> If you're submitting an error report, please include the following:
> 
> - Just Read version (free/premium version as well as the specific version number if possible)
> - Your operating system
> - Steps to recreate the issue including the relevant URL if necessary
> - A screenshot of what the page looks like (if relevant)
> 
> Please delete this text from your post before posting.

**Comment by ZachSaucier** [comment]
Thanks for the report! I fixed this and the change should be available later today in JR version 1.2.9.
