### ISSUE TITLE
default style svg tag

### ISSUE THREAD

**Issue by WimDeBacker** [ZachSaucier/Just-Read#203]
My last issue of the day:

More & more sites now use svg for icons (https://w3techs.com/technologies/details/im-svg/all/all). Without a svg tag the icons can become very large. I suggest to add an svg tag to the default-styles.css

Thanks

Wim

> Thanks for wanting to help improve Just Read! 
> 
> Looking through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) may help you with your request. Please look through [the existing posts](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed.
> 
> If you're submitting an error report, please include the following:
> 
> - Just Read version (free/premium version as well as the specific version number if possible)
> - Your operating system
> - Steps to recreate the issue including the relevant URL if necessary
> - A screenshot of what the page looks like (if relevant)
> 
> Please delete this text from your post before posting.

**Comment by ZachSaucier** [comment]
I'm trying to understand what you're really requesting here. Is there a site where there is an issue with this? 

Currently I already have the following in the default stylesheet which should limit the size of most inline SVG images: 

```
[class *= "emoji"],
[class *= "icon"] { width: 1em; }
```

Other SVG images (ex. a graph or something) *should* take up the full width of the content, which they do with the default styles. If you want more control over SVGs, you can simply add an SVG selector to your stylesheet:

```
svg { 
    /* Whatever you'd like */
}
```

**Comment by ZachSaucier** [comment]
Closing this at least until more information is given.
