### ISSUE TITLE
Auto-run domain in query string causing JR to auto-run - related to "Send from Gmail" Chrome extension

### ISSUE THREAD

**Issue by baz357** [ZachSaucier/Just-Read#204]
Just Read v. 1.2.9
Windows 10

> Steps to recreate the issue including the relevant URL if necessary

- Open an article from a site that's on your Auto-run domain list
- Click the "Send from Gmail" extension icon

The "Send from Gmail" extension will now open a new window with a Gmail URL to create a new email. The URL will be "https://mail.google.com[...]body=https://[URL_ON_YOUR_AUTO-RUN_LIST]/[...]", which is enough to cause JR to process that window. Which it shouldn't.

**Comment by ZachSaucier** [comment]
Hello and thanks for the report.

The auto-run domain list is checked using regex, so you can change your auto-run entries from something like `example.com` to `^(http|https)://example.com` or just `^https://example.com` (if you only visit the https version) to have JR not run on these pages.

**Comment by baz357** [comment]
Wow, perfect! And thanks for the near-instant reply! :)
