### ISSUE TITLE
Only one DIV rendered (title & byline), and nothing else - crookedtimber.org

### ISSUE THREAD

**Issue by SpiderJonny** [ZachSaucier/Just-Read#205]
Just Read 1.2.9 Free
Win 8.1
http://crookedtimber.org/2018/10/05/hoaxes-in-general/

![jr](https://user-images.githubusercontent.com/31634570/46611016-6c2d0e80-cb04-11e8-9f9f-5b37c660a3cc.jpg)

**Comment by ZachSaucier** [comment]
Hello and thanks for the report. This is the same core issue as #94, so I'll close it as a dupe and list this domain in the list there.

You can work around this issue by using [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode).
