### ISSUE TITLE
My fav style

### ISSUE THREAD

**Issue by jesuvio** [ZachSaucier/Just-Read#207]
![image](https://user-images.githubusercontent.com/44093225/46879697-afdd8c00-ce14-11e8-94da-bf335a89eacd.png) 

@import url("https://fonts.googleapis.com/css?family=Kreon|Source+Sans+Pro:400,700");
body { font-family: "Kreon", sans-serif; background-color: rgb(226, 222, 190); line-height: 1.6; font-size: 25px; color: rgb(68, 79, 102); text-rendering: optimizeLegibility; }
h1, h2 { font-family: "Kreon", sans-serif; font-weight: 700; }
h1 { font-size: 1.875em; line-height: 1.125; }
h2 { font-size: 1.45em; line-height: 1.2625em; }
h3 { font-family: Kreon, serif; font-size: 1.25em; line-height: 1.5; }
hr { height: 1px; background-color: rgb(216, 216, 216); border: none; width: 100%; margin: 0px; }
a[href] { color: rgb(76, 124, 150); }
a[href]:hover { color: rgb(155, 114, 111); }
.youtubeContainer { position: relative; width: 100%; height: 0px; padding-bottom: 56.25%; padding-top: 25px; }
iframe[src*="youtube.com/embed/"] { width: 100%; height: 100%; position: absolute; top: 0px; left: 0px; }
img { max-width: 100%; }
li { line-height: 1.5em; }
td { border: 1px solid black; padding: 3px 7px; }
pre { background-color: rgb(224, 224, 224); padding: 10px; overflow: auto; }
blockquote { border-left: 4px solid; padding: 15px 10% 15px 8%; margin: 1em 0px; font-size: 1.2em; line-height: 1.4; }
blockquote > :first-child { margin-top: 0px; }
blockquote > :last-child { margin-bottom: 0px; }
figure { margin: 0px 0px 10px; }
figcaption { font-size: 0.9em; opacity: 0.7; border: 1px solid rgb(238, 238, 238); padding: 17px 17px 12px; }
aside, [class*="sidebar"], [id*="sidebar"] { max-width: 90%; margin: 0px auto; border: 1px solid lightgrey; padding: 5px 15px; }
.simple-date { display: inline-block; font-family: "Source Sans Pro", sans-serif; font-size: 18px; padding-right: 15px; padding-top: 10px; padding-bottom: 10px; border-right: 1px solid rgb(216, 216, 216); }
.rtl .simple-date { border-left: 1px solid rgb(216, 216, 216); border-right: none; padding-right: 0px; padding-left: 15px; }
.simple-author { display: inline-block; font-family: "Source Sans Pro", sans-serif; font-size: 18px; color: rgb(187, 160, 60); line-height: 22px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; }
.rtl .simple-author { padding-left: 0px; padding-right: 10px; }
.simple-container { max-width: 700px; }
::selection {
  background-color: #e8c7a0;
  color: #444f66;
[class*="emoji"], [class*="icon"] { width: 1em; }

**Comment by ZachSaucier** [comment]
Thanks for sharing! 

But #4 should be used for this purpose. Closing this issue as a duplicate.
