### ISSUE TITLE
Icons placement to prevent text overlapping

### ISSUE THREAD

**Issue by mecool1** [ZachSaucier/Just-Read#208]
I've set Just-Read so that the text is pretty wide.

The problem with the horizontal placement of the 3 icons (edit, print, close) is that they overlap the text of the top line:

![justread](https://user-images.githubusercontent.com/12640485/46939948-d9422600-d067-11e8-823d-edda1b1a2996.jpg)

It would be cool to place these 3 icons vertically instead.

**Comment by ZachSaucier** [comment]
You're free to change it in your local stylesheet. Something like this should work:

```
.simple-print { top: 55px; left: 5px; }
.simple-edit-theme { top: 98px; right: 8px; }
.simple-delete { top: 140px; right: 8px; }
```

[See this post](https://github.com/ZachSaucier/Just-Read/issues/3#issuecomment-229514745) for more information on how to style these buttons.
