### ISSUE TITLE
next page hotkey disabled

### ISSUE THREAD

**Issue by adamp4** [ZachSaucier/Just-Read#209]
The next page hotkey is disableb in read mode, for example https://read.qidian.com/chapter/hmdUeQbO0Ag1/TB4EiQN7hdMex0RJOkJclQ2

**Comment by ZachSaucier** [comment]
你好 and thanks for posting your issue.

What is the next page hotkey (for me to test)?

**Comment by ZachSaucier** [comment]
Closing this until more information is provided.
