### ISSUE TITLE
Auto-run domain list / Launching unexpectedly

### ISSUE THREAD

**Issue by reaves** [ZachSaucier/Just-Read#21]
Hello,

I'm using the auto-run domain list for articles websites (www.euractiv.com ; www.lemonde.fr ; www.project-syndicate.org) however as it's currently implemented it's launching unexpectdly also in url containing this character as in the rss aggregator feedly (http://feedly.com/i/subscription/feed/http://www.lemonde.fr/)

I was previously using the extension permanent readability and it was possible to fine tune more precisely the url targeted (only specific domains, not the main page ...) as you can see on the sceenshot below.

![capture - permanent readability](https://cloud.githubusercontent.com/assets/1025687/20526268/a358ceec-b0c3-11e6-8a41-72baa27f5d71.PNG)

Best Regards

**Comment by ZachSaucier** [comment]
This is a good idea. I'll spend some time today looking into this, trying to find a way to give more control while retaining ease of use.

**Comment by ZachSaucier** [comment]
This should be implemented as of 1.0.13. See [this post](https://github.com/ZachSaucier/Just-Read/issues/15#issuecomment-262255204) for more detail

**Comment by reaves** [comment]
Thanks it's working perfectly now ;)

**Comment by vikramram** [comment]
How would I add all sites to the auto-enabling feature please? I tried a lot of options in vain...
^?=^.*.*.*
^*$

**Comment by ZachSaucier** [comment]
@vikramram If you want it to match literally every URL, you can use `.*` but to me that's very annoying 😛

**Comment by vikramram** [comment]
I am trying to auto-enable for ALL sites but a few like news.google.com, *.google.*, but I am unable to do it.
My list should look like follows:
.*
!site1
!site2

Also, just adding .* to enable for all sites actually blanks out all sites after loading for some reason, so I just added a few lines of gibberish before and after .* line to make it work.
Thank you for the extension - it works great and I feel I have control back again.
Much appreciated.

**Comment by ZachSaucier** [comment]
I think you'd have to build the `!`s into the `.*` query, meaning you have to use [something like this](https://stackoverflow.com/q/406230/2065702).
