### ISSUE TITLE
Just-Read Stopped Working

### ISSUE THREAD

**Issue by IMANWriter** [ZachSaucier/Just-Read#210]
Just-Read has just stopped working for me on Chrome. It maybe related to a resetting of Chrome settings, an update of browser or something else. I disabled every other extension and tried JR on some pages... nothing. The only thing that happens is that the red "on" badge appears for 2-3 seconds, but nothing else.

**Comment by ZachSaucier** [comment]
Hello and thanks for the report. Sorry that this is happening for you! 

Is this true on every web page that you try it on? Have you tried reinstalling Just Read? Are there any error in the console (you can check by pressing F12) after you click the Just Read button?

**Comment by ZachSaucier** [comment]
Closing this until more information is provided.

**Comment by ZachSaucier** [comment]
Thanks for giving me some more information. Based on your screenshot, it's some input/output (IO), i.e. filesystem, error that I've never seen before. Can you confirm that this same error occurs on all pages that Just Read doesn't work on for you?

Also, do you have any sort of antivirus installed on your computer that you're trying to use Just Read on?

The only `storage.get` (as seen in your console log) that is in Just Read is in the [dat.gui](https://github.com/dataarts/dat.gui) script...

**Comment by IMANWriter** [comment]
Here are the errors on two other pages:
On [Link](https://www.alternet.org/election-03918/texas-voting-machines-changing-senate-vote) ([screenshot](https://user-images.githubusercontent.com/1221810/48117631-0fe21980-e27f-11e8-8727-4cb584795dbe.PNG))
On [Link](https://news.vice.com/en_us/article/wj9vjz/these-are-some-of-the-most-racist-political-ads-of-2018) ([screenshot](https://user-images.githubusercontent.com/1221810/48117780-7f580900-e27f-11e8-961a-069f75eb09b3.PNG))

I use Panda Dome (Free) antivirus.

The highlighted errors (in screenshots) appear after I press the JR button in Chrome toolbar. Otherwise I have no clues about `storage.get` thingy.

**Comment by ZachSaucier** [comment]
Sorry for the delay. Hectic time. 

Can you try disabling Panda Dome completely (temporarily) and running JR and see if the same sort of errors appear?

**Comment by ZachSaucier** [comment]
As there's not anything more for me to do and it seems like a local issue, I'm going to close this issue until there is a need to reopen it.

**Comment by IMANWriter** [comment]
Weird! I also have JR on my laptop and (as I checked yesterday) it works. So it does seem like an issue with my work PC. Thanks for bearing with me, anyway. Sorry if I needlessly took your time. I'll keep on trying to fix the issue on my end.

**Comment by ZachSaucier** [comment]
No problem.
