### ISSUE TITLE
A better icon

### ISSUE THREAD

**Issue by samiq** [ZachSaucier/Just-Read#211]
hi Zach, thanks for a great service, love it... but there is something I can get thru with this service and I know, I know, it's stupid, but the icon is shit, I would for your service to have an accompany icon that is on par with the minimalistic nature of the service and I feel like icon does a disservice, it doesn't communicate the trust that should with it, I think Pocket does a better job at it, it blends with the browser and doesn't come up as amateur. I think that now that there is a premium version of the service it would be great to think about it. again, thanks for a great service and sorry if this comes up harsh or stupid.

**Comment by Zyst** [comment]
I like the icon

**Comment by sorburu** [comment]
Hi, was thinking about the idea of using a funnel (lab filter one :)
![SNAG-0000](https://user-images.githubusercontent.com/28994304/56497154-bbfd8100-64fc-11e9-9695-befa934acd6f.png)

**Comment by ZachSaucier** [comment]
@sorburu Thanks for the idea! That's not bad to match Just Read's *functionality*, but it doesn't really reflect Just Read's *name* or even the true goal of Just Read well. It also would likely be hard to understand what it is at small sizes (~30px wide).

**Comment by sorburu** [comment]
Still playing, funnel idea, "J" on the left and "r" on the right...
You mention "true goal of Just Read", would be interesting to define in one/two words the essence of it, moving then to a concept/image.
![SNAG-0000](https://user-images.githubusercontent.com/28994304/56654169-b71d0680-668f-11e9-8938-beb75e40c64d.png)

**Comment by ZachSaucier** [comment]
Closing this due to a lack of support.

**Comment by macx** [comment]
Would reopen the issue. Just take a option of three to five Icons from Material Design Icons, or let us upload one to the extension.

https://materialdesignicons.com/icon/read is nice, or this one: https://materialdesignicons.com/icon/book-open-outline
