### ISSUE TITLE
Elements with spaces deleted may be misleading

### ISSUE THREAD

**Issue by hyphenminus** [ZachSaucier/Just-Read#214]
Further to issue #206 (which you closed as the effect was by design and the problem in the example was essentially aesthetic, removing the space between two sentences):

A slightly more serious example of Just Read removing elements containing a non-breaking space, this time where it clearly impairs the semantics as well as aesthetics of the text:

https://www.gov.uk/government/publications/update-to-hasc-on-windrush-november-2018/update-on-the-work-of-the-home-office-in-relation-to-windrush-12-november-2018

In the first table in section 10, a non-breaking space is used to keep many table cells blank:

```html
<tr><td>2002</td><td>&nbsp;</td><td>1</td><td>1</td><td>&nbsp;</td><td>1</td></tr>
```

Just Read removes all of these <td> elements, effectively shifting many remaining cells to the left (to the first remaining non-blank places in each row):

```html
<tr><td>2002</td> <td>1</td><td>1</td> <td>1</td></tr>
```

Admittedly, in this case the discrepancies in the column totals are so great as to make it fairly obvious that something is wrong. But I think this now demonstrates that there is a plausible risk of other pages being affected in ways which might actually mislead readers.

A similar but hypothetical problem would arise if an element containing only a space were used to separate two numbers, which Just Read would presumably then merge: eg "`4<span>&nbsp;</span>5kg bags`" → "`45kg bags`". In general, it seems risky to continue assuming that white-space is never important. Moreover, the webpage example with table cells shows that even collapsing multiple white-space elements into a single element (rather than removing them all, as at present) would still result in misleading tabulations.

Though I quickly realised that the above example webpage was semantically distorted, the most dangerous cases will arise when the reader fails to notice the distortion and therefore fails to report it here! So I would again encourage you to be very cautious about modifying pages in ways which might conceivably alter their apparent meaning.

I hope this additional feedback is of further assistance. In any case, thank you again for your great work on Just Read.

Still using Just Read extension version 1.2.9 (free) on Chrome/Win10.

I appreciate your helpful previous responses to #206 but have reported this in case you now find the case more compelling. Not sure whether you would see this comment if I only appended it to the closed thread, so have opened this as a new issue, but of course feel free to move this to the original thread if appropriate. I see now that #6 also overlaps with this issue.

**Comment by ZachSaucier** [comment]
Thanks a lot for following up on this and providing more examples! I do in fact get notifications on old threads, but it's perfectly okay to start a new one in this case 😄 

I think you're right in that the default behavior should not to remove "empty" elements like this, especially since JR has a deletion mode now so that users can delete elements like these if they want to. I can't even find the old sites that I created this behavior off of. 

The next version of JR will have this functionality of deleting "empty" elements removed from it and it will behave like you describe. Thanks a lot for contributing!

**Comment by hyphenminus** [comment]
Great, thanks again Zach for the extension. And your deletion mode certainly is an excellent extra way to customise awkward pages!
