### ISSUE TITLE
Option to enable/disable right click context menu?

### ISSUE THREAD

**Issue by halkun** [ZachSaucier/Just-Read#22]
Hello, is it possible to implement a checkbox option to enable/disable for "Show context menu item on right click"?

Thanks.

**Comment by ZachSaucier** [comment]
You mean the menu item that asks, "View this page using Just Read", correct? That's not a bad thing to ask, but why is it a problem that it remains?

**Comment by halkun** [comment]
Hi Zach, thank you for your kind reply. I like to declutter and customize my context menu as much as possible. :)

**Comment by ZachSaucier** [comment]
I added these options in a new modal when "Additional options" on the Options page is clicked. It should be there as of version 1.0.14.

Thanks for the report!
