### ISSUE TITLE
Unable to use other plugins with this

### ISSUE THREAD

**Issue by Nimish4** [ZachSaucier/Just-Read#230]
> - Just Read version (free/premium version as well as the specific version number if possible) 

> FREE

> - Your operating system 

> Windows 10

> - Steps to recreate the issue including the relevant URL if necessary 

> Install Smooth Key Scroll plugin: `https://chrome.google.com/webstore/detail/smooth-key-scroll/gphmhpfbknciemgfnfhjapilmcaecljh/related?hl=en`

**Comment by ZachSaucier** [comment]
Hello and thanks for posting. 

This is actually a problem with Smooth Key Scroll, not Just Read. Please see [this FAQ question](https://github.com/ZachSaucier/Just-Read/#q-x-extension-doesnt-work-with-the-just-read-version-of-my-page-how-can-i-get-it-to-work) or [referenced issue](https://github.com/ZachSaucier/Just-Read/issues/29#issue-196499408) for more information.
