### ISSUE TITLE
"Unknown Date" Incorrectly Declared

### ISSUE THREAD

**Issue by jasondalycan** [ZachSaucier/Just-Read#232]
For blog post 'https://www.finextra.com/blogposting/15596/some-insights-on-fintech-financing-and-performance' reader mode declares the document to be of an "Unknown Date" yet the blog post has a date declared at the top when viewing the page in normal mode (located next to the author).

**Comment by ZachSaucier** [comment]
Thanks for the report! 

"Unknown date" in Just Read means that the places that Just Read looks for a date didn't come up with anything that could pass as a date. 

But it's been a while since I've looked into searching for article dates for Just Read, so I'll give it a look sometime soon.

**Comment by ZachSaucier** [comment]
I made some minor changes to JR's date selection so it works in cases like this one. It will be available in the next version of Just Read. 

I still am interested in having a whole different but better date, author, and title auto-selection mechanism in general, but I can't think of a better approach right now.
