### ISSUE TITLE
Does not render pages from the Financial Times

### ISSUE THREAD

**Issue by halbates** [ZachSaucier/Just-Read#233]
As you can see from below the text of the article is missing:
Feb 5, 2019
Philip Stafford
Investors fret about dual-listed shares under a hard Brexit
Viewed using Just Read

Report an error

> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> If you're submitting an error report, please include the following:
> 
> - Just Read version (free/premium version as well as the specific version number if possible)
> - Your operating system
> - Steps to recreate the issue including the relevant URL if necessary
> - A screenshot of what the page looks like (if relevant)
> 
> Please delete this text from your post before posting.

**Comment by ZachSaucier** [comment]
Hello,

Can you please include a link to the problematic page? I also don't see any image if you tried to include one.

**Comment by ZachSaucier** [comment]
Closing until more feedback is given.
