### ISSUE TITLE
Install Premium in Brave Browser

### ISSUE THREAD

**Issue by billmcaninch** [ZachSaucier/Just-Read#234]
I have purchased and installed the premium version on the Google browser on this computer, however, I'm switching to the Brave browser on this same computer. Can I transfer the version on the Google browser to the Brave browser? If so, how do I do so?

**Comment by ZachSaucier** [comment]
Hello,

I'm not familiar with how extensions on Brave work, but based on [Brave's support page](https://support.brave.com/hc/en-us/articles/360017909112-How-can-I-add-extensions-to-Brave-) it looks like you can install it directly from Just Read Premium's [Google webstore page](https://chrome.google.com/webstore/detail/just-read-premium/dpamdgmnffodphoamchpmbclkpmccjga) if you're logged into the Google account that you have Just Read Premium on. 

Let me know if you run into any problems as I believe it should still work. Officially only Chrome is supported by Just Read though 😄.

**Comment by billmcaninch** [comment]
Thank you. I installed it directly from the Google Web Store and I was not
asked to pay again. Brave is based on Chromium so can use any Google
extensions. My concern was how to install it a second time on the same
computer without having to pay again. Apparently, once I signed into my
Google account, it recognized that I had already paid.

**Comment by ZachSaucier** [comment]
Great!

**Comment by ZachSaucier** [comment]
The newest version of Just Read (v 5.0) now supports Premium features in every browser including Brave 🥳 
Please let me know if you run into any issues.
