### ISSUE TITLE
Deletion mode has problems with embedded youtube

### ISSUE THREAD

**Issue by klimcio** [ZachSaucier/Just-Read#235]
I tried to use deletion mode on [a website (example)](https://antyweb.pl/ale-ladne-zabawki-robi-ten-ubisoft-jak-gralo-sie-figurkami-statkow-w-starlink-battle-for-atlas) and noticed that I can't delete youtube video embedded on the site.

**Comment by ZachSaucier** [comment]
Thanks for the report! This bug should now be fixed. Your JR version should automatically update soon.
