### ISSUE TITLE
Comments-function doesn't work

### ISSUE THREAD

**Issue by MichaelW89** [ZachSaucier/Just-Read#236]
Whenever I try to add a comment, the comment-window shortly appears and vanishes after a second. I can nonetheless type and add the comment but it will be added to the very bottom of the page.

This only occurs if the maximum width is bigger than 700.

What can I do?

**Comment by ZachSaucier** [comment]
Hello and thanks for this report. I am aware of this issue and don't know of a good solution. It will also occur if you shrink your browser to a smaller size than the content's width. 

The core issue is: what should happen if the content is too wide for comments to be placed? Currently I'm handling that by placing the comments below the article's content (which is where the text box is going when the maximum width is over 700 for you). 

I'll continue to think about how to handle these situations - maybe a `[*]` that can be clicked to view the comment would be a good solution.

**Comment by MichaelW89** [comment]
I'm not sure if this helpful, but the screen's maximum width is far bigger than 700. There would be enough space to display the comment in the browser window. next to the body of the article. I can't really figure out why '700' is the critical value.

The asterisk would work fine for me. 

Thanks for the great product and the quick response.

Best,
Michael

**Comment by ZachSaucier** [comment]
I had set an arbitrary max value of 1000, but I changed it to `calc(100% - 320px)` which fits the default size of the comment box (pushing the changes to the webstore now). This should allow sizes higher than currently allowed to work properly but if the total browser window width is larger than that value, this error will still occur. 

I will get around to making an alternative on smaller screens sometime soon.

**Comment by ZachSaucier** [comment]
I remembered why I had the `max-width: 1000px` in there. It is because using the `calc` approach I said above makes the margins way too big for smaller windows. Instead, I just removed this outer max width (which should make the larger widths work but not break smaller widths).

**Comment by MichaelW89** [comment]
The comments are displayed correctly now. Thank you for the quick support.

Another but unrelated question: What is the smallest possible value for the auto-scroll function?

**Comment by ZachSaucier** [comment]
Technically the smallest possible value is negative infinity :D 

But any [double](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) would work. Is there an issue you're seeing?

**Comment by MichaelW89** [comment]
0.1 is still too fast for some texts and whenever I try to enter a smaller value, the auto-scrolling doesn't start anymore.

**Comment by ZachSaucier** [comment]
There was actually a "bug" of sorts with the auto-scroll functionality. I don't actually use it, so thanks for testing it out! It should be fixed now.

**Comment by MichaelW89** [comment]
Yeah, thanks. It's working now.

**Comment by ZachSaucier** [comment]
Comment functionality for smaller screens should now work as of JRP version 3.4.1.
