### ISSUE TITLE
Add the original url at the bottom of the page

### ISSUE THREAD

**Issue by kwanbis** [ZachSaucier/Just-Read#239]
I am using Just Read in chrome. It is a wonderful piece of software. It will be great if we can have the original URL at the bottom of the page in case we want to re-open it.

**Comment by ZachSaucier** [comment]
I [just added the original URL](https://github.com/ZachSaucier/Just-Read/issues/237) to the top of the page. You can enable this under Options -> Additional Options -> "Always add the original URL."

Why do you want it at the bottom?

**Comment by ZachSaucier** [comment]
I'm going to close this due to a lack of response and I currently think what Just Read has of providing the original URL at the top is sufficient.

**Comment by kwanbis** [comment]
Hi Zach. I haven't seen the option when I wrote, and I think is fine. I
personally prefer it at the bottom, but that is maybe just me.
