### ISSUE TITLE
Does the reverse of what it's supposed to do!

### ISSUE THREAD

**Issue by davejewell** [ZachSaucier/Just-Read#244]
Just went to this page:

https://www.dailymail.co.uk/news/article-6861199/I-human-make-mistakes-admits-fire-Speaker-John-Bercow.html

And switched on Just Read.  Instead of removing the ad's, it deleted the article I wanted to read and left nothing except an extremely long vertical list of ad's.  Now deleted from Chrome.  Let me know when it does what it's supposed to.  Definitely won't be getting the Premium version until the free version works.

**Comment by ZachSaucier** [comment]
Hello and thanks for the report.

Just Read's auto-selection isn't perfect and can't always predict the article content. The core issue is the same as issues #163 and #94. You can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to read article's content where JR fails to select the correct content like this website.

I'm going to close this issue as a duplicate and add this site to the running list of problematic sites there.

**Comment by davejewell** [comment]
Understood.  Thanks for the quick response.  I guess the heuristics do not always work.  I was maybe unlucky because it was the first URL I tried when using Just Read.  I will give it another chance in the near future.  

Thanks again for being so responsive.
Best regards,
Dave
