### ISSUE TITLE
Incorrect article date 

### ISSUE THREAD

**Issue by bolchowka** [ZachSaucier/Just-Read#245]
Just Read displays an incorrect date for the following article: https://www.producttalk.org/2019/03/continuous-discovery-across-the-organization/

It shows "April 18" while the correct date is March 13. I'm using free Just Read version on macOS Mojave 10.14.3.

**Comment by ZachSaucier** [comment]
Thanks for the post. Sorry about that! Just Read's auto-selection can't be perfect, especially with dates. If you need this to be correct you can manually change it by hovering over the date and clicking the pencil icon that appears. For more information please see [this FAQ post](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-edit-the-articles-date-author-and-title-once-in-just-read).

If you use this website regularly and they have a consistent date selector, you can use Just Read Premium's domain-specific selectors to always auto-select the correct date. For more information about that functionality, [see this FAQ post](https://github.com/ZachSaucier/Just-Read/#q-can-i-customize-which-selectors-just-read-uses-for-selecting-the-date-author-title-header-image-and-content).

As for the core issue of auto-selecting the correct date across all articles, it's a won't-fix for now at least.
