### ISSUE TITLE
In this Medium article, Just Read started from the middle of the article. 

### ISSUE THREAD

**Issue by benyben123** [ZachSaucier/Just-Read#246]
In this Medium article, JustRead started from the middle of the article. 

https://medium.com/the-spartan-group/demystifying-cosmos-atomic-swaps-ethereum-polkadot-and-the-path-to-blockchain-interoperability-d1a2d75c20d6

**Comment by ZachSaucier** [comment]
Thanks for the post! This is a known issue and has been discussed in issue #95. As discussed there, you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to work with problematic pages like this.

Please keep further discussion on that issue.
