### ISSUE TITLE
Multiple regex matches result in a blank page

### ISSUE THREAD

**Issue by rchunter** [ZachSaucier/Just-Read#247]
Just Read 1.6.0 Free
Windows 10 - 64 bit.  Chrome 73 

If I have "fu" and "bar" on my autorun domain list visiting "fubar.com" results in a blank white page. (Maybe the extension is trying to grab the content from the page twice but can't find an article in the Iframe?) 

Maybe related to this issue:
https://github.com/ZachSaucier/Just-Read/issues/86

to recreate, add "feed/html" and "lipsum.com" to the article domain list and visit 
https://www.lipsum.com/feed/html

**Comment by ZachSaucier** [comment]
Thanks for posting! This is definitely a bug and a condition I didn't think to test when implementing the auto-run functionality. I'll hopefully have time to get around to fixing it today or tomorrow.

**Comment by ZachSaucier** [comment]
This should be fixed as of JR version 1.6.1. Releasing it now. Thanks for the report!
