### ISSUE TITLE
Can Just-Read format links to a specific style?

### ISSUE THREAD

**Issue by benyben123** [ZachSaucier/Just-Read#249]
Sorry if this isn't the right place to ask (no forum), but can Just-Read format links to a specif style I chose? Let's say something like: all links should be colored red, and have no underline. Is this possible? Thanks for a great extension!

**Comment by ZachSaucier** [comment]
This is the right place to ask.

Just Read can style links! If you click the paint brush icon in the top right of the Just Read view it will open a graphical editor you can use. The `linkColor` and `linkHoverColor` values will change it for your theme - just make sure click "Save and close" if you want to keep the color changes.

For the underline you will need to change the actual stylesheet for your theme. To do that you need to right click on Just Read, open the "Options" page, and add the following somewhere in the currently active theme:

```
a { text-decoration: none; }
```

Then make sure to save that change as well. 

Let me know if you get it working or need more help!

**Comment by benyben123** [comment]
WORKED! That is SO GREAT! Thank you so much!!!

**Comment by ZachSaucier** [comment]
Happy to help!
