### ISSUE TITLE
incorrect ReadMode for HabraHabr.ru

### ISSUE THREAD

**Issue by lutc** [ZachSaucier/Just-Read#25]

**Comment by ZachSaucier** [comment]
Particular articles on HabraHabr.ru seem to work just fine, such as [this example](https://habrahabr.ru/company/wunderfund/blog/316826/). Can you please link to a more specific page that doesn't work for you?

**Comment by lutc** [comment]
https://habrahabr.ru/post/310438/
You're right. I tried only this page and closed habr with sad face. Other articles works good

**Comment by ZachSaucier** [comment]
Thanks for providing the direct link!

I've just thought of a way that I think I can avoid problems like this, but I don't have time to implement the change right now. I'll update this post when I have had time to implement the change.

Until then, you can use Just Read's user selection mode or highlight mode to select article content like that where the auto-selection doesn't work. Read more about them on [the docs page](https://github.com/ZachSaucier/Just-Read#user-selection-mode)

**Comment by ZachSaucier** [comment]
I added a class "blacklist" in 1.0.14 that Just Read now checks for when auto-selecting elements. In essence, it checks potential selection's `className` for the substring in the blacklist.

Currently it only has "comment" in the blacklist. As I come across others I will add them.

As such, it now selects a more-correct container for the page you linked (though it's still not perfect).
