### ISSUE TITLE
Just-Read has stopped working entirely

### ISSUE THREAD

**Issue by SpiderJonny** [ZachSaucier/Just-Read#255]
**Describe the bug**
Basically, Just-Read has stopped working at all.

**To Reproduce**
1. Go to any webpage in browser.
2. Click on the J-R icon in Chrome address-bar.
3. Red "on" flag appears on J-R icon.
4. Page *doesn't* get re-rendered as expected by J-R.
5. Vertical scroll bar has now disappeared from page. Only fix is to reload page.

**Expected behavior**
Page re-rendered by J-R.

**Screenshots**
N/A.

**Please complete the following information:**
 - OS: Windows 8.1
 - Browser: Chrome 
 - Version: 74.0.3729.131

**Additional context**
I have tried disabling all extensions/plug-ins other than J-R, but the problem remains.

When using my personalised stylesheet I get the following in the console:
Failed to load resource: net::ERR_FILE_NOT_FOUND    SourceSansPro-Light.ttf
Failed to load resource: net::ERR_FILE_NOT_FOUND    SourceSansPro-Semibold.ttf

I have tried loading other stylesheets -- the problem is the same, but there are no messages in the console.

**Comment by ZachSaucier** [comment]
Interesting. I'm sorry to hear that this is happening for you! I am unable to reproduce it on my end.

Do you happen to know what you were doing before error behavior started happening? Did you change any of Just Read's settings or something along those lines?

**Comment by SpiderJonny** [comment]
Thanks for such a very fast response.

I haven't changed anything in Just-Read for ages -- I got it all configured how I wanted quite some time ago. Loading different stylesheets earlier today was the first time I've changed any settings since then.

**Comment by ZachSaucier** [comment]
Alright, I'll look into the switching stylesheets functionality. I have had some edge case errors with the same functionality so I need to take a deeper look at it sometime. I probably don't have time this week to do so though.

If you just want to work around the issue for now, you can reinstall Just Read but this may require that you reset your settings. Make sure to backup any custom stylesheets that you have if you do this.

**Comment by SpiderJonny** [comment]
Well, re-installing J-R has fixed the problem.

NB.  The problem didn't occur *after* switching stylesheets.  I only tried switching stylesheets to see if my personal stylesheet was somehow causing the problem.

**Comment by ZachSaucier** [comment]
Interesting. I am very interested if you can figure out how to reproduce the error. 

Thanks for the report!
