### ISSUE TITLE
Premium ad modal uses wrong verb tense in one sentence

### ISSUE THREAD

**Issue by Tyler-H** [ZachSaucier/Just-Read#257]
The tense of one of the sentences in the Just Read Premium ad is past tense when it should be present tense (unless you no longer offer a Premium version...). 

1. Install the free version of Just Read
2. Visit an article page and click the Just Read button to activate the add-on
3. Read the modal

The message should say "Did you know there **is** a Premium version?" (emphasis mine)

![JustRead bug](https://user-images.githubusercontent.com/206492/57538719-05303c00-7317-11e9-9173-c9f8927ab218.PNG)

 - OS: Windows 7 Enterprise 64-bit
 - Browser: Firefox
 - Version: 66.0.4

**Comment by ZachSaucier** [comment]
Fixed, though I won't put out a whole new release for this change. So you'll have to wait until the next one to be appeased 😄
