### ISSUE TITLE
The free version of Just Read's icon modal indicates it is Premium

### ISSUE THREAD

**Issue by Tyler-H** [ZachSaucier/Just-Read#258]
Hovering over the Just Read icon in the top bar shows a modal that tells me the full name. The only problem is that I have installed the free version, but the modal reads "Just Read Premium". I considered whether this was a free trial, but that seemed unlikely, and I didn't see it mentioned anywhere on the website or in the FAQ/Readme.md.

1. Install the free version of the add-on
2. Hover over the icon in the top bar
3. Read the modal

The free version should just say "Just Read" or "Just Read Free"

![JustRead bug2](https://user-images.githubusercontent.com/206492/57539115-c484f280-7317-11e9-9da3-16ed065b38bd.PNG)

 - OS: Windows 7 Enterprise 64-bit
 - Browser: Firefox
 - Version: 66.0.4

**Comment by ZachSaucier** [comment]
This is due to a hastily copied manifest file. Fixed and will be in the next release
