### ISSUE TITLE
Install premium extensions on new Microsoft Edge (Chromium)

### ISSUE THREAD

**Issue by sinhthanh** [ZachSaucier/Just-Read#259]
Hi Just Read,
I love your extension very much and use it everyday to read web contents. Now I want to buy and use Just Read Premium, but I need to know once I bought, can I use it on Other browsers that base on Chromium like Vivaldi and the new Microsoft Edge.
I'm not sure about that because when I click buy, the browser request me to sign in the browser with Google account, which I cannot.

**Comment by ZachSaucier** [comment]
I'm glad you like Just Read!

I don't think the Chromium-based Edge is released yet... And I don't know about Vivaldi specifically, but Just Read Premium works fine on other Chromium-based browsers that I've tried such as Dolphin, Kiwi, and Yandex. It presumably should work fine with the new Edge whenever it comes out. 

What do you mean you "cannot" sign in with your Google account? You just have to be signed in to start the download on [JRP's webstore page](https://chrome.google.com/webstore/detail/just-read-premium/dpamdgmnffodphoamchpmbclkpmccjga).

**Comment by sinhthanh** [comment]
When said "cannot" I mean, when I use Chromium-based Edge I already signined Microsoft account, and when I use Vivaldi I signined Vivaldi account, then I when I click buy Just Read, the browser show this message:

> You just signed into the Chrome Web Store with thaxxxx@gmail.com, but you signed into Chrome with thaxxxx@live.com. To install this app, you need to sign into the Chrome Web Store with thanhns@live.com.

You see, that's the problem I cannot pay for Just Read when I'm using Chromium-based Edge or Vivaldi

**Comment by ZachSaucier** [comment]
It seems like the issue is that you're using two different emails, not that is not supported.

**Comment by sinhthanh** [comment]
You may try it to see what I’m talking about. You cannot use the same email in this case.
- You can only sign in to Chrome Web Store with Google email
- You can only sign in to Edge browser with Microsoft account/email
So, in this case, you cannot use the same email to sign in Chome Web Store and Edge browser at the same time.

**Comment by ZachSaucier** [comment]
Why can't you create a Microsoft account with a Google email? I realize that this will mean this could be a hassle if you have an existing account with Microsoft, but I don't think there is another work around.
