### ISSUE TITLE
Add "View this selection in Just Read" as a command, so we can assign shortcut for it.

### ISSUE THREAD

**Issue by jefferyyuan** [ZachSaucier/Just-Read#260]
- Sometimes, the default "View this page in Just Read" doesn't work  (maybe due to sidebar etc).
  - for example in quip,
- we have to select all the text, and choose "View this selection in Just Read" .

It would be great if we can also assign a shortcut for it.

**Comment by ZachSaucier** [comment]
This is very doable and a good request. I will implement it in the next build whenever I get back to my main computer (which may be a week from now or so). 

Thanks for the suggestion! Sorry for the delay in responding.

**Comment by ZachSaucier** [comment]
After looking into this, why doesn't the "Enable user text selection mode" shortcut work for this purpose? That shortcut, when enabled, starts user selection mode in Just Read.

**Comment by jefferyyuan** [comment]
- Thanks for your reply.
- I tried this approach. It takes me some time to understand how it works.
- But it works perfectly!!!
