### ISSUE TITLE
Got this Yahoo news page very wrong

### ISSUE THREAD

**Issue by nirodhasoftware** [ZachSaucier/Just-Read#262]
Doesn't even include any article text: https://news.yahoo.com/u-psychoanalysts-apologize-labeling-homosexuality-100000198.html

**Comment by ZachSaucier** [comment]
Sorry, I can't reproduce this error at all. Can you please provide some additional information? Like your browser, OS, steps to reproduce the error, and so forth?

**Comment by ZachSaucier** [comment]
Closing due to a lack of response.
