### ISSUE TITLE
Cannot edit font size or max width

### ISSUE THREAD

**Issue by DJayCubbz** [ZachSaucier/Just-Read#263]
I have been using this extension for about a week, and initially i could edit the text size at will (using the floating-mini editor that is on the upper right of the article) , now however, I can no longer edit this. When i click the text editor doesnt do anything, almost as if it is non-editable text, even though i have done it before.

**Comment by ZachSaucier** [comment]
Hello, sorry this is happening for you.

Can you please tell me which URL(s) this error occurs on? And what OS and browser you're using.
