### ISSUE TITLE
Please add a new option: if current web has just read enabled, then all link from current page has justread enabled.

### ISSUE THREAD

**Issue by 9527KGG** [ZachSaucier/Just-Read#266]
**Is your feature request related to a problem? Please describe.**
I don't want to use "Auto-run domain list:", because i use just read only in office, but not at home.

**Describe the solution you'd like**
Please add a new option: if current web has just read enabled, then all link from current page has justread enabled. I mean if I click link from the web which has justread enabled, then new page has justread enabled automatically.

**Describe alternatives you've considered**
NA

**Additional context**
If you like it, please do not add this feature to the paid version, since I don't have the money to pay.
Thanks/Appreciate!

**Comment by ZachSaucier** [comment]
Hello, I'm glad you like Just Read!

This is not a bad feature request. Do you want to take a shot at implementing it? You can base it off of the current code to open links in Just Read.

**Comment by 9527KGG** [comment]
Thanks for the reply. I've no idea about javascript and recently too busy. Sorry about that.

**Comment by ZachSaucier** [comment]
Keep in mind that you can already right click any link (including those in the Just Read view) and click "View the linked page using Just Read" to open up a new page in Just Read's view.

**Comment by ZachSaucier** [comment]
Given you can right click and open up pages in JR, I don't think this feature is worth my time in adding.
