### ISSUE TITLE
Feature: Non-black "Just Read" Toolbar Icons when background-color is black (so they don't vanish) 

### ISSUE THREAD

**Issue by DZGoldman** [ZachSaucier/Just-Read#267]
Currently, the toolbar icons in the upper right corner get hidden when you set the page's background to black. Could fix by having the toolbar buttons to inversely correlated to the background on the white to black grey-scale.

**Comment by ZachSaucier** [comment]
Hey DZGoldman,

You can change the color of the icons by editing your stylesheet by using the `fill` property of CSS and using the selectors [specified in this post](https://github.com/ZachSaucier/Just-Read/issues/3#issuecomment-229514745) (I'd recommend using `.simple-control { fill: #fff; }` or something like that).

Although it is possible to detect darker backgrounds programmatically and change the icons to a lighter color if so, this would very likely also affect people's custom themes which would not be good. As such, I will not be implementing anything like that. 

Does that make sense?
