### ISSUE TITLE
View local file: runtime error: manifest must request permission to access this host

### ISSUE THREAD

**Issue by hakonhagland** [ZachSaucier/Just-Read#269]
### Background
I would like to view [this page](https://github.com/swig/swig/blob/master/Doc/Devel/internals.html) using the "Just Read" extension (I am using Google Chrome). Since the HTML file is not exposed to the browser, I downloaded it to `/home/hakon/Downloads/internals.html` and opened that file in Chrome. 
### Problem
When I now click on the "Just Read" extension icon in Chrome, nothing happens. If I right-click the extension icon (instead of left-click) and select "Manage extensions" from the drop down menu, I can inspect the background page of the extension in Chrome DevTools. It shows that the script `background.js` has failed with error:
```
Unchecked runtime.lastError: Cannot access contents of url "file:///home/hakon/Downloads/internals.html". 
Extension manifest must request permission to access this host.
```
 - OS: Ubuntu 19.04
 - Browser: Chrome

**Comment by ZachSaucier** [comment]
You can fix this by modifying the manifest.json file like so:

```

```

Essentially it is adding `"file:///*"` as a permission. I am unlikely to add this to the production version of Just Read due to the fact that it would make some people worry about privacy issues 😃
