### ISSUE TITLE
Articles that don't use <p>s for content aren't auto-selected

### ISSUE THREAD

**Issue by ZachSaucier** [ZachSaucier/Just-Read#27]
Sometimes when pages don't use `<p>`s for content but use `<p>`s elsewhere on the page, Just Read selects the part with `<p>`s which is not the article content.

Example sites:

- http://bikepost.ru/blog/69642/Kratko-o-Honda-VTR1000-posle-prodazhi-i-bez-kupjur.html
- http://www.xianxiaworld.net/Dominating-Sword-Immortal/1001075.html
- http://www.sousetsuka.com/2016/08/death-march-kara-hajimaru-isekai_19.html
- http://punto-informatico.it/4369752/PI/News/adblocker-resistere-inutile.aspx
___

**Until a fix is found for this, this error can be worked around by manually selecting the text using either [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) or [highlight mode](https://github.com/ZachSaucier/Just-Read#highlight-mode).**

**Comment by hxgdzyuyi** [comment]
@ZachSaucier ,

Why don't u try to use arc90-readability's method （Replace all doubled-up <BR> tags with <P> tags）.

https://github.com/tjweir/arc90-readability/blob/master/js/readability-0.1-debug.js#L41-L43

**Comment by ZachSaucier** [comment]
@hxgdzyuyi That approach actually works surprisingly well! 3 out of 4 of the linked sites above auto-select correctly when I add that approach - [this site](http://punto-informatico.it/4369752/PI/News/adblocker-resistere-inutile.aspx) being the still-problematic one.

Just Read should include this fix as of version 1.0.19 / 34607ce

Thanks a lot for suggesting it!
