### ISSUE TITLE
Support rendering KaTeX math equation in addition to MathJax

### ISSUE THREAD

**Issue by wuchichou** [ZachSaucier/Just-Read#274]
When I use Just Read to render a webpage with math equation, it works well for MathJax, but not for KaTeX. As an example, you can see here in the link: https://www.intmath.com/cg5/katex-mathjax-comparison.php . There are two bottons on the page, "Processed by KaTeX" and "Process with MathJax", to switch between KaTeX and MathJax. I have tested that no KaTeX math equation shown up with Just Read.

Just Read has taken care of the MathJax math well, but it would be better to add a feature for rendering KaTeX math equation in Just Read.

**Comment by ZachSaucier** [comment]
Thanks for posting. I hadn't heard of KaTeX - is it that widely used? 

If it is easy to support I will likely build the functionality. I may or may not just give you a snippet of code to include in your local copy 🙂

**Comment by ZachSaucier** [comment]
Closing this due to lack of interest. I am open to a PR that supports this.
