### ISSUE TITLE
Unable to use when Javascript is disabled

### ISSUE THREAD

**Issue by JPalchak** [ZachSaucier/Just-Read#277]
When Javascript is disabled on sites where I'm blocking paywalls or article limits (wired.com for example) the extension doesn't work and just and freezes the page as it normally would display until I manually refresh the page.

System:
Windows 7 x64
Google Chrome
Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by ZachSaucier** [comment]
Just Read is completely built on JavaScript. It could do what it does with JS disabled. Therefore I'm closing this issue because it is impossible to accomplish.
