### ISSUE TITLE
Can we get an estimate of an article's reading time like Medium does?

### ISSUE THREAD

**Issue by nkmathew** [ZachSaucier/Just-Read#279]
**Is your feature request related to a problem? Please describe.**

I'd like to know roughly how long it takes to read an article so I can prioritize the shorter ones when I'm in a rush

**Describe the solution you'd like**

JustRead to calculate the number of words against normal reading speed and display the time it would take

**Describe alternatives you've considered**

Not any I can think of

**Additional context**

![Medium example](https://i.imgur.com/a955WyC.png)

**Comment by ZachSaucier** [comment]
Hey nkmathew and thanks for suggesting this feature.

Just Read Premium sort of has a form of this - the custom scrollbar changes size based on how far you've read so you get more of a correct perception of how much longer the article is. 

I'll continue thinking about whether or not this feature is worth including behind a checkbox on the options page.

**Comment by ZachSaucier** [comment]
I added this functionality in the next version of JR. It should get to you whenever it goes through the Chrome webstore's validation process.
