### ISSUE TITLE
Link Context Menu Disappeared

### ISSUE THREAD

**Issue by jack94707** [ZachSaucier/Just-Read#280]
I can't seem to find the Link Context Menu check box in the options menu any more. I'm running free version 2.08. I've enclosed a screen shot.
![link-context-menu](https://user-images.githubusercontent.com/31328906/69586255-dae25b00-0f96-11ea-827d-0d244dc69e6f.png)

Thanks.

**Comment by ZachSaucier** [comment]
Hey Jack, thanks for posting.

I did indeed remove this functionality because Chrome's webstore is getting stricter with permissions. Without supporting this feature, I just need the `activeTab` permission. With it, I need access to all `tabs` since a new tab isn't the active one. 

Did you often use this feature? I'm not particularly opposed to adding it back, granted it gets by Chrome webstore's security check, but I was curious if it was actually something that people used.

**Comment by jack94707** [comment]
Hi Zach,

Thanks for the lightning reply! Yes, I used this feature a lot while
reading newsletters that had a lot of links. Lately I've been adding
domains to the auto start, but It's not always as effective.

I've also lost the ability to see a context menu on a highlighted section
of the page. The page context menu is, thankfully, still there.

The work-arounds are easy enough, so if everyone else is happy I wouldn't
worry about adding the menus back in.

I've run into several new ways that Google has made life more difficult for
me. I guess I'm not alone.

Jack

**Comment by ZachSaucier** [comment]
> I've also lost the ability to see a context menu on a highlighted section of the page.

I can't reproduce this behavior. Can you please double check this? Can you not select highlighted content on a particular page or every page?

> The work-arounds are easy enough, so if everyone else is happy I wouldn't worry about adding the menus back in.

If other people want this feature back in I'll add it. I'll keep it commented out for now. Will reopen if that happens.

**Comment by jack94707** [comment]
I don't see Just Read in my context menu on any page. I tried an experiment: I enabled JR for incognito mode, and looked at a few pages there. My right-click menu over selected text showed no JR option.

Another thing I've noticed is that my stylesheets keep disappearing. The only way I can recover them is to re-install JR, which I've done a couple of times. Are they stored in cookies or a cache that I'm erasing?

**Comment by ZachSaucier** [comment]
> Are they stored in cookies or a cache that I'm erasing? 

They're stored in Chrome's synced storage associated with your Google account. So running JR incognito may not show your themes? I'm not sure how that works. 

I think this is just getting too complex. I'll just add back the extra permissions.

**Comment by jack94707** [comment]
;-)  I might just have too many extensions. I'll disable them all except JR and see what happens. If I discover anything, I'll report back here.
