### ISSUE TITLE
JS error when changing "Never reformat pre tags" option

### ISSUE THREAD

**Issue by Neospiro** [ZachSaucier/Just-Read#281]
Uncaught TypeError: Cannot set property 'onchange' of null
    at options.js:543

I had it but now I can't reproduce, I don't know why. 

Still, if I check this box and reload the page, it will be unchecked.

**Comment by ZachSaucier** [comment]
I can reproduce it, fixed it now. Pushing the changes to the Chrome store now.

**Comment by Neospiro** [comment]
I still can't change the option value :/

**Comment by ZachSaucier** [comment]
You've got to wait for the version to update. It might take some time for it to go through the webstore and propagate to your computer.
