### ISSUE TITLE
Make it easy to hide the date and author metas when they are unknown?

### ISSUE THREAD

**Issue by nkmathew** [ZachSaucier/Just-Read#283]
**Is your feature request related to a problem? Please describe.**

When the page author and article date can't be parsed it usually shows up as "Unkown author" and "Unknown date" which sticks out badly IMO. I'd rather just not see it in that case.

![](https://i.imgur.com/ntwJLcc.png)

**Describe the solution you'd like**

Add a class so they can be hidden with custom CSS e.g `.simple-author.unknown` or `.simple-date.unknown`

**Describe alternatives you've considered**

Would have been easier if CSS could match by content text but it doesn't seem to unfortunately

**Comment by ZachSaucier** [comment]
Good recommendation. I'll add this in the next release.

**Comment by ZachSaucier** [comment]
This functionality has been added in JR version 2.3/4.2 (premium). Pushing changes momentarily.

**Comment by ZachSaucier** [comment]
Note that I added the classes to the meta container, not the author and date elements themselves, so that you can have full control over styling.
