### ISSUE TITLE
Add text-justify and text-align buttons to "edit stylesheet" modal.

### ISSUE THREAD

**Issue by iveskins** [ZachSaucier/Just-Read#285]
**Describe the solution you'd like**
Sometimes I would like to read text in a "newspaper" style layout. 
```
p {
  text-align: justify;
  text-justify: inter-word;
} 
```
It would be nice to have some text-align buttons to quickly change between word spacing css.

**Describe alternatives you've considered**
This is easily achieved by directly editing the body css directly, but it is a bit slow to do every time. 

**Additional context**
These layouts can help with reading certain text faster because of the easier eye movements.

**Comment by ZachSaucier** [comment]
Hey iveskins, thanks for the suggestion.

Why not just create a stylesheet for this and toggle between it using the "edit stylesheet" dropdown?

**Comment by iveskins** [comment]
fair enough. I can do that. I guess it means that this plugin (beyond the basic) is most useful for people who want to write css. thanks.
