### ISSUE TITLE
Options menu? 

### ISSUE THREAD

**Issue by RustyPlex** [ZachSaucier/Just-Read#287]
Hello,
Great Chrome extension but I have a few questions. My phone is a Pixel 3a and my browser is Kiwi and I added this extension to Kiwi via their Chrome store.
1. How do I get to the options menu for Just Read? 
2. After selecting the Configure button (paintbrush) there is a link for "View more themes". Clicking on that link takes me to GitHub and lists additional themes. However, I don't see how that theme can be downloaded. I copied the code from GitHub but cannot paste it into a new stylesheet.
Any help would be appreciated, Russ

**Comment by ZachSaucier** [comment]
Hey Rusty,

1. You get to the options using Kiwi by pressing the three dots in the top right -> Extensions -> Find Just Read and click on "Details" under it -> scroll down and click "Extension options".
2. You should be able to paste in the stylesheet from the GitHub issue into the code section on the page described in 1.

Let me know if you have any other questions!
