### ISSUE TITLE
Two Subscriptions

### ISSUE THREAD

**Issue by billmcaninch** [ZachSaucier/Just-Read#290]
I think I just mistakenly subscribed to Just Read Premium for the second time today. I already have a subscription. Can you please refund today's $9.99 and subscription.

**Comment by ZachSaucier** [comment]
Hey Bill. Happy to help. Can you please forward the receipt for the one that you would like to be refunded to support@justread.link?

**Comment by billmcaninch** [comment]
Requested receipt forwarded as separate email.

**Comment by billmcaninch** [comment]
Google Payments <payments-noreply@google.com>
4:21 PM (2 hours ago)
Reply
to me
Thank you
Hello,
Thanks for buying from Zach Saucier Web Development in the Chrome Web Store
<https://www.google.com/appserve/mkt/p/AFnwnKW6qwLdIwYLWDq7pBYKorS85fg56kKgQzkXA0zqcSjAjhYDxi8602ahtwUcsLqA063Cu8VG-Zmrs_z3Etr-x0dyL08SBE2V>
By purchasing an item in the Chrome Web Store you agreed to immediate
delivery and waived your statutory right of withdrawal. See the Chrome Web
Store Terms of Service
<https://www.google.com/appserve/mkt/p/AFnwnKXol03-embaBLKzd-Dzaa_S-1V_DALnhjcSgRKghwza-kgfmzw7QaMvXRrS1cL7H-0O6wROanvFGQcyL1UxtSPGXLrBA6QZ6THtMLFjKdZpDOGJhmyZ0NPJnD1fbee6U3V6i-tY>
for
your refund rights.

You may cancel your order within 30 minutes of your purchase by visiting your
apps page
<https://www.google.com/appserve/mkt/p/AFnwnKUq1k3LMhF4wOk05hVVZRl6aejR4F1bE5-O1iipbu3Kg7sg3KeheW5u7O52tMD4a0uYmj2MufhvfbKoMwHcszBEOrfjdAfv3A75LE2mBBnjsoAEL-B0>
in
the Chrome Web Store. If you've purchased and canceled this item before,
you may not cancel this order. To learn more, see the Chrome Web Store
cancellation
policy
<https://www.google.com/appserve/mkt/p/AFnwnKUt3PYQz2eb-XxfG4XO-1e_WhEkdH46KWuGf_myc8mU6P2Pcgn_-MgHONejwNCR7nack7su7lWHSB51MnLUClgeDzAL925gNVTgY8cWsSE2vPis3r8eh8o8bL_fp4cuXpb5rOT_x0A>
.
Chrome Web Store
January 24, 2020, 2:21:11 PM PST
Item Quantity Price
Just Read Premium
A feature-packed, customizable reader extension. 1 $9.99
You will be charged *$9.99 plus any applicable tax every year* until you
cancel your subscription. Auto-renews on *January 24, 2021.*
Tax $0.00

$9.99
Payment method
Visa  • • • • 4870
Order number
CWSSUB.3980-0364-7170-68021.3

 VIEW ONLINE
<https://www.google.com/appserve/mkt/p/AFnwnKU7sedz3w_kvhd3fjT6lTVoZ8KNpx5qCTwaFHVuzVcSPQXdJIJcVCQg2NuJenZ07_ggvTGsmRlh4ClObS2lDTT6ANIIBfHyKIuTZrFF_L2l6XoxfBtERDQS_PAYCD4jdiu3Pfo_yme-VR9TIkuk4Tk0oCvBsLR4y5RhpzeirwUio1bLYJAo1q-FZ1Ipt1aaB1d4376t6ueank0ZwvODl4XwBOyZmA9xiBEuqAAaxg>
support@justread.link
Zach Saucier<br/>Zach Saucier Web Development<br/>408 Crestfield
Drive<br/>Columbus, GA 31904<br/>United States
HELP CENTER
<https://www.google.com/appserve/mkt/p/AFnwnKV1NLYlVJx5rfX1EX7GtooWMi3oYQk8IYO6gZy5uOxTtCnEAUXVY0jtKiqtDrNE3F20g6uSE1M5RsgfJRT-HZywhX2jJCnci3LtYreLC3cZVQ>
 CONTACT US
<https://www.google.com/appserve/mkt/p/AFnwnKWIzLpqkaNeEWoyqFzYXm1l95qpo7fCjRdIp5dZ6ZdsejPXAsXiVSGzNcsgk_Ui7VYMegIFj-2Jle0JQYKz7YVpl6izctKwIFOQzRqJw-yJIvzdwg>
Payments profile ID: 4521-5565-8702
Google LLC 1600 Amphitheatre Parkway, Mountain View, CA 94043
You have received this mandatory service announcement to update you about
important changes to Google or your account.
Google Pay is the faster, simpler way to pay with Google. It keeps your
payment info safe in your Google Account until you're ready to pay. Learn
more
<https://www.google.com/appserve/mkt/p/AFnwnKXDfMS7B5c4y7FVofmijX9llwHkeXBimjEZnQ3tPJMRlIM8vbLaRAYhGvX1eZLm_sHezkjZ8RbxSST6uk7zpuZwht94FBlGrIEqGeMkICLWplZJLmWF61BGpUhP_wBPhco>
ReplyForward

**Comment by billmcaninch** [comment]
Received refund notice. Thank you very much. Great service.

**Comment by ZachSaucier** [comment]
Happy to help!
