### ISSUE TITLE
JustRead shows empty screen when enabled on site https://author.today

### ISSUE THREAD

**Issue by Quark-Zimmerman** [ZachSaucier/Just-Read#293]
1. Open some book to read on site : https://author.today ("warning" the site is on russian)
Example of page: https://author.today/reader/6288/26862
2. Click JustRead button (in latestChrome)
3. Get empty screan instead of text

P.S.:
 Pressing Ctrl-J in Chrome I can easily reach the text on that page.

**Comment by ZachSaucier** [comment]
Hey Quark. Thanks a lot for posting! This is due to a side effect of a recent change that I made that I wasn't aware of. 

I'll get it corrected and have it in the next version which I'll go ahead and release today.
