### ISSUE TITLE
Print preview breaks after first page when triggered from the keyboard

### ISSUE THREAD

**Issue by ErinPo** [ZachSaucier/Just-Read#294]
**Describe the bug**
I am trying to use Just Read to print clean versions of articles from the keyboard, without reaching for my mouse. 

Unfortunately, when triggering Chrome's print preview using ⌘-P on Mac (as opposed to clicking Just Read's print icon), the print preview only shows content for the first page with all subsequent pages completely empty. Saving to PDF then in fact creates all these empty pages. This happens using the default stylesheet with all other plugins deactivated on seemingly all websites with long enough content to require multiple pages.

**Please complete the following information:**
 - OS: MacOS 10.5.3
 - Browser Chrome
 - Version 79

**Additional context**
I tried a few other reading mode plugins and they are able to produce the expected multi-page content regardless of how the print preview is invoked so it appears possible to code the functionality without requiring a click on a custom print icon.

**Comment by ZachSaucier** [comment]
Good catch. I have something in place for CTRL + P but not CMD + P. I'll add it to the next version release.
