### ISSUE TITLE
Just Read no longer working with Chrome on Mac

### ISSUE THREAD

**Issue by ljmwaugh** [ZachSaucier/Just-Read#299]
**Describe the bug**
I click on the Just Read icon in the tool bar for Chrome, "on" lights up for a second or two but the page format never changes.  This started happening in the last few days.

**To Reproduce**
see above

**Expected behavior**
that Just Read formats the page and removes all the clutter

**Screenshots**

**Please complete the following information:**
 - OS: MacOS Catalina 10.15.3
 - Browser chrome
 - Version 
![image](https://user-images.githubusercontent.com/23143202/75080484-1b8c3a80-54da-11ea-935d-d8d22f7bf392.png)

**Additional context**

**Comment by ZachSaucier** [comment]
Hey ljmwaugh and thanks for posting. This is a known issue and has been fixed but I am unable to upload the fix because of a "review" by Google that has remained unresolved for days with no update. Please see #297 for more details and a temporary work around.
