### ISSUE TITLE
Capturing incorrect elements / suggestion for a UI to remove elements

### ISSUE THREAD

**Issue by brendanchua** [ZachSaucier/Just-Read#30]
Hi Zach, thanks for the work you are doing on this. Its a great app!

There seems to be some slight problems rendering this article from the Wall Street Journal. 
[http://www.wsj.com/articles/companies-face-delays-getting-cash-out-of-china-1482148801](url)

When I hit the Just Read button, there is a blank between the Title and main picture, and then after the main picture as well. 
![image](https://cloud.githubusercontent.com/assets/2143410/21343335/2d0f9b02-c6d1-11e6-889d-d1ed453e07bd.png)

I tried selecting the text, but doesnt change the result. 

I love the select text to read function, and works quite well in some sites. It would be good to have a UI function to easily remove elements that you don't want **after** you have rendered the Just Read page. Currently, I open up the developer tools to remove html elements from the Just Read page, if the Select Text to Read function captures more than necessary.

**Comment by ZachSaucier** [comment]
Hello Brendan and thanks for the report!

I'm not seeing the behavior you have, [this is what I see](http://i.imgur.com/2mS7n5v.png). 

Are you on Windows or a Mac? Are you using the default stylesheet or one of your own?

___

As for the deletion of elements, Just Read actually has a deletion mode which [you can read about](https://github.com/ZachSaucier/Just-Read#deletion-mode) and enable an icon for in "Additional options". It should do exactly what you suggest.

**Comment by brendanchua** [comment]
Hey Zach, appreciate the speedy response. Somehow I can't seem to replicate the error when I did the screen grab. I now get the same result as what you captured. I am using PC Chrome. My apologies for that; will let you know if something similar crops up again. 

And another apology - I should have seen that the deletion option first before suggestion. Super nifty - well done!

On a side note, there might be a minor CSS bug. 
Sometimes if I click on the 'hand' portion of the deletion toggle, the hand disappears, but the trash can stays. 
![image](https://cloud.githubusercontent.com/assets/2143410/21374280/96a3ad30-c760-11e6-9bc4-f3cfb5cde6fe.png)

On the other _hand_, I click on the trash can, it disappears, leaving the hand. 
![image](https://cloud.githubusercontent.com/assets/2143410/21374414/9b8f5410-c761-11e6-89ea-5c61a27c7760.png)

Sometimes, both disappear.
![image](https://cloud.githubusercontent.com/assets/2143410/21374392/785f9644-c761-11e6-9c1e-c9f17064c29b.png)

To consistently replicate the error, I have to hover on (fade in), click, hover off, hover on, click, rather than repeatedly clicking on the toggle button. 
![image](https://cloud.githubusercontent.com/assets/2143410/21374577/a86d1edc-c762-11e6-84cb-8c73598b4b77.png)
Seems like you created two separate icons. Was there a particular reason they were not merged?

**Comment by ZachSaucier** [comment]
Thanks again. I already knew it had some CSS issues, but you're right about the deletion aspect. I uploaded a fix and it should be in the store soon. You can update to it manually once it's on the webstore or just wait a few hours for your browser to auto-update it.
