### ISSUE TITLE
Auto-scroll speed not working on MacBook Pro. Scrolls at default speed always.

### ISSUE THREAD

**Issue by kenzan-mryan** [ZachSaucier/Just-Read#300]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

**Additional context**

**Comment by ZachSaucier** [comment]
Hey @kenzan-mryan and thanks for the report!

There is indeed a bug in the functionality reading the user's custom values. I fixed that and it will be in the next version which I will release once we get the other issue you posted resolved.
