### ISSUE TITLE
I have Just Read Premium but cannot access the Just Read Dashboard.  A message appears that I need Just Read Premium.

### ISSUE THREAD

**Issue by kenzan-mryan** [ZachSaucier/Just-Read#301]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

**Additional context**

**Comment by ZachSaucier** [comment]
Hey @kenzan-mryan. Thanks for posting. 

What browser are you in? This feature only works in Chrome/Edge because of the way that user IDs are setup.

**Comment by kenzan-mryan** [comment]
Hi Zach – thanks for getting back to me.  I am using Chrome 80.0.3987.116 on a MacBook.

Very nice product BTW, I find it very useful.


Michael Ryan
Director of Engineering
Kenzan, an Amdocs company
Email: mryan@kenzan.com<mailto:mryan@kenzan.com>
Mobile: 603-401-9491

**Comment by ZachSaucier** [comment]
Are you logged into multiple Google accounts in Chrome?

The primary user (meaning the one displayed in the top right of Chrome next to the extension buttons) should be the same one that you purchased Just Read Premium with.

**Comment by kenzan-mryan** [comment]
That’s interesting because I do have two users, but the one I am logged in with is the same one I purchased Just Read with.  Not hard to imagine something from the other user is cached somehow and interfering with access to the dashboard.

But no worries – I was only trying to access to dashboard to see if I could get the auto scroll functionality reading the values I inserted.  So if the autoscroll issue is fixed I am ok with the dashboard not working due to multiple google users on same browser.

How can I get the updated version once you deploy?  Is the extension updated automatically?

Thanks for your help on this.  Again, nice product!

Michael Ryan
Director of Engineering
Kenzan, an Amdocs company
Email: mryan@kenzan.com<mailto:mryan@kenzan.com>
Mobile: 603-401-9491

**Comment by ZachSaucier** [comment]
I'm happy to jump on a screen share and try to get it resolved if you are interested in that. Just email support@justread.link if so 🙂 

> How can I get the updated version once you deploy?  Is the extension updated automatically?

Yes, as long as you have the version installed from the web store it will automatically update when I push the changes.

> Very nice product BTW, I find it very useful.

Thanks! I love seeing people use it. It's very useful to me as well 😄 

> I am ok with the dashboard not working due to multiple google users on same browser.

Closing this as no-repro for now then. I'll go ahead and push the new version to the store.
