### ISSUE TITLE
JustRead is not working suddenly on most sites.

### ISSUE THREAD

**Issue by RJUNS** [ZachSaucier/Just-Read#302]
**Describe the bug**
Extension not working on sites like psychologytoday.com and many others. upon clicking the extension, the extension icon changes to "ON" and then disappears after 2 seconds.

**Please complete the following information:**
 - OS: Windows 7
 - Browser chrome
 - Version [latest]

**Comment by ZachSaucier** [comment]
On most sites or all sites? Please see #297. Are you facing the same issue?

**Comment by fadingsignal** [comment]
I'm dealing with this too.  It hasn't worked at all for the last 2 weeks or more.  I click it and it doesn't do anything then the "On" icon turns itself off.

**Comment by ZachSaucier** [comment]
Again, is it the same issue as #297 @fadingsignal? please refer to that thread for updates and workarounds.

**Comment by fadingsignal** [comment]
@ZachSaucier Wow thanks for the fast reply, apologies for reporting a dupe.  Will look into it.  Going to check out premium, I can't live without this plugin anymore! :smile:

**Comment by ZachSaucier** [comment]
@fadingsignal No problem! I'm glad you like the extension. I use it just about daily as well 🙂
