### ISSUE TITLE
On some sites, the extension does not work due to specific response headers

### ISSUE THREAD

**Issue by wisiwig** [ZachSaucier/Just-Read#303]
**Describe the bug**
If HTTP response headers on a site are set to 
```
X-Frame-Options : SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
```
Just-Read extension can not work

**To Reproduce**
1. Go to 'https://rutracker.org/forum/viewtopic.php?t=5867294'
2. Try click on 'Just-Read' button
3. Blank page until you click on 'Just-Read' button again

**Expected behavior**
I would expect normal work

**Screenshots**

**Please complete the following information:**
 - OS: [Windows 7]
 - Browser [Waterfox Classic]
 - Version [2020.03.1]

**Additional context**
Read more here:
[HTTP headers > X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)

**Comment by ZachSaucier** [comment]
Hey wisiwig. I can't reproduce this error on Catalina in Chrome. If you try it in a different browser does the same error still occur?

**Comment by wisiwig** [comment]
> 
> 
> Hey wisiwig. I can't reproduce this error on Catalina in Chrome. If you try it in a different browser does the same error still occur?

In Google Chrome 80.0.3987.149 all works as expected. But in Waterfox Classic latest version i see this error in browser console:
![____--____2020-03-19_171435](https://user-images.githubusercontent.com/9008636/77082966-75aeeb80-6a05-11ea-958a-84e557348a64.jpg)

**Comment by ZachSaucier** [comment]
Thanks for the update. Did you load Just Read via the Firefox store or somehow using Chrome's web store? I am not familiar with how extensions work in Waterfox.

The site you link to works fine for me in all browsers on Catalina including Firefox which is built on the same engine as Waterfox.

If the error is isolated to Waterfox, especially Waterfox for Windows 7 which I can't even get access to (Microsoft only offers VMs for Windows 10 at this point), the bug is likely to not be fixed any time soon.

**Comment by wisiwig** [comment]
> 
> 
> Thanks for the update. Did you load Just Read via the Firefox store or somehow using Chrome's web store? I am not familiar with how extensions work in Waterfox.
Yes, i insalled Just Read from the Firefox store.
> 
>  
> The site you link to works fine for me in all browsers on Catalina including Firefox which is built on the same engine as Waterfox.
> 
Waterfox Classic based on 56 Firefox version. Perhaps this is  the cause of the error.

> 
> 
> If the error is isolated to Waterfox, especially Waterfox for Windows 7 which I can't even get access to (Microsoft only offers VMs for Windows 10 at this point), the bug is likely to not be fixed any time soon.
OK
