### ISSUE TITLE
Share button not working on Chrome (Mac OS Catalina)

### ISSUE THREAD

**Issue by miguelfmendonca** [ZachSaucier/Just-Read#304]
I'm a JustRead premium user but when I press the share button on the top left button of the page nothing happens.
 - Mac OS Catalina 10.15.3
 - Browser Chrome
 - Version 80.0.39.87

I don't have any other extensions currently installed besides JustRead.

**Comment by ZachSaucier** [comment]
Hey Miguel and thanks for the report.

I cannot reproduce this error in my tests. Can you please give me some additional information? 

- Does this error occur on every website or just some? 
- Does the sharing feature work on a simple page like https://text.npr.org/s.php?sId=817978107 ?
- Did the sharing feature work in the past? 
- Are you logged into multiple Google accounts in Chrome?

**Comment by miguelfmendonca** [comment]
Sorry, I had account syncing disabled. Noit it works! :)
How about other browsers? If I used it in Opera or Edge Chromium will JustRead work as well?
Thanks

**Comment by ZachSaucier** [comment]
No promises, but in Edge seems to work, but shared pages are not synced between Chrome and Edge because there's no way for me to match people's user IDs generated by the browser. 

I haven't tested Opera.

**Comment by miguelfmendonca** [comment]
Thanks again and congratulations for your awesome service and support.

**Comment by ZachSaucier** [comment]
Thanks for your support!
