### ISSUE TITLE
Shared link is not working from FB

### ISSUE THREAD

**Issue by DMblTPO** [ZachSaucier/Just-Read#306]
After prepare a page and share it through the FB I've got this error - look at the attach

![2020-04-09_23h54_25](https://user-images.githubusercontent.com/11612200/78940063-ece41680-7abd-11ea-98b8-77406792ce2e.png)

**Comment by ZachSaucier** [comment]
Can you please copy the exact URL that FaceBook is giving and paste it here? Meaning right click and click "Copy link address" on Facebook.

**Comment by DMblTPO** [comment]
yes, it's "the same" but without the query string
https://justread.link/Z6wGf4Mt8

**Comment by ZachSaucier** [comment]
Thanks. I wasn't sure if it was because they were using a short URL or something. I should get this fixed by the end of the weekend.

**Comment by ZachSaucier** [comment]
Should be fixed now!

**Comment by DMblTPO** [comment]
yes, now it works fine
