### ISSUE TITLE
Quora.com is not loading properly

### ISSUE THREAD

**Issue by galaxyx7** [ZachSaucier/Just-Read#308]
Hi.

When I try to use Just Read on Quora.com (with lastest, fully updated Google Chrome browser), it doesn't show it properly. Buttons underneath each post are enlarged instead of removed.

A screenshot of the issue: https://imgur.com/e5B7aZB

Best regards,
galaxyx7

**Comment by ZachSaucier** [comment]
This should be fixed in the next version of JR that I'm pushing to the webstore today.
