### ISSUE TITLE
Kiwi Browser Extension Config Copy/Paste Broken

### ISSUE THREAD

**Issue by markNZed** [ZachSaucier/Just-Read#309]
**Describe the bug**
In Kiwi Browser (Chrome for Mobile with extensions enabled) the extensions config of Just Read does not allow copy/paste (impossible for pasting CSS setup). I can copy paste on other extension config pages, so I guess it is a problem specific with Just Read.

**To Reproduce**
Install Just Read on Kiwi Browser
Try to copy paste into the stylesheet editor

**Expected behavior**
Copy paste should work

**Please complete the following information:**
 - OS: Android 9
 - Browser Kiwi
 - Version Latest as of today

**Additional context**
A way to load CSS sheets from a file would be a workaround.

**Comment by ZachSaucier** [comment]
I had to temporarily move away from my home due to coronavirus and my Android device is at my apartment. So it will be some time before I'm able to test a solution for this issue.

**Comment by markNZed** [comment]
Sorry to hear that. The workaround I used was to install Swiftkey keyboard that has a independent copy/paste buffer. Using that I could copy/paste the CSS.

**Comment by ZachSaucier** [comment]
I'm guessing this is because I use a modal (to be able to work in Firefox) instead of an actual page. Since you have a workaround I'm going to go ahead and close this.

**Comment by mgrobelkiewicz** [comment]
But we would like it working please

**Comment by mgrobelkiewicz** [comment]
I try to copy error logs from developer console, but can not with swiftkeyboards it copy but only world :(
