### ISSUE TITLE
Change background color outside of text's body

### ISSUE THREAD

**Issue by vovokrall** [ZachSaucier/Just-Read#31]
I wish I could get the background outside the text's body in black, so I don't have too many white on my eyes. Is it possible?

(did anyone understand my request? english isn't my first language)

**Comment by ZachSaucier** [comment]
This should be possible via the graphical editor (clicking the paint brush icon) with the "backgroundColor" value. Simply click the value and then use the color picker to choose one that you like.

You can also use CSS to do this via the Options page, such as `html { background-color: black; }`.

**Comment by vovokrall** [comment]
That's not it. Instead of having all screen white, I want to have only the body of the text in white (and the text in black). Outside of the body of the text, I want to make it black. 

I'm sending a picture of how I use iReader. I want to do the same in Just Read. 

Oh, and is it possible to change the font?

Awesome extension, btw.

![ireader](https://cloud.githubusercontent.com/assets/8398363/21441203/ed668908-c87d-11e6-8a25-ac4c6b16f559.PNG)

**Comment by ZachSaucier** [comment]
Oh, yes. Simply apply it to the `body` in the CSS instead: 

```
html { background-color: black; }
body { background-color: white; }
```

Be careful that you color the icons a way where you can still see them though! Their default black will not be visible on a screen like that.

**Comment by vovokrall** [comment]
How do I do that? I don't have any knowledge about CSS.

**Comment by ZachSaucier** [comment]
Copy the two lines in the post above, right click the Just Read button and click Options, select the theme you're using in the left panel, paste the two lines at the bottom of that file, then save it.

**Comment by vovokrall** [comment]
I'm finally using Just Read as I want it. I took this style sheet (https://gist.github.com/kimu/09cac61f9ce54468dbcf55f2b177f108) and adapted it to my use. I think that this style sheet is more "readable" to me. 

Thanks! 

There it is: 
![justreaed](https://cloud.githubusercontent.com/assets/8398363/21793042/27f4f9be-d6d5-11e6-8cf9-93853a284ed8.PNG)
