### ISSUE TITLE
Add an option for links to be opened in a new tab

### ISSUE THREAD

**Issue by nkmathew** [ZachSaucier/Just-Read#311]
**Is your feature request related to a problem? Please describe.**

If you run into an article with a lot of interesting outside links that you want to explore further you're bound to be ctrl-clicking or right clicking and opening in new tab every now and then. Links that open in a new tab can be more convenient because you only have to switch back to the article tab and if you have an extension like **[Force Background Tab](https://chrome.google.com/webstore/detail/force-background-tab/gidlfommnbibbmegmgajdbikelkdcmcl)** then it becomes almost effortless

**Describe the solution you'd like**

Make `_target`s `blank`

**Describe alternatives you've considered**
None, other than listed above

**Additional context**
None

**Comment by ZachSaucier** [comment]
So you're saying force all links to have `target="_blank"`? If so, I will not implement this because I believe it to be too intrusive. Nor do I think it would be what users expect or generally want.

You're free to edit Just Read to add this or have a userscript that does this for you on every page that you visit (in Just Read's format or not).

**Comment by nkmathew** [comment]
You have it as an opt-in feature then that way it doesn't affect anyone who doesn't want it

**Comment by ZachSaucier** [comment]
I don't think there would be many people interested in this feature. Until I'm proven otherwise, I'm going to close this issue.

**Comment by nkmathew** [comment]
Sorry for necroing but could you give some pointers on the userscript method. If I were to create a Tampermonkey script how would it be included in the Just Read iframe when it doesn't seem to have an `src` defined?

**Comment by ZachSaucier** [comment]
This will select all links on the page and in the Just Read iframe and put them in an array: `const links = [...document.querySelectorAll("a"), ...document.querySelector("#simple-article").contentWindow.document.querySelectorAll("a")]`. Then you can loop through and change whatever attributes you'd like.
