### ISSUE TITLE
Get on Brave List of Whitelisted Extensions

### ISSUE THREAD

**Issue by heyjoecampbell** [ZachSaucier/Just-Read#312]
Brave browser is growing in popularity. They take privacy ultra serious and produce a warning for any extension not included on their list of whitelisted extensions. The current list does not feature a reader app. I thought it would be to Just Read's advantage to the first and potentially the only reader app on the list.

Brave List of Whitelisted Extensions:
https://github.com/brave/brave-browser/wiki/Extension-whitelisting-process

![image](https://user-images.githubusercontent.com/8339561/81076628-dc0aa300-8eb9-11ea-8d34-0ecb7bb84767.png)

**Comment by ZachSaucier** [comment]
Thanks for the suggestion! Do you have a link to the list/submission?

**Comment by heyjoecampbell** [comment]
This is what's stated on the whitelist page:

To add an extension to this list, please follow the following process:

1. Create an issue detailing the extension to be added. Make sure to note factors & evidence supporting credibility and integrity of the developers & maintainers.
2. The security team will review the issue, and may request additional information.
3. If approved, extension whitelist will updated.

**Comment by heyjoecampbell** [comment]
https://github.com/brave/brave-browser/issues

**Comment by ZachSaucier** [comment]
Done https://github.com/brave/brave-browser/issues/9797
