### ISSUE TITLE
Offer Link to Sample Share Page

### ISSUE THREAD

**Issue by heyjoecampbell** [ZachSaucier/Just-Read#313]
Showcase the premium feature by adding a link to a sample Just Read Share Page. The link could/should live on both the Just Read homepage and Chrome Web Store page.

Also - it would be ideal if there was explanation of the payment transaction (payment options, steps, etc.)

Here's a screenshot of how it could be executed. Note: to make space for the link I removed "your" from the text "Share pages in Just Read format (example)"

![image](https://user-images.githubusercontent.com/8339561/81080087-5b01da80-8ebe-11ea-874d-38334d545207.png)

**Comment by ZachSaucier** [comment]
This is a good suggestion. Thanks!

**Comment by heyjoecampbell** [comment]
Thanks Zach 😀 Please let me know when it's live.

One more thing, does the annotation/comments offer anchor links? Using such would make it possible to link directly to a specific annotation/comments on a share page.

**Comment by ZachSaucier** [comment]
>does the annotation/comments offer anchor links? Using such would make it possible to link directly to a specific annotation/comments on a share page. 

Yes, it does. However, you currently need to right click -> Inspect element to view the ID that is generated. Then add that to the URL. For example https://justread.link/6hGN7NqpC#jr-1588690793804

**Comment by heyjoecampbell** [comment]
A link off off to the side would be a nice user experience:

**Desktop**
![image](https://user-images.githubusercontent.com/8339561/81081725-4c1c2780-8ec0-11ea-8407-04181ebe2f53.png)

**Mobile**
![image](https://user-images.githubusercontent.com/8339561/81081954-943b4a00-8ec0-11ea-84fd-31ec05df323d.png)

**Comment by ZachSaucier** [comment]
Ya, I considered that. But you can have multiple highlights in a line so they would be overlapping. I suppose that's an edge case and something is better than nothing though.

**Comment by heyjoecampbell** [comment]
Executing for comments would be easier and cleaner. Simply make the timestamp into a link.

![image](https://user-images.githubusercontent.com/8339561/81082621-86d28f80-8ec1-11ea-9177-8373f0cbc631.png)

**Comment by ZachSaucier** [comment]
@heyjoecampbell What do you think [of this](https://justread.link/ibHy21Rb1)? I haven't added links for individual highlights yet.

**Comment by heyjoecampbell** [comment]
Excellent Job 👍

**Comment by ZachSaucier** [comment]
Added a link on the JR home page.
