### ISSUE TITLE
Removing certain elements

### ISSUE THREAD

**Issue by madstrom** [ZachSaucier/Just-Read#314]
Hi, I just learned how to remove images. Is there a way to automatically remove the image captions as well? Also, is there a way to remove the "Sign up for our newsletter" part on various news sites? Thank you.

**Comment by ZachSaucier** [comment]
Hey madstrom.

It's not as simple as saying "Remove all sign up elements". Just Read does its best of removing irrelevant parts programmatically but sometimes things slip through. 

Is there a particular site that's giving you trouble? If it's one that you use regularly it might make sense to add some custom CSS to hide something on the page. If it's not, it probably makes more sense to just use Just Read's deletion mode to delete the parts that you want to delete.

**Comment by madstrom** [comment]
OK I see, thank you. How about removing the image captions, same thing?

**Comment by ZachSaucier** [comment]
Yep. Again, if you share the page I can take a look. I may be able to improve Just Read's selection of things to delete.

**Comment by madstrom** [comment]
Image captions and newsletter sign-ups are on almost all sites, but here's one for example:
https://www.wired.com/story/inside-the-early-days-of-chinas-coronavirus-coverup/

**Comment by ZachSaucier** [comment]
There are a few classes that I could use to hide some of that. Thanks for the report! It might be a bit before the next release comes out though. I have a fair bit of other work before I can do Just Read stuff.

**Comment by madstrom** [comment]
OK, thank you. Really appreciate your work, this is a fantastic app.

**Comment by ZachSaucier** [comment]
Glad you like it!

Don't close the issue, I'll close it when I implement whatever fix I end up with.
