### ISSUE TITLE
Improve Just-Read

### ISSUE THREAD

**Issue by sinhthanh** [ZachSaucier/Just-Read#315]
![image](https://user-images.githubusercontent.com/25836687/81784738-807a8e00-9527-11ea-8011-2c0b5d974ba1.png)

This one use Immersive Reader on Microsoft Edge
![image](https://user-images.githubusercontent.com/25836687/81783690-e403bc00-9525-11ea-8780-5c17265d6eb4.png)
This one is using Just Read
The one using Immversive Reader on Microsoft Edge is much cleaner compare to Just Read
I think you should take a look at how Immersive Reader works.
Here's the  link for article above: 
https://tuoitre.vn/dinh-chi-hoat-dong-bac-si-cay-nhau-348511.htm

**Comment by ZachSaucier** [comment]
Please make more tangible suggestions of improvement, not "make it like this extension".
