### ISSUE TITLE
Menu not visible

### ISSUE THREAD

**Issue by chanpreet1999** [ZachSaucier/Just-Read#318]
**Describe the bug**
I am using brave browser and added the just-read extention.
A weirdly blank menu appears when i tried to change the theme.

**To Reproduce**
1. Article I was reading : 'https://queue.acm.org/detail.cfm?id=3136559'
2. Switch on Just-read 
3. Open the 'Edit your theme menu'
4. Expected behavior  : 'Theme drop-down' 
**Screenshots**
![image](https://user-images.githubusercontent.com/34856246/85438098-3e724c80-b5a9-11ea-81a4-3f57d1137dee.png)

**System information:**
 - OS: Windows 10
 - Browser: brave
 - Version: V1.10.95 ( Chromium : 83.0.4103.106  64 bit)

**Comment by ZachSaucier** [comment]
Hey chanpreet and thanks for posting. This is a known issue where the page's default styles override some of the style customizer. Just edit the styling on other pages (like [this plain text website](https://text.npr.org/)).
