### ISSUE TITLE
PLAIN TEXT STYLE SHEET FOR COPY PASTE

### ISSUE THREAD

**Issue by Kongulu** [ZachSaucier/Just-Read#321]
Hi Zach,

Could you provide a simple style sheet that would take selected text from a website and convert it to plain text.

Some programming websites show code examples, but do not allow me to copy them. This forces me to type it in the code which takes extra time and introduces the possibility of errors.

Thanks,

Byron
brupp@msn.com

**Comment by ZachSaucier** [comment]
Hey Kongulu. What do you mean "take selected text from a website and convert it to plain text"? You can do that sort of thing by doing [CMD/CTRL + SHIFT + V](https://www.google.com/search?safe=active&sxsrf=ALeKk00IEyIq21Vq9qAEetg3-xihRQYfdg%3A1596459473596&ei=0QkoX4DfI8Gc_Qbk0ZSQBQ&q=paste+plain+text&oq=paste+plain+text&gs_lcp=CgZwc3ktYWIQAzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADICCAA6BAgAEEc6BAgjECc6BAguECc6BQgAEJECOgUIABCxAzoLCC4QsQMQxwEQowI6CAguEMcBEKMCOgQIABBDOggIABCxAxCRAjoFCC4QsQM6CAgAELEDEIMBOg4ILhCxAxCDARDHARCvAToHCAAQsQMQQzoFCC4QkQI6AgguOgQIABAKOgQILhAKUMEVWNctYIYvaANwAXgAgAGEAYgB6AqSAQQxNy4ymAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwjAi8n-iv_qAhVBTt8KHeQoBVIQ4dUDCAw&uact=5) when pasting. 

How is Just Read releated to this request?

Can you please provide a URL or two where this is an issue for you?

**Comment by Kongulu** [comment]
Hi Zach,

Thank you for getting back to me so fast.

I was trying to copy code samples from the following website – but the copy function was blocked.

https://www.crummy.com/software/BeautifulSoup/bs4/doc/#making-the-soup

I was thinking that since I can copy from Just Read, why not have a style that formats the text so I can paste it into my visual studio code window.

EXAMPLE

[cid:image001.png@01D669D7.B115CF50]

JUST READ OUTPUT
[cid:image002.png@01D669D7.EBECAD10]


DESIRED OUTPUT
head_tag = soup.head
head_tag
# <head><title>The Dormouse's story</title></head>

head_tag.contents
[<title>The Dormouse's story</title>]

title_tag = head_tag.contents[0]
title_tag
# <title>The Dormouse's story</title>
title_tag.contents
# [u'The Dormouse's story']

**Comment by ZachSaucier** [comment]
>I was trying to copy code samples from the following website – but the copy function was blocked.
> https://www.crummy.com/software/BeautifulSoup/bs4/doc/#making-the-soup
Huh, it works for me.

It looks like you tried to embed some images? It didn't work. I still am unsure what you're trying to do/want.

**Comment by Kongulu** [comment]
Hi Zach,

You are correct – my chrome installation did not allow copy, but MS Edge did.

I will need to find out how to change the setting in chrome, or maybe one of my extensions is blocking the copy.

I am not sure why the images did not come through; however, it looks like I can solve the problem by adjusting the settings in my browser.

Sorry to bother you.

Thanks for the help.

Kindly,

Byron

**Comment by ZachSaucier** [comment]
> I will need to find out how to change the setting in chrome, or maybe one of my extensions is blocking the copy. 
I'm in Chrome and it works so I'm guessing it's an extension. It's not Just Read interfering 🙂
