### ISSUE TITLE
Large icons / symbols heading historynet articles (and others)

### ISSUE THREAD

**Issue by ajmich54** [ZachSaucier/Just-Read#324]
https://www.historynet.com/americas-worst-wildfire-the-big-burn-of-1910.htm

See attached image.  These symbols appear HUGE at start of article, each hundreds of pixels in height.
<img width="239" alt="Screen Shot 2020-09-12 at 01 18 30 p" src="https://user-images.githubusercontent.com/65506957/93001221-8e531680-f4fb-11ea-87f8-22bc48527b0a.png">

**Comment by ZachSaucier** [comment]
Hello. I am not seeing those icons on the page that you linked to at all, in or out of Just Read's view. Are you sure that the link is correct? Perhaps it requires a membership?

**Comment by ZachSaucier** [comment]
Closing due to a lack of info.
