### ISSUE TITLE
"In order to see entries, you need to have Just Read Premium installed."

### ISSUE THREAD

**Issue by MikeBlueberry** [ZachSaucier/Just-Read#325]
**Describe the bug**
Comments (entries) made in reader mode of Just Reader Premium don't show up in my dashboard, with the warning "In order to see entries, you need to have Just Read Premium installed."

**To Reproduce**
1. Go to any article.
2. Activate Just Read Premium by clicking the extension icon or its shortcut key.
3. Create a comment by clicking anywhere on the right side of the article.
4. Go to your dashaboard in https://justread.link/dashboard
5. See error "In order to see entries, you need to have Just Read Premium installed."

**Expected behavior**
I believe all our comments done in articles we read in reader mode should appear in the dashboard.

**Screenshots**
[https://www.screencast.com/t/pwTdeGRMAwR](https://www.screencast.com/t/pwTdeGRMAwR)

**Please complete the following information:**
 - OS: Windows 10, desktop
 - Browser: Brave
 - Version: 1.13.82 Chromium: 85.0.4183.83 (64 bits) - portable

**Additional context**
Another error also happens. The dashboard is only accessible from the web, not directly inside the options of the extension. See screenshot: [https://www.screencast.com/t/TeekvZlD](https://www.screencast.com/t/TeekvZlD)

**Comment by ZachSaucier** [comment]
Hey Mike. This is because Brave doesn't provide a unique user ID like Chrome does (what Just Read was made for) which is what Just Read's dashboard uses to determine whether or not Just Read Premium is installed. I'll investigate an alternative for Brave.

> Another error also happens. The dashboard is only accessible from the web, not directly inside the options of the extension. See screenshot: https://www.screencast.com/t/TeekvZlD

Thanks, I'll try to fix that so it opens in a new tab in the next version of JRP.

**Comment by MikeBlueberry** [comment]
Thank you for looking into it, Zach, much appreciated.

**Comment by ZachSaucier** [comment]
Leaving this open as a reminder to myself later 😉

**Comment by MikeBlueberry** [comment]
Hi Zach, I'm wondering if you managed to get around the(se) issue(s) with Brave? (for Just Read Premium). Thanks for considering.

**Comment by ZachSaucier** [comment]
@MikeBlueberry since Chrome is deprecating their payment platform I'm working on implementing my own. That version should support Brave. Not sure when it'll be ready though.

**Comment by ZachSaucier** [comment]
All Just Read Premium features now work in the next version of Just Read to be released in the next month or so. More info to come.

**Comment by ZachSaucier** [comment]
The newest version of Just Read (v 5.0) now supports Premium features in every browser including Brave 🥳 
Please let me know if you run into any issues.
