### ISSUE TITLE
Undoing and removing changes

### ISSUE THREAD

**Issue by oskamaya** [ZachSaucier/Just-Read#326]
Hi team,

Thanks for creating this extension. It has been very helpful for me and my reading flow. 

I want to comment that I did not see any option for undoing. I think it is very helpful, especially when I, for instance, highlight texts by mistake or when I want to undo any change and to let the texts how they were initially. 

Thanks in advance for reading my comment and again, good jo guys! 

> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Comment by ZachSaucier** [comment]
You can do this using the arrow in the top right or pressing Ctrl/CMD + Z.

**Comment by albertcb98** [comment]
Hi ZachSaucier really cool extension mate, I also cant undo the edit document, like highlights, comments or deletions. How can I resolve this? Is the undo ,redo feature still available?

**Comment by ZachSaucier** [comment]
Hey @albertcb98. The undo/redo functionality should still work. With that being said, not every action that you can take in Just Read is supported by undoing/redoing. Inline edits like highlights are a lot more complicated than, say, deleting a chunk of content. For things like that it's best to use other tools (like the "clear formatting" button or the comment deletion button) to get rid of your edits.
