### ISSUE TITLE
您好，你的软件被谷歌应用商店下架了吗？

### ISSUE THREAD

**Issue by WuZhengqiang666** [ZachSaucier/Just-Read#327]
![image](https://user-images.githubusercontent.com/49598775/94595449-716d6000-02bd-11eb-9dc6-a1a5ae3a8444.png)
您好，你的软件被谷歌应用商店下架了吗？
我如何下载它呢？
谢谢您！

**Comment by ZachSaucier** [comment]
您好.

It's [still on the Chrome webstore](https://chrome.google.com/webstore/detail/just-read/dgmanlpmmkibanfdgjocnabmcaclkmod/reviews) at least in most countries. Maybe it's just being blocked in China for some reason? Or maybe you have some malware that's redirecting the URL?

Anyway, you can get it running via this GitHub repo by downloading it and installing it yourself. Quoting from [the FAQ post](https://github.com/ZachSaucier/Just-Read):

> How can I run Just Read from a local copy on my computer?
To run it from a local copy you need to download Just Read as a ZIP, unzip it, and then go to chrome://extensions/ (or about:debugging#addons for Firefox), click enable "developer mode", and click "Load Unpacked", and then select the unzipped folder. This is particularly useful if you are wanting to modify how Just Read works or debug issues.
