### ISSUE TITLE
Can't add to chrome can't cancel subscription

### ISSUE THREAD

**Issue by joeshachaf** [ZachSaucier/Just-Read#328]
When I go into google chrome store, the install button is grayed out, telling me the extension is installed, however, it isn't installed or I can't see/use it.
Also, I can't cancel my subscription.

**Comment by ZachSaucier** [comment]
Hey Joe. Are you using Chrome? Can you see Just Read Premium on the chrome://extensions page? If so, the button for it is likely just hidden. You can find it by clicking the puzzle piece next to your Google account icon in the top right of Chrome and then click "pin" to make sure it's always visible.

For info on unsubscribing see [this page](https://support.google.com/chrome_webstore/answer/1060830?hl=en).

**Comment by joeshachaf** [comment]
Thanks, I figured out the issues and managed to solve the problem.
