### ISSUE TITLE
Printing dialog modal 

### ISSUE THREAD

**Issue by forrie** [ZachSaucier/Just-Read#329]
When I print from MacOS, generally I use the system modal OPT+CMD+P to print from Chrome, so that I can select other print providers. In my case, I print to a local app that stores articles.    With Just-Read, it appears I cannot do this.   It's not clear to me why, but I would expect that the system modal would be uniformly available.

**Comment by ZachSaucier** [comment]
Hey forrie. This is the first I've ever heard of the OPT+CMD+P keyboard shortcut! I'm well aware of the CMD+P print preview and that's supported in Just Read already. I can't seem to find any information about how to call the print menu you bring up via JavaScript. Do you happen to know how to call it? If so I'll happily add it. It may not be possible with JavaScript.

**Comment by ZachSaucier** [comment]
Closing this as at this point I don't think it's possible.
