### ISSUE TITLE
Auto-run for subpages only

### ISSUE THREAD

**Issue by kipcakbegi** [ZachSaucier/Just-Read#33]
Why we cant active read-mode for just subpages? We should be able to write in auto-run domain list. For example:
**bilimfili.com/***

Or it could be in another way. So, read mode to be activated in subpages, not for homepages.

**Comment by ZachSaucier** [comment]
The auto-run domain list is checked using regex, so `bilimfili.com/[^/]` would match all URLs that have a `/` after the `.com`, so sub directories like `bilimfili.com/subdirectory/.

`bilimfili.com/.+` would match *everything* that has `bilimfili.com/` with anything after it like `bilimfili.com/index.html` and `bilimfili.com/subdirectory/`

You can enter any valid regex per line.

**Comment by kipcakbegi** [comment]
I got it, thanks! :)
