### ISSUE TITLE
It's picking up the menu instead of the article on this site

### ISSUE THREAD

**Issue by elkir** [ZachSaucier/Just-Read#333]
**Describe the bug**
Just read is picking up the suggested next articles at the bottom, instead of the main article.

The website itself looks like a very standard basic article website, nothing complicated, which I believe is why this classifies as bug

**To Reproduce**
1. Go to https://covid.joinzoe.com/post/over-the-second-wave
2. Activate Just read
4. See error:: next article headlines and thumbnails are being shown

**Expected behavior**
I'd expect the simple main fairly long text article, instead of the menu items.

**Screenshots**
![Screenshot from 2020-11-10 12-23-40](https://user-images.githubusercontent.com/20708119/98673790-c6d26d80-234f-11eb-9a59-965696df17d7.png)

**Please complete the following information:**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 86.0.4240.75 (Official Build) (64-bit)

**Comment by ZachSaucier** [comment]
Hey elkir, thanks for the report. I added that site to [the list of sites with the same issue](https://github.com/ZachSaucier/Just-Read/issues/94#issuecomment-332076592). I'm in the process of trying to update Just Read's auto-selection algorithm so this is a good test case.

In the mean time you can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the content to read on problematic pages like this.
