### ISSUE TITLE
Just a request to be notified when the new system becomes available!

### ISSUE THREAD

**Issue by Chuck-7** [ZachSaucier/Just-Read#335]
Hi Zach!
I could not figure out where to post this Question::  Hope _This_ is OK!

I am the person who had purchased the Premium Version—but could not yet download it due to the problem existing in Brave Browser. 

{By The Way, I ALSO Had Purchased Just Read–Premium a couple years ago, but I was on Chrome Back Then. (Brave is Better!!)}

Anyway, I am **_Very Eager_** to switch BACK to Premium as soon as that new “Sign-In” System is available in which (if I understand correctly) the Premium Features are available Just by Signing In (or _Something_ like that).  
_AND_, it occurred to me that I need a way to be NOTIFIED when the New System is available!!  Could you please tell me of a way that I can be NOTIFIED?  {The Only Method that I can think of TO Receive Notice of that Version’s Release is via GitHub, but I do not know how to set that up!!}

Thank You,
Chuck Colsch

**Comment by ZachSaucier** [comment]
Sure, I can notify you by posting in this thread when the new version is live. If all goes according to plan, that should be in the next week or two. 

Thanks for supporting Just Read!

**Comment by ZachSaucier** [comment]
The newest version of Just Read (v 5.0) now supports Premium features in every browser including Brave 🥳 
Please let me know if you run into any issues.
