### ISSUE TITLE
Payment Processing Error

### ISSUE THREAD

**Issue by laflier** [ZachSaucier/Just-Read#336]
**Describe the bug**
Payment Processing Error at jrp-application-payment-processing.us-east-2.elasticbeanstalk.com

**To Reproduce**
1. Created Just Read account
2. Entered verification code
3. Chose Premium version

**Screenshots**

<img width="712" alt="Screen Shot 2020-11-27 at 9 51 26 AM" src="https://user-images.githubusercontent.com/7854264/100461302-9cdeb200-3096-11eb-98c2-4ad74779b662.png">

**Please complete the following information:**
 - OS: MacOS 10.14.6
 - Browser: Chrome
 - Version: 87.0.4280.67
 - Browser: Firefox
 - Version 83.0

Looking forward to trying the new plugin but I need to get past this first. Let me know if you'd like me to help troubleshoot.

**Comment by ZachSaucier** [comment]
Sorry about that. I accidentally linked to the staging site in the redirect. It should redirect to https://justread.link/dashboard

It should be fixed now.
