### ISSUE TITLE
I can't access Options Page

### ISSUE THREAD

**Issue by abg88** [ZachSaucier/Just-Read#337]
Since last update I can't access options page. It asks me to login to Justread.link, but when I try to sign up (free) an error occurs.
Just Read worked just perfectly offline, why it's now mandatory to sign up so I can edit anything? It should be optional. I can't even edit width while I'm reading an article anymore - it changed automatically on last update and I can't fix it now.

PS: I have no use for highlighting and the balloon is distracting.

**Comment by ZachSaucier** [comment]
Hey abg88. What error occurs when you try to sign up for a free account?

> I have no use for highlighting and the balloon is distracting.

As covered in [the FAQ](https://github.com/ZachSaucier/Just-Read#faq):

> To hide premium features, adding the following to your stylesheet: `.premium-feature { display: none; }`

**Comment by laflier** [comment]
Maybe it's the same error I'm getting. I'm now getting the following error when I try to log in. I tried clearing the browsing data in Chrome and used a "virgin" browser (Safari 14), to no avail.

At: https://justread.auth.us-east-2.amazoncognito.com...

<img width="346" alt="Screen Shot 2020-11-27 at 10 46 24 AM" src="https://user-images.githubusercontent.com/7854264/100466070-4f664300-309e-11eb-98f5-d790e2192ce7.png">

**Comment by abg88** [comment]
This page opens: https://justread.auth.us-east-2.amazoncognito.com/error

Cool, I will hide those features when I'm able.

But why I'm not able to edit anything but theme and fontSize in Edit Your Theme button? Could it be a bug?

**Comment by ZachSaucier** [comment]
Investigating now. Will update you ASAP.

**Comment by ZachSaucier** [comment]
Ah, I think I found it. I missed another redirect to the staging site (this time in the authentication settings). Try now, it should work. So sorry about the trouble.

**Comment by ZachSaucier** [comment]
Are things working for you now?

**Comment by laflier** [comment]
Yes, I was able to log in and complete the transaction using the "THANKYOU" coupon code. Thank you!

**Comment by ZachSaucier** [comment]
Please let me know if you run into any other trouble. Thanks for bearing with me in this transition (I wish I never had to make it in the first place, but alas).

**Comment by abg88** [comment]
I know there's a coupon code for a one year premium account, but I wanted to make a free account.
Everytime I sign in or try to access the dashboard, it asks me to make a premium account.

**Comment by ZachSaucier** [comment]
If you're logged into a free account then you should be good to go in terms of using Just Read and it's options page. 

Maybe that's not clear on the dashboard page? I can change the wording.

**Comment by laflier** [comment]
Looks like I have the opposite problem! I DO want the premium account but I'm not yet seeing premium features after logging in and going through the payment process. Here's what I'm seeing:

<img width="252" alt="Screen Shot 2020-11-27 at 11 10 37 AM" src="https://user-images.githubusercontent.com/7854264/100467999-80944280-30a1-11eb-8b93-0416bfc06dba.png">
<img width="356" alt="Screen Shot 2020-11-27 at 11 06 26 AM" src="https://user-images.githubusercontent.com/7854264/100468007-82f69c80-30a1-11eb-8d12-1ce1fffa6383.png">

**Comment by ZachSaucier** [comment]
Hmm. Maybe the cookies didn't get set up appropriately due to the error earlier. Can you try clearing your cookies for the Just Read website, logging in again, and seeing if that fixes the issue?

**Comment by laflier** [comment]
Cleared all browsing data for 24 hours. Same result. Opened Chrome on another computer. No Premium notification but no additional features besides the ones shown above.

**Comment by abg88** [comment]
I'm really lost. 

When I try to sign up for a free account, it says there's already an account. Ok, expected behavior, then I sign in using my email. It says ![image](https://user-images.githubusercontent.com/8398363/100468825-f3a6b480-30b3-11eb-8097-bbe8ffdb6055.png), but I actually can't ![image](https://user-images.githubusercontent.com/8398363/100468857-0620ee00-30b4-11eb-8a06-7ae5c0cf9f8b.png)

**Comment by ZachSaucier** [comment]
Sounds like the same issue. Investigating...

**Comment by ZachSaucier** [comment]
Can both of you please email me at support@justread.link? That way I know which user you are.

**Comment by ZachSaucier** [comment]
Thanks @laflier. Your account is definitely Premium... So it's some issue with cacheing or something related. 

What do you mean "no additional features besides the ones shown above"?

**Comment by abg88** [comment]
Sent
> Can both of you please email me at [support@justread.link](mailto:support@justread.link)? That way I know which user you are.

**Comment by ZachSaucier** [comment]
@abg88 I can't seem to reproduce this issue. Can you please try clearing your cookies, logging into justread.link again, then trying again?

**Comment by laflier** [comment]
Here's what I'm seeing. Tried clearing cookies for 24 hours and restarting Chrome.

<img width="994" alt="Screen Shot 2020-11-27 at 11 56 20 AM" src="https://user-images.githubusercontent.com/7854264/100471125-a290c380-30a7-11eb-8f0b-60aa4eb447e1.png">

**Comment by ZachSaucier** [comment]
Interesting. I can reproduce it with the version from the webstore itself but not my local version... Investigating why that might be.

**Comment by ZachSaucier** [comment]
Still unable to figure out what could be causing the issue. I am trying to push a new version based on my local files now. It has to go through the review and approval process so it will take some time to see if that fixes the issue.

**Comment by ZachSaucier** [comment]
Please follow #338 if you'd like updates.

**Comment by abg88** [comment]
> @abg88 I can't seem to reproduce this issue. Can you please try clearing your cookies, logging into justread.link again, then trying again?

I did that, then restarted Chrome, but I still can't access options page.

Also there's no indication I'm logged in (except Log In is replaced by Dashboard) nor there's a button to log off.

**Comment by ZachSaucier** [comment]
I figured out the issue. Make sure you're using the latest version (5.0.3), go to https://justread.link/dashboard, then it should work normally. Sorry again for the trouble and thanks for bearing with me.

**Comment by abg88** [comment]
I can finally access options page. Thanks!

 > As covered in [the FAQ](https://github.com/ZachSaucier/Just-Read#faq):
> 
> > To hide premium features, adding the following to your stylesheet: `.premium-feature { display: none; }`

I added it to different lines, but it doesn't seem to work. I still see the ballon and I'm able to highlight. Where should I add it?

Also, there's only these two options in Edit Your Theme 
![image](https://user-images.githubusercontent.com/8398363/100478267-68d0b480-30c9-11eb-8e61-4039f122f60f.png)

**Comment by ZachSaucier** [comment]
@abg88 Try this: `.premium-feature { display: none !important; }`. I'll update the FAQ.

**Comment by abg88** [comment]
> @abg88 Try this: `.premium-feature { display: none !important; }`. I'll update the FAQ.

It's working now. Thanks.

**Comment by abg88** [comment]
> Also, there's only these two options in Edit Your Theme
> ![image](https://user-images.githubusercontent.com/8398363/100478267-68d0b480-30c9-11eb-8e61-4039f122f60f.png)

You gonna take a look on this?

**Comment by abg88** [comment]
BTW there's also this blank space on top now. Is it possible to fix it?
![image](https://user-images.githubusercontent.com/8398363/100490121-b49a5280-30f7-11eb-9962-10a5d32beff7.png)

**Comment by ZachSaucier** [comment]
> there's only these two options in Edit Your Theme
This is not an issue with Just Read. As stated in the FAQ, this is because you're using a custom theme. There's no guarantee that the UI can work with custom themes because the themes may be missing the selectors that are required. You might be able to get it working better if you start from the default theme and don't change the selectors used or remove the properties that are checked in the UI.

> there's also this blank space on top now. Is it possible to fix it?
What blank space are you talking about? Above the date and author? I think that's always been there. You can customize your theme to adjust the spacing as you'd like. 

Note that the new version did change a couple of selectors so you might need to adjust your custom theme some.

**Comment by abg88** [comment]
> > there's only these two options in Edit Your Theme
> 
> This is not an issue with Just Read. As stated in the FAQ, this is because you're using a custom theme. There's no guarantee that the UI can work with custom themes because the themes may be missing the selectors that are required. You might be able to get it working better if you start from the default theme and don't change the selectors used or remove the properties that are checked in the UI.
Oh, I had no idea the selectors changed; certainly this is the problem. I will try tweaking later. Thanks.

> 
> > there's also this blank space on top now. Is it possible to fix it?
> 
> What blank space are you talking about? Above the date and author? I think that's always been there. You can customize your theme to adjust the spacing as you'd like.
> 
> Note that the new version did change a couple of selectors so you might need to adjust your custom theme some.

I will see that too.
