### ISSUE TITLE
Extension doesn't recognize that I'm logged in (can't access option page)

### ISSUE THREAD

**Issue by rikiberga** [ZachSaucier/Just-Read#338]
I just made a free account to be able to modify the option page, but I still cannot access options. when I right-click on the extension and select "options" it still says: "To use the options page, sign up for free on JustRead.link"

any suggestion?

![image](https://user-images.githubusercontent.com/75134525/100468626-16959080-30d5-11eb-9564-b4d8724cecf3.png)

 - OS: windows 10
 - Browser: microsoft edge
 - Version: 87.0.664.47

**Comment by ZachSaucier** [comment]
I can't seem to reproduce this issue. Can you please try clearing your cookies, logging into justread.link again, then trying again?

**Comment by rikiberga** [comment]
cleaned all cookies, still doesn't work. I even tried with chrome, same result, am I doing something wrong?

**Comment by ZachSaucier** [comment]
Other users are having the same issue so it's probably an issue with Just Read. But I haven't been able to reproduce it yet so I'm not able to fix anything yet.

**Comment by ZachSaucier** [comment]
Interesting. I can reproduce it with the version from the webstore itself but not my local version... Investigating why that might be.

**Comment by ZachSaucier** [comment]
Still unable to figure out what could be causing the issue. I am trying to push a new version based on my local files now. It has to go through the review and approval process so it will take some time to see if that fixes the issue.

**Comment by ZachSaucier** [comment]
I think it might be an issue with the script that I am using to limit API calls. Pushing a change now, we'll see if it fixes the issue.

**Comment by ZachSaucier** [comment]
That wasn't the issue. But I'm pretty confident I found the issue. I had `"https://justread.link/"` where it should have been `"https://justread.link"` (notice the slash). Pushing the change live now.

**Comment by ZachSaucier** [comment]
That was indeed the issue. So now you just have to visit https://justread.link/dashboard and then you should be able to use the extension normally. Sorry again for the trouble.

**Comment by rikiberga** [comment]
Thanks man! Keep it up! 😉



Da: Zach Saucier<mailto:notifications@github.com>
Inviato: venerdì 27 novembre 2020 19:42
A: ZachSaucier/Just-Read<mailto:Just-Read@noreply.github.com>
Cc: rikiberga<mailto:rikirock_00@hotmail.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [ZachSaucier/Just-Read] Extension doesn't recognize that I'm logged in (can't access option page) (#338)


That was indeed the issue. So now you just have to visit https://justread.link/dashboard and then you should be able to use the extension normally. Sorry again for the trouble.
