### ISSUE TITLE
Compatibility with another addons - hyptohesis for web notes

### ISSUE THREAD

**Issue by ehocquard** [ZachSaucier/Just-Read#34]
Hi,

First thanks so much for this great addon!

I have one question:
I am using hyptohesis addon to take note or highlight content of a webpage (e.g. when reading an articles).
I was wondering if there is any simple way to make it work with Just Read, that would be an awesome combo. Clean read & notes :)
For now, if I enable just read, it looks like the notes plugin is removed (probably some div in the html)

Thanks again!
Etienne

**Comment by ZachSaucier** [comment]
See #29 for working with other extensions. 

Also see #20 for a possibility of building notes into JR.

**Comment by ehocquard** [comment]
Thanks Zach, and I do agree for paid version. Would be happy to support :)
It could be nice to have it think with Google Keep.

Have a good day!

**Comment by ZachSaucier** [comment]
Note that this and other extensions are supported using the shared version of Just Read pages in the premium version of Just Read. See [this post](https://github.com/ZachSaucier/Just-Read/#q-x-extension-doesnt-work-with-the-just-read-version-of-my-page-how-can-i-get-it-to-work) for more information.
