### ISSUE TITLE
One other Likely Fix Re Notation-Failure Related to CSS

### ISSUE THREAD

**Issue by Chuck-7** [ZachSaucier/Just-Read#342]
After our conversation, I decided to Test one of the **_Default_** Styles – –
While it was **Ugly**, it DID Actually CORRECT the problem with the Notation Feature not fitting!
So, I think I SHOULD be able to just start with one of the Default Styles & work on De-Uglifying it!
Thank you again Zach for your assistance!

– _Chuck_

**Comment by ZachSaucier** [comment]
Glad you got something figured out.

**Comment by ZachSaucier** [comment]
#341 for reference.
