### ISSUE TITLE
after update, dont work on this site.

### ISSUE THREAD

**Issue by Martino1972** [ZachSaucier/Just-Read#343]
after update, dont work on this site. 
https://www.xataka.com/perifericos/utilizo-trackball-a-diario-para-trabajar-hace-15-anos-estas-mis-razones-para-no-volver-al-raton.
![Captura](https://user-images.githubusercontent.com/61390569/100618504-aff1bc00-32fa-11eb-8bb9-976fe16bc96e.JPG)

**Comment by ZachSaucier** [comment]
Hey Martino and thanks for posting. I will investigate the issue when I get sometime. Until then you can use Just Read's [user-selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the content to read on sites like this.

**Comment by ZachSaucier** [comment]
Thanks for posting. There was a bug in my blacklist function. It's fixed in version 5.0.7 which I'm pushing to the extension marketplaces now.
