### ISSUE TITLE
Remove content on original webpage

### ISSUE THREAD

**Issue by anotherbruce** [ZachSaucier/Just-Read#349]
Just Read is awesome.  But, it seems to just paste a tidy reading page over the glunky complex source page, rather than replace it.  

The end result is that all the ad tech, page javascript and such remain running rampant in the background.  With the sites where Just Read is most essential, they continue to max my CPU, and peg my PC fan, despite the visually clean page.

Ideally, Just Read would replace the original page, and the X close button would become a link back to the original page.  Or if that is unfeasible, continue the cover-up strategy, yet block 100% of scripts on the underlying page.

**Comment by ZachSaucier** [comment]
Hey Bruce. This is a good thought. I don't think everyone would want this behavior as some people want Just Read to be more of an overlay, especially when they want to easily navigate to other pages on the same site. So I'll investigate the feasibility of enabling this functionality behind a user setting and see how it goes. Perhaps it could become the default at some point?

**Comment by ZachSaucier** [comment]
There's no way for me to restrict all other JS from running. However I can remove all of the non-Just Read elements from the page which should help performance a whole lot on pages that have a lot of bloat. The JavaScript itself shouldn't cause much of a performance issue (it'll mostly just error out). 

I went ahead and uploaded a version (5.1.0) with this behind a checkbox which you can enable on Just Read's options page. Under "Additional preferences" it's called "Remove the original page's content once the Just Read view has opened (better performance but loses original page load if JR view closed)." Please try it out and let me know if you run into any issues. Additionally if you have any suggestions as to how I should word the checkbox for it or it doesn't match your expectations please let me know.

**Comment by anotherbruce** [comment]
Wow you do fast work.  On theroot.com (an extremely ad-heavy site), Chrome task manager reports 98% CPU use when visiting that page.  After turning on Just Read with your new setting, it drops to 1.6%.  I say well done.   

Per the warning in the setting description, I have only tested it a few places, but when I close Just Read view on a site, the original automatically reloads as expected.

Per your request for wording, I'm a verbose guy, but this is what I would write:

"Remove original page content after Just Read view is opened.  This can stop CPU intensive tasks like ad display from running behind the Just Read view.  Note: may sometimes require use of browser back button to recover original page after Just Read is closed again."
