### ISSUE TITLE
Issues with some website formats

### ISSUE THREAD

**Issue by NeutralTerritroy** [ZachSaucier/Just-Read#35]
I found your extension because I really enjoy reading it on my iPhone (with the read mode) and wanted a similar extension to it. 

I am trying to use the extension with this site that hosts some web novels. 
http://www.sousetsuka.com/2016/08/death-march-kara-hajimaru-isekai_19.html

This is part of what the site looks like:
![image](https://cloud.githubusercontent.com/assets/25179047/22028059/e90b01ba-dca3-11e6-82ef-050a5944dad0.png)

This is what happens with the extension
![image](https://cloud.githubusercontent.com/assets/25179047/22028133/33b2a894-dca4-11e6-83a8-1075bcbf5631.png)
:

**Comment by ZachSaucier** [comment]
Thanks for the report! This is the same issue as #27. The work around is the same: manually selecting the text using either [user selection mode](http://www.xianxiaworld.net/Dominating-Sword-Immortal/1001075.html) or [highlight mode](https://github.com/ZachSaucier/Just-Read#highlight-mode).
