### ISSUE TITLE
CSS text-align not working

### ISSUE THREAD

**Issue by nvsitr** [ZachSaucier/Just-Read#351]
The CSS `text-align: justify;` is not working in MS Edge 87.0. Any ideas what may be happening?

**Comment by ZachSaucier** [comment]
It seems to work fine for me in Edge. I applied it to `.content-container`. Can you please provide additional information as to how to recreate the issue?

**Comment by nvsitr** [comment]
> It seems to work fine for me in Edge. I applied it to `.content-container`. Can you please provide additional information as to how to recreate the issue?

Hi Zach!

Thanks for sharing that. I was applying the function to the `body` section as I used to do in previous versions. I tried using `.content-container` and it worked!

**Comment by ZachSaucier** [comment]
Glad to hear you got it sorted.
