### ISSUE TITLE
Links are improperly raised to superscript when printed

### ISSUE THREAD

**Issue by dmgirard** [ZachSaucier/Just-Read#353]
**Describe the bug**
Links are improperly raised when an adjusted document is printed. 

**To Reproduce**
1. Go to: https://www.psychologytoday.com/us/blog/the-right-mindset/202011/new-research-finds-pessimism-signals-bipolar-relapse?amp
2. Click on 'Just Read'
3. Click on the 'Print article' button.
4. Scroll to second page.
5. Notice all links are raised. 

**Expected behavior**
Links should be rendered inline with the other text, not raised. 

**Screenshots**
![Screenshot_2021-01-29 21_07_03](https://user-images.githubusercontent.com/78242890/106344005-68de6380-6276-11eb-9f1f-3b0be431be5b.png)

**Please complete the following information:**
 - OS: Microsoft Windows 10 
 - Browser: Google Chrome 
 - Version: Version 88.0.4324.104 (Official Build) (64-bit)

**Additional context**
None

**Comment by ZachSaucier** [comment]
Hey dmgirard. Unfortunately these styles are added by the site, not Just Read, and I don't believe there is a way for me to prevent that. If you print from this site often you can probably edit your custom stylesheet to fix this. My guess is that it's a [`vertical-align`](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align) issue.

**Comment by dmgirard** [comment]
It seems that this behavior occurs when the css "display" property is set to "inline-block." If I change this property to "inline," the problem goes away.
