### ISSUE TITLE
fix this issue

### ISSUE THREAD

**Issue by kartikfire** [ZachSaucier/Just-Read#355]
https://brightside.me/wonder-places/10-staggering-facts-about-pompeii-that-reveal-a-lot-about-the-eruption-of-vesuvius-793110/
`please fix the extra lines space in this website`

**Comment by ZachSaucier** [comment]
Hey kartikfire. A fix for a site like this is a bit too specific for what I'm able to do. They have a bunch of empty square SVGs for some reason. There's no way I could programmatically get rid of that sort of thing. 

If you use Just Read on that site often you might want to add a custom rule to your stylesheet. Something like:

```
[data-test-id *= "share"] { display: none; }
```

After that rule is applied, any remaining spaces are simply from the images not being loaded before you start Just Read so it'd help if you scrolled to the bottom of the article before starting Just Read.
