### ISSUE TITLE
Not all the text appears. On the specific page there are several articles, arranged vertically on top of each other but only the bottom one shows up when entering Just Read. https://www.thegospelcoalition.org/article/7-steps-to-conflict-resolution/

### ISSUE THREAD

**Issue by skinnydork** [ZachSaucier/Just-Read#356]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

**Additional context**

**Comment by ZachSaucier** [comment]
Hey skinnydork. Just Read will work fine if you start it when the page loads. But the core issue is already known. See #163 and #331.

**Comment by skinnydork** [comment]
That did it. Sorry I didn’t find the resolved issues prior to posting.

Thanks!


Chris Juday

**Comment by ZachSaucier** [comment]
No problem! Thanks for using Just Read.
