### ISSUE TITLE
Just Read vs. EasyReader – icons become large

### ISSUE THREAD

**Issue by JeffKang** [ZachSaucier/Just-Read#359]
Sorry, also wanted to add that I sometimes see very large icons on Just Read, but they’re fine on EasyReader:

e.g. Facebook or Twitter:

https://i.imgur.com/C4vGtfR.png

https://i.imgur.com/gTqkXbo.png

https://i.imgur.com/aKwXJpg.png

https://i.imgur.com/JO35acB.png

Not sure of it’s related to this:

>Inline emoji image rendering at 100% paragraph width #26

https://github.com/ZachSaucier/Just-Read/issues/26

Windows, Chrome

**Comment by ZachSaucier** [comment]
Hey Jeff. There's really nothing to be done here. Twitter and Facebook use completely random class names so there's nothing I can reliably select to resize these icons without restricting the width of _all_ SVGs which is obviously sub-optimal.

**Comment by JeffKang** [comment]
Ok thanks anyway.
