### ISSUE TITLE
Too aggressive rendering on Google Scholar

### ISSUE THREAD

**Issue by taconsta** [ZachSaucier/Just-Read#36]
A publication entry on Google Scholar is converted to "Unknown Date, Unknown Author" "Cite" "Ok, Done!". That's 7 words.

Example:
(https://scholar.google.com/scholar?cluster=780838853224936938&hl=en&as_sdt=0,5)
Why I wanted to use Just Read on such a page? Because I wanted to have the link to ncbi.nlm.nih.gov highlighted (and for that I was planning to use the JS found here: (http://stackoverflow.com/questions/119441/highlight-a-word-with-jquery#answer-120161)
Can I simply insert this JS in the CSS for a new JustRead style?
Thanks!

Alex

**Comment by ZachSaucier** [comment]
[This is what I see](http://i.imgur.com/WaYzwgh.png) when Just Read auto-runs on that URL. It doesn't seem to match the description that you give. Are you sure that you were running it on that exact URL? Could you please try again to see if you still get the same behavior?

**Comment by taconsta** [comment]
Thanks for the quick reply!

Yes, the URL is correct. See screenshot attached.
![170118_1447_](https://cloud.githubusercontent.com/assets/25196265/22066511/83c854a2-dd8d-11e6-91c8-170b1912abc0.png)

I attach a screenshot with the options, too, just to make sure it's not from something there.
![170118_1448_](https://cloud.githubusercontent.com/assets/25196265/22066531/96e2dea4-dd8d-11e6-8a32-0ffc6694b0dd.png)


Thanks for the other tip, too.

Alex

**Comment by ZachSaucier** [comment]
What operating system and Chrome version are you currently using?

**Comment by taconsta** [comment]
Chrome 55.0.2883.87 m
Win7 Pro SP1, 32bit

**Comment by taconsta** [comment]
Highlight works fine. Same for User-Selection

**Comment by ZachSaucier** [comment]
Great! So you can make due on pages by using one of those modes. 

I'll see if I can find some Win7 PC to test on, but chances are I won't have a fix for this since I can't reproduce it.

**Comment by taconsta** [comment]
Ok, thanks for having a look at it!
