### ISSUE TITLE
Add configuration settings to change or disable keyboard shortcuts

### ISSUE THREAD

**Issue by intvnut** [ZachSaucier/Just-Read#360]
**Is your feature request related to a problem? Please describe.**
Yes, it is.  After installing Just Read, it intercepted keyboard shortcuts that I use on Quora.com for formatting text.  For example, Cmd-Shift-K formats selected text as a code block, and Cmd-Shift-L formats selected text as LaTeX.

**Describe the solution you'd like**
From my naive user perspective, the simplest solution would be to provide a switch to disable all Just Read keyboard shortcuts.  Let me opt out with something less stark than disabling the entire extension.  So far, I could not find such a setting.

Other ideas:
* Configure sites to suppress keyboard shortcuts.
* Configure sites to suppress Just Read entirely.
* Configure keyboard shortcuts to be different from the defaults.
* Configure keyboard shortcuts to have different settings on _specific websites._

Me?  I just want to tame sites like Jalopnik and The Hill, and not break Quora.

**Describe alternatives you've considered**
Disabling the extension.
Uninstalling the extension.
Using manual markup tags (which works for inline markup, but not for multi-line blocks of code).
Filing this feature request.

**Additional context**
If I hit Ctrl-Shift-L on Quora, the page just freezes, effectively.  There didn't seem to be a way to get back to where I was, and not lose the comment I was in the middle of typing.  This keyboard shortcut clash caused me to lose work.  It wasn't much, but it was frustrating.  It caused me to disable Just Read for now.  It's a blocker.

**Comment by ZachSaucier** [comment]
You can disable these using the shortcuts panel of your web browser as covered in [this FAQ post](https://github.com/ZachSaucier/Just-Read#on-a-desktop-or-laptop).
