### ISSUE TITLE
Is there a way to clear all the justread.link entries of your dashboard?

### ISSUE THREAD

**Issue by JeffKang** [ZachSaucier/Just-Read#362]
Hi,

Is there a way to clear all the justread.link entries of your dashboard?

**Comment by ZachSaucier** [comment]
Hey Jeff. Currently the only way to do this is to delete each entry individually. Perhaps this could be added in a later version.

If you'd like me to delete all of your entries, please send your email address associated with your Just Read account to support@justread.link.

**Comment by JeffKang** [comment]
Nah it should be okay; just tidying.

Thanks.
