### ISSUE TITLE
Marker "Already Read"

### ISSUE THREAD

**Issue by frame-michael** [ZachSaucier/Just-Read#363]
Hi, I love Just Read and use it very often.
Sorry if something like this was mentioned before - I searched the FAQ and GitHub but couldn't find anything related.

As I am reading many articles from blogstyle websites it happens that i am beginning to read the same article again.

Is it possible to get Just Read to display if I read or visited an article / webpage already?
I know that something like this would increase your webtraffic and webspace of your server, but it will only be a small txt, csv file or something like this, where all the visited sites where Just Read was used are stored.

A nice feature would be a button on the site with your menu that says "already read" or an icon (eye) that tells you that you read or began to read an article.
The next step would be a marker where in the text you left of, not only for the last visited website.

**Comment by ZachSaucier** [comment]
Hey Michael. I believe that this feature is a bit out of scope for Just Read. 

1. I don't think most people would care to have this feature. Adding it has the cost of making the UI more cluttered and taking up more storage on user's devices (_every single webpage_ would have to be tracked. That's a lot of data over time).
2. Browsers already do this on links  (for _recent_ history) by default. A link to a page that has already visited will usually be a different color. You can customize this color using CSS's [`:visited` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited). So to customize the link color in the Just Read view you could use the following: `a:visited { color: rebeccapurple; }` in your stylesheet. If you wanted to customize this color across _all_ websites you'd have to use a user styles extension like [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en-US).

You could also add this sort of functionality yourself by editing Just Read's source code, using user scripts (I think), or writing your own extension.
