### ISSUE TITLE
author name and publication date missing from JR version of a page

### ISSUE THREAD

**Issue by hnorr** [ZachSaucier/Just-Read#365]
**Describe the bug**
I just DL'd JustRead, and on the first page I tried it on, I spotted an important error: it omits the name of the article's author and instead inserts the name of the author of another article linked in a sidebar on the page. In addition, JR omits the publication date (March 17) and instead inserts something that does not appear at all in the regular version of the page - and is pretty meaningless: "Yesterday 4:00 pm"

**To Reproduce**
1. Go to https://www.thenation.com/article/environment/climate-media-youth-activists/ 
and note the name of the author, Mark Hertsgaard (in light gray type - could that be the problem?) and the "March 17"  date.
2. Click on JustRead
3. Look for the name "Mark Hertsgaard" or "March 17" - I don't see either (even though when I search for the authoer's name with Brave's search function, it reports four instances on the page). 

Notice also that the name "Jeremy Deaton" appears at the top of the JR version. If you go back to the regular version of the page, you will see that Jeremy Deaton is actually the author of a whole different article listed in a sidebar. JR includes that sidebar and the titles of the articles listed in it in the JR version of the page, but leaves out the authors' name.

**Expected behavior**
I expected to see "By Mark Hertsgaard" and "March 17" somewhere at the top of the page.

**Please complete the following information:**
 - OS: Windows 10
 - Browser Brave
 - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)

**Additional context**
I just tried the same page in Chrome Version 89.0.4389.114 (Official Build) (64-bit) and found the same problems.

**Comment by ZachSaucier** [comment]
Hey hnorr. Sorry it didn't work like you hoped. Web pages have _vastly_ different structures so Just Read's selection algorithm can't always be correct. Just Read provides the ability to manually edit the meta information like author and date. It also enables you to use custom selectors on a per-site basis if you want to do that.

 If you'd like to improve Just Read's selection algorithm, Just Read is open source so you're welcome to contribute!
