### ISSUE TITLE
Atlantic article cutting out key text

### ISSUE THREAD

**Issue by Jillnvc** [ZachSaucier/Just-Read#366]
Go to https://www.theatlantic.com/politics/archive/2021/04/black-boys-trauma-misunderstood-behavior/618684/.

Just Read is cutting out the first two paragraphs and the last paragraph.

**Please complete the following information:**
 - OS: Catalina
 - Browser Chrome
 - Version 90.0.4430.85

**Comment by ZachSaucier** [comment]
Hey Jillnvc and thanks for posting. This is a known issue with Just Read's auto selection.

You can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select content when the auto selection fails.
