### ISSUE TITLE
"Just Read" starts on every single page. Bug?

### ISSUE THREAD

**Issue by lookmaname** [ZachSaucier/Just-Read#367]
This didn't happen before, I ran into this error from one day to the next. I just wanted to go to a site and it did not load correctly, then it was because Just Read was trying to load on the "random" page. I realized that it does it on all pages and doesn't accept changes to his configuration, if I turn it off it turns on again when reloading.

If this is just my problem, I should reinstall the extension or as a last option also the browser, but I would not like to lose the already established parameters or bookmarks.
I have to keep it deactivated from the Mozilla configuration, and it's annoying. Before I didn't have to touch anything, because it opened automatically in the pages that I saved (and not in the rest).

I hope it can be solved, it is a useful extension.

 - OS: [Windows]
 - Browser [Mozilla]
 - Version [88.0 (64-bit)]

**Comment by ZachSaucier** [comment]
Hey lookmaname. Sorry for the issue.

Rest assured, there is no reason to reinstall your browser. At the most reinstalling Just Read _might_ be necessary. We'll see.

Can you please provide some additional information?

- Do you have anything in Just Read's autorun list? To view this go to Just Read's options and look under "Auto-run domain list:".
- Is Just Read actually starting successfully on every page, or is it failing to start?
- Are there any errors in your console (press F12 to view the console).
- Is "Remove the original page's content once the Just Read view has opened" checked in Just Read's options? If so, does turning it off help?

**Comment by lookmaname** [comment]
hey, thanks for replying! Currently it doesn't save any type of modification in its configuration (even the sites saved for auto-run were deleted). So it becomes difficult to test options because the changes that I make are useless.

"Just Read" loads the sites well, the problem, apart from the aforementioned, is that it loads any site it enters, even google.com

I handle little about the console, but on the page to modify parameters this appears in console (as you can see in the attached image).

I will be attentive to your comments.

![consola-mozilla](https://user-images.githubusercontent.com/83476989/116767818-53154180-aa11-11eb-9af9-e15025a15fe0.png)

**Comment by ZachSaucier** [comment]
> Content Security Policy: The page configuration blocked the loading of a resource in inline ("script-src").

I can't recreate that issue...

Can you try going to `about:config`, typing in `security.csp.enable`, and then setting `security.csp.enable` to `false`? Then try the options page and see if it works with no errors. 

Make sure to set `security.csp.enable` back to `true` after you test this given it's important for the security of your computer. 

Another thing you can try to get more info is open `about:debugging#/runtime/this-firefox` and then click "Inspect" next to Just Read. Then try to change an option in the Just Read options or open a new tab and see if any errors show up. If they do, please include them here (optimally in English 🙂).

**Comment by ZachSaucier** [comment]
I'll close this soon if no other information is provided.
