### ISSUE TITLE
Just read activated in Gmail fails and freezes the whole page

### ISSUE THREAD

**Issue by elkir** [ZachSaucier/Just-Read#370]
**Describe the bug**
Justread and Gmail. A very complicated relationship.  There are moments when I run JustRead on an e-mail opened on the Gmail webpage and it just works. 

However most of the time, especially after a fresh restart it does nothing, removes the scrollbar,  and freezes the whole page. This then needs to be fixed by reloading the page.

**To Reproduce**
1. Go to mail.google.com, log in and open a mail in the default individual mail view mode (no side by side or fancy stuff)
2. Activate JustRead (the full thing, not individual selection)
3. See error (page freezes)

**Expected behavior**
It pulls the text from the email, it could include the sender, or some other header details  but mainly it's the body of the email.

(It does this sometimes, but the situation when it's working is much harder to reproduce)

**Please complete the following information:**
 - OS: Ubuntu 20.04
 - Browser: Chrome  90.0.4430.93 (Official Build) (64-bit)
 - Version: Just Read 5.1.3
 - Gmail: April 2021

**Additional context**
Here is some output from the console when it the extension is activated and the page freezes:

content_script.js:2380
Resource interpreted as Document but transferred with MIME type application/binary: "https://contacts.google.com/widget/hovercard/v/2?authuser=0&hl=en-GB&origin=https%3A%2F%2Fmail.google.com&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.vQiXRrxCe40.O%2Fd%3D1%2Frs%3DAHpOoo-wBrxoiAJAWI5rmBYJxS8iVgTdFg%2Fm%3D__features__".
createSimplifiedOverlay @ content_script.js:2380
getDomainSelectors @ content_script.js:2351
continueLoading @ content_script.js:2806
afterPremium @ content_script.js:898
(anonymous) @ content_script.js:839
/mail/u/0/#inbox/FMfcgxwLtQVkXqfjTqWGClhsxqQgLvSM:1

Error handling response:
TypeError: Cannot read property 'insertBefore' of null
    at chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2665:32
    at Array.forEach (<anonymous>)
    at doStuff (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2660:20)
    at createSimplifiedOverlay (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2774:9)
    at getDomainSelectors (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2351:9)
    at continueLoading (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2806:5)
    at afterPremium (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:898:5)
    at chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:839:13

[Violation] Forced reflow while executing JavaScript took 98ms
content_script.js:2584 Resource interpreted as Document but transferred with MIME type application/binary: "https://contacts.google.com/widget/hovercard/v/2?authuser=0&hl=en-GB&origin=https%3A%2F%2Fmail.google.com&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.vQiXRrxCe40.O%2Fd%3D1%2Frs%3DAHpOoo-wBrxoiAJAWI5rmBYJxS8iVgTdFg%2Fm%3D__features__".
doStuff @ content_script.js:2584
createSimplifiedOverlay @ content_script.js:2774
getDomainSelectors @ content_script.js:2351
continueLoading @ content_script.js:2806
afterPremium @ content_script.js:898
(anonymous) @ content_script.js:839

/mail/u/0/#inbox/FMfcgxwLtQVkXqfjTqWGClhsxqQgLvSM:1 
[DOM] Found 2 elements with non-unique id #null: (More info: https://goo.gl/9p2vKq) <form id=​"null" action=​"?ui=html&zy=s" method=​"post">​…​</form>​ <form id=​"null" action=​"?ui=html&zy=d" method=​"post">​<input type=​"hidden" name=​"at" value=​"AF6bupP2CJA2c1du8fY0ZLokVeh9keiZCA">​"If you're on a slow connection, try "<input type=​"submit" value=​"basic HTML view" class=​"submit_as_link">​"."</form>​
ADGmqu_J-KLuPsYYb7JHHSCxP2Jd2EYpKGA6SIav-XMh=s48-c-mo:1 GET https://lh3.google.com/u/1/ogw/ADGmqu_J-KLuPsYYb7JHHSCxP2Jd2EYpKGA6SIav-XMh=s48-c-mo 403
Image (async)
doStuff @ content_script.js:2584
createSimplifiedOverlay @ content_script.js:2774
getDomainSelectors @ content_script.js:2351
continueLoading @ content_script.js:2806
afterPremium @ content_script.js:898
(anonymous) @ content_script.js:839

m=_b,_tp:208 
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Si @ m=_b,_tp:208
.
.
.
_.Yg.fl @ m=_b,_tp:145
Wg @ m=_b,_tp:137
Show 24 more frames

The FetchEvent for "https://ssl.gstatic.com/i18n/phonenumbers/phoneinputwidget/flags4.png" resulted in a network error response: an "opaque" response was used for a request whose type is not no-cors
Promise.then (async)
(anonymous) @ sw.js?offline_allowed=1&offline=1:181

**Comment by ZachSaucier** [comment]
Hey elkir. Just Read isn't built to try and read Gmail or any other mail clients. Web articles are beasts enough for the meager Just read 🙂 

With that being said, you could try opening emails that you want to read in the "original" mode. To do so, click the three dots, then "Show original" then use Just Read on that page. There will be extra stuff but the content should also be there and hopefully be more readable.

**Comment by elkir** [comment]
Hi, thanks for the reply.

I understand what you mean, I'm not a web developer and some of the pages might by orders of magnitude more complicated on the inside than it seems on the outside, Gmail is definitely one of them.

I love your extension and the most frustrating thing is it often _does_ work with Gmail and it's amazing when it does! Non-HTML emails are sometimes extremely long paragraphs of text with no set column width spanning whatever width you give them.

This means I find myself activating the extension again and again, and in 60% of cases, it works almost perfectly.

It's only the 40% when something makes it trip, and the whole page freezes. At that point, I reload the whole thing and use the JustRead's "Select content to read" function.

Failing sometimes is ok, I don't expect that. What is really the hurdle is the time-consuming freeze & reload cycle. That is really the bug in my opinion. If the extension _just noticed the problem, threw an error and maybe a popup notifying the user, leaving the page intact_, I could immediately switch to manual selection mode.

Do you think that is fixable?

**Comment by ZachSaucier** [comment]
>If the extension just noticed the problem, threw an error and maybe a popup notifying the user, leaving the page intact, I could immediately switch to manual selection mode. Do you think that is fixable?

At this point I don't know if that's fixable 🙂 Could you send an email that has the issue to support@justread.link? Then I can test it on my device.

**Comment by elkir** [comment]
At this moment it's every mail that I try. I'll try to find out when it's not an issue.

Out of the console log up there this line is unique to the fail:

> 

```
Error handling response: TypeError: Cannot read property 'insertBefore' of null
    at chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2665:32
    at Array.forEach (<anonymous>)
    at doStuff (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2660:20)
    at createSimplifiedOverlay (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2774:9)
    at getDomainSelectors (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2351:9)
    at continueLoading (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:2806:5)
    at afterPremium (chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:898:5)
    at chrome-extension://dgmanlpmmkibanfdgjocnabmcaclkmod/content_script.js:839:13```

**Comment by ZachSaucier** [comment]
I was able to fix this error and am pushing the changes to the webstore now.
