### ISSUE TITLE
"Edit your theme" menu not working 

### ISSUE THREAD

**Issue by SpiderJonny** [ZachSaucier/Just-Read#371]
When I click on the paintbrush to edit my theme, I only get a couple of editable entries in the menu, and no "save" option, as per screenshot:

![justread editmytheme](https://user-images.githubusercontent.com/31634570/118391947-c54f6e00-b62e-11eb-80b6-a396b620c9fd.jpg)

I have included my custom CSS below.

System config:

- Just Read 5.1.4
- Chrome (currently ver. 90.0.4430.212)
- Windows 8.1

It happens when JR is the only extension that's active, so it's not due to a clash with another extension.

I have tried it on a variety of sites, so I don't think it's a case of the  page's default styles overriding things.

My CSS
> `@import url("https://fonts.googleapis.com/css?family=Merriweather|Source+Sans+Pro:400,700");
> body { font-family: "Source Sans Pro", sans-serif; background-color: rgb(35, 44, 55); line-height: 1.33; font-size: 16px; color: rgb(2, 2, 2); text-rendering: optimizelegibility; }
h1, h2 { font-family: "Source Sans Pro", sans-serif; font-weight: 700; }
h1 { font-size: 1.875em; line-height: 1.125; }
h2 { font-size: 1.45em; line-height: 1.2625em; }
h3 { font-family: "Source Sans Pro", sans-serif; font-size: 1.25em; line-height: 1.5; }
hr { height: 1px; background-color: rgb(226, 226, 226); border: none; width: 100%; margin: 0px; }
a[href] { color: rgb(0, 102, 153); }
a[href]:hover { color: rgb(39, 170, 225); }
.youtubeContainer { position: relative; width: 100%; height: 0px; padding-bottom: 56.25%; padding-top: 25px; }
iframe[src*="youtube.com/embed/"] { width: 100%; height: 100%; position: absolute; top: 0px; left: 0px; }
img { max-width: 100%; }
li { line-height: 1.5em; }
td { border: 1px solid black; padding: 3px 7px; }
pre { background-color: rgb(224, 224, 224); padding: 10px; overflow: auto; }
blockquote { border-left: 4px solid; padding: 15px 10% 15px 8%; margin: 1em 0px; font-size: 16px; line-height: 1.33; }
blockquote > :first-child { margin-top: 0px; }
blockquote > :last-child { margin-bottom: 0px; }
figure { margin: 0px 0px 10px; }
figcaption { font-size: 0.9em; opacity: 0.7; border: 1px solid rgb(238, 238, 238); padding: 17px 17px 12px; }
aside, [class*="sidebar"], [id*="sidebar"] { max-width: 90%; margin: 0px auto; border: 1px solid lightgrey; padding: 5px 15px; }
.simple-date { display: inline-block; font-family: "Source Sans Pro", sans-serif; font-size: 18px; padding-right: 15px; padding-top: 10px; padding-bottom: 10px; border-right: 1px solid rgb(216, 216, 216); }
.rtl .simple-date { border-left: 1px solid rgb(216, 216, 216); border-right: none; padding-right: 0px; padding-left: 15px; }
.simple-author { display: inline-block; font-family: "Source Sans Pro", sans-serif; font-size: 18px; color: rgb(39, 170, 225); line-height: 22px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; }
.rtl .simple-author { padding-left: 0px; padding-right: 10px; }
.simple-container { max-width: 500px; }
[class*="emoji"], [class*="icon"] { width: 1em; }
.simple-container { padding: 30px; background-color: rgb(254, 255, 237); border-radius: 10px; }
>

Thanks.

**Comment by ZachSaucier** [comment]
Hey Jonny. Sorry for the trouble.

I'm not able to recreate this issue, even if I use your theme. Can you please provide additional details about the issue?

1. What errors are in the console when this occurs? You can press F12 to view the console.
2. Does this happen on every site or only particular ones?
3. Does the issue still happen if you use Just Read's [default theme](https://github.com/ZachSaucier/Just-Read/blob/master/default-styles.css)?

**Comment by SpiderJonny** [comment]
> What errors are in the console when this occurs? You can press F12 to view the console.

Console log attached.
[jr.console.log](https://github.com/ZachSaucier/Just-Read/files/6489344/jr.console.log)

> Does this happen on every site or only particular ones?

Every site I've tried.

> Does the issue still happen if you use Just Read's default theme?
 
 No, it doesn't.  I wonder how I'm breaking JR? :-(

**Comment by ZachSaucier** [comment]
It looks like the line of code that's the source of the error is [this one](https://github.com/ZachSaucier/Just-Read/blob/master/content_script.js#L1300). 

> I wonder how I'm breaking JR?

It looks like you edited your theme before the last major style update - some classes were switched out.

Try replacing your theme with this slightly modified one:

```
@import url("https://fonts.googleapis.com/css?family=Merriweather|Source+Sans+Pro:400,700");
body { font-family: "Source Sans Pro", sans-serif; background-color: rgb(35, 44, 55); line-height: 1.33; font-size: 16px; color: rgb(2, 2, 2); text-rendering: optimizelegibility; }
h1, h2 { font-family: "Source Sans Pro", sans-serif; font-weight: 700; }
h1 { font-size: 1.875em; line-height: 1.125; }
h2 { font-size: 1.45em; line-height: 1.2625em; }
h3 { font-family: "Source Sans Pro", sans-serif; font-size: 1.25em; line-height: 1.5; }
hr { height: 1px; background-color: rgb(226, 226, 226); border: none; width: 100%; margin: 0px; }
a[href] { color: rgb(0, 102, 153); }
a[href]:hover { color: rgb(39, 170, 225); }
.youtubeContainer { position: relative; width: 100%; height: 0px; padding-bottom: 56.25%; padding-top: 25px; }
iframe[src*="youtube.com/embed/"] { width: 100%; height: 100%; position: absolute; top: 0px; left: 0px; }
img { max-width: 100%; }
li { line-height: 1.5em; }
td { border: 1px solid black; padding: 3px 7px; }
pre { background-color: rgb(224, 224, 224); padding: 10px; overflow: auto; }
blockquote { border-left: 4px solid; padding: 15px 10% 15px 8%; margin: 1em 0px; font-size: 16px; line-height: 1.33; }
blockquote > :first-child { margin-top: 0px; }
blockquote > :last-child { margin-bottom: 0px; }
figure { margin: 0px 0px 10px; }
figcaption { font-size: 0.9em; opacity: 0.7; border: 1px solid rgb(238, 238, 238); padding: 17px 17px 12px; }
aside, [class*="sidebar"], [id*="sidebar"] { max-width: 90%; margin: 0px auto; border: 1px solid lightgrey; padding: 5px 15px; }
.simple-date { display: inline-block; font-family: "Source Sans Pro", sans-serif; font-size: 18px; padding-right: 15px; padding-top: 10px; padding-bottom: 10px; border-right: 1px solid rgb(216, 216, 216); }
.rtl .simple-date { border-left: 1px solid rgb(216, 216, 216); border-right: none; padding-right: 0px; padding-left: 15px; }
.simple-author { display: inline-block; font-family: "Source Sans Pro", sans-serif; font-size: 18px; color: rgb(39, 170, 225); line-height: 22px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; }
.rtl .simple-author { padding-left: 0px; padding-right: 10px; }
.simple-article-container { max-width: 500px; }
[class*="emoji"], [class*="icon"] { width: 1em; }
.simple-article-container { padding: 30px; background-color: rgb(254, 255, 237); border-radius: 10px; }
```

Like I said, I haven't been able to reproduce the issue yet so I'm not sure if it will help.

**Comment by SpiderJonny** [comment]
> Try replacing your theme with this slightly modified one:

That's fixed it :-)

Many thanks for your really excellent support.

**Comment by ZachSaucier** [comment]
> That's fixed it :-)

Glad to hear it! Thanks for using Just Read.
