### ISSUE TITLE
Adjust editor shortcut

### ISSUE THREAD

**Issue by blue119** [ZachSaucier/Just-Read#376]
Current, the editor shortcut is fixed and nonchargeable. Is it able to let user change its prefer shortcut setting for text editor in JR's Option page?

Thanks,

**Comment by ZachSaucier** [comment]
Hey blue119 and thanks for posting. 

What shortcut are you referencing? Maybe it'd help if you described what you're trying to do.

**Comment by blue119** [comment]
just like the text highlight in the JR's mode and it is pretty good if these 8 button all can adjust its hotkey with user's preference. 

![jr-hotkey](https://user-images.githubusercontent.com/151087/129444589-9ad527d5-e275-428e-94db-e573fe89fa31.png)

**Comment by ZachSaucier** [comment]
Thanks for clarifying. Unfortunately browsers limit the amount of "official" shortcut (that can be edited on pages like `chrome://extensions/shortcuts`) to just 4 shortcuts. So Just Read can't use that customization for all of the shortcuts that it offers.

With that being said, in theory a section could be added to Just Read's options page to add this sort of functionality but doing so is not the most straightforward thing.

Can you please provide a couple of examples of how you're hoping to customize the shortcuts? Part of the difficulty is not conflicting with other shortcuts.

**Comment by ZachSaucier** [comment]
Closing this due to lack of feedback.
