### ISSUE TITLE
Short cut key

### ISSUE THREAD

**Issue by koraa** [ZachSaucier/Just-Read#38]
It would be nice to assign a keyboard shortcut!

**Comment by ZachSaucier** [comment]
A keyboard shortcut for what? Starting the extension? There is already a keyboard shortcut for that as well as several other functions. Take a look at the [ReadMe](https://github.com/ZachSaucier/Just-Read#use-just-reads-built-in-selection)

**Comment by koraa** [comment]
Nevermind. I should RTFM :)
Thanks for the response!
