### ISSUE TITLE
Just Read is missing from Firefox Add-ons

### ISSUE THREAD

**Issue by tomnapp2** [ZachSaucier/Just-Read#383]
**Describe the bug**
When attempting to download this extension from the Firefox Add-on store, I cannot find it anywhere. When attempting to follow the Firefox Add-on link provided by the developer in this GitHub repository, an "_Oops! We can’t find that page_" page appears.

**To Reproduce**
1. Go to [Firefox Add-on store](https://addons.mozilla.org/en-US/firefox/extensions/)
2. Search 'Just Read'
3. It will not show up in search results
OR
1. Go click the [Firefox Add-on link](https://addons.mozilla.org/en-US/firefox/addon/just-read-ext/) provided by the developer & see the "_Oops! We can’t find that page_" page

**Expected behavior**
Just Read does not appear in Firefox Add-on store search results and its original Firefox Add-on store page has been removed.

**Screenshots**
![211121-20 35 36 288_firefox-Add-ons_for_Firefox_(en-US)_—_Mozilla_Firefoxq29t](https://user-images.githubusercontent.com/38059841/142788585-5d6305c2-b071-456e-90d8-0501b6a6b968.jpg)

**Please complete the following information:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 94.0.1 (64-bit)

**Comment by ZachSaucier** [comment]
Just Read is now (finally) back in the Firefox store!
