### ISSUE TITLE
Access highlighted text from dashboard

### ISSUE THREAD

**Issue by onlychans1** [ZachSaucier/Just-Read#385]
**Is your feature request related to a problem? Please describe.**
When I'm reading an article, I would like to review the text I highlight without having to revisit the article. 

**Describe the solution you'd like**
Store the highlighted text in a database so you can access your past highlights from your dashboard. 

**Describe alternatives you've considered**
Programatically transfer just the highlighted text of an article into a text file programatically, without having to manually copy and paste. 

**Additional context**
This highlight feature is inspired by the Blinkist highlighting feature, and the Just Read dashboard can integrate a similar feature. 

![image](https://user-images.githubusercontent.com/60107091/153237453-1dd20b2f-3c10-4eec-ace5-e28b3f237839.png)

![image](https://user-images.githubusercontent.com/60107091/153238596-6d9d6039-269d-430e-abd7-7473fe58d707.png)

**Comment by ZachSaucier** [comment]
Hey Eden. Thanks for the suggestion!

Are there other apps that you use to manage highlights? Building this functionality myself is not the most straightforward thing, but if I could use an API for an existing service that allows users to save highlights to that service that seems a lot more doable.

**Comment by ZachSaucier** [comment]
Closing due to a lack of feedback and the scope being pretty large to implement this request.
