### ISSUE TITLE
Be able to opt-in to have a list of your highlighted text emailed to you

### ISSUE THREAD

**Issue by onlychans1** [ZachSaucier/Just-Read#386]
**Is your feature request related to a problem? Please describe.**
I would appreciate being able to opt in to have a list of the highlighted text from the past week/month emailed to me on a weekly/monthly basis to better digest the ideas from articles from the text I've highlighted. 

**Describe the solution you'd like**
Have an option in the dashboard to opt in to these email digest notification, and change your preferences of which highlights you want to be emailed to you, which email you want them to be sent to, and how frequently you want these email digests. 

**Describe alternatives you've considered**
Integrate support for some spaced repetition software like Anki to review highlighted text. 

**Additional context**
https://apps.ankiweb.net/

The preference menu can resemble something like this:
![image](https://user-images.githubusercontent.com/60107091/153289367-fb9dbd30-9ab9-45ef-92e4-b6b5dc085269.png)

**Comment by ZachSaucier** [comment]
Hey onlychans1. Thanks for posting! And so sorry for not responding sooner. I usually respond much faster so sorry for failing you here.

Given that Just Read Premium has a pretty small amount of users and this functionality would require not only a fairly significant amount of investment of development time but would also require additional recurring costs for me as the developer, Just Read will not be adding this functionality at this time. If Just Read Premium starts getting a lot more users and this is a commonly requested feature, I will reevaluate at that time.
