### ISSUE TITLE
Auto-run is not working

### ISSUE THREAD

**Issue by Orlinky** [ZachSaucier/Just-Read#388]
Hello,

**Describe the bug**
The auto-run feature is not working anymore.

**Expected behavior**
When using regex in the auto-run domain list and then going to one of the websites Just Read doesn't automatically enter its reader mode.

**Versions**
 - OS: macOS 12.2.1
 - Browser: Chrome 99.0.4844.51
 - Just Read: 5.1.10

**Additional context**
It was working just yesterday I don't know what changed. 
I tried it on multiple websites to be sure. 
My settings haven't changed recently either.

**Comment by ZachSaucier** [comment]
Hey Orlinky.

The auto-run functionality seems to be working fine for me. 

For example, if I have this in my auto-run section on the options page:

```
text.npr.org
```

Then go to https://text.npr.org/ it opens Just read automatically.

Are there any relevant errors in your developer tools console (F12 when on a page that should auto-run)? 

Maybe there's a conflict with another extension that you have installed?

**Comment by Orlinky** [comment]
Yes you were right it was indeed another extension causing the problem, sorry for wasting your time.

The culprit was [BetterTTV](https://betterttv.com/), the weird thing is once I disabled it and then re-enabled it the auto-run issue didn't reappear which is highly intriguing.

Anyway thanks for your time :)

**Comment by ZachSaucier** [comment]
I'm glad you got it sorted out!
