### ISSUE TITLE
Changing background & text colours

### ISSUE THREAD

**Issue by domingohui** [ZachSaucier/Just-Read#39]
Hey thanks a lot for making this extension! I find myself frequently switching back and forth between dark and white background. Does it make sense and is it applicable to many people to have a button/shortcut to swap the colours of the background and the text?

**Comment by ZachSaucier** [comment]
You can switch between themes by opening Options and selecting another theme... I am hesitant to add a whole button and functionality for this. 

I'd recommend a userscript that you can use personally. You could attach it to a keyboard command or modify the DOM to add a button. A user script could also work outside of Just Read if you wanted it to

**Comment by domingohui** [comment]
okay that sounds good! Thanks!

**Comment by ZachSaucier** [comment]
This is now possible using the drop down in the GUI as of a few JR versions ago.
