### ISSUE TITLE
Need option that goes to the original page when pressing "Back" (e.g. when you press a side mouse button for back\fwd)

### ISSUE THREAD

**Issue by vonDubenshire** [ZachSaucier/Just-Read#393]
**Is your feature request related to a problem? Please describe.**
Need option that goes to the original page when pressing "Back" (e.g. when you press a side mouse button for back\fwd)

**Describe the solution you'd like**
An option to not have it appear as an overlay, so when I press "back" on my side mouse button it doesn't reverse to the LAST website, but the full website I am currently on and using JustRead with.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ZachSaucier** [comment]
Hey vonDubenshire and thanks for posting. This feature makes sense! I will probably add it in the next version of Just Read. Though it's a _little_ tricky given that the site could be on Just Read's auto-run list and then start Just Read... So I will have to have a work around for that edge case.

**Comment by vonDubenshire** [comment]
cool, yeah I don't use auto-run so I would think even if it isn't
work-aroundable you can have one or the other toggled. sweet. thx.

**Comment by ZachSaucier** [comment]
I added this functionality in version 5.2.0!

**Comment by stegorg** [comment]
> **Is your feature request related to a problem? Please describe.** Need option that goes to the original page when pressing "Back" (e.g. when you press a side mouse button for back\fwd)
> 
> **Describe the solution you'd like** An option to not have it appear as an overlay, so when I press "back" on my side mouse button it doesn't reverse to the LAST website, but the full website I am currently on and using JustRead with.
> 
> **Describe alternatives you've considered** n/a
> 
> **Additional context** n/a

Hi, this would be a very good feature with a hardcoded image with a qr code on it.

**Comment by ZachSaucier** [comment]
Hey stegorg. Just Read has to be installed on someone's computer for that to work... But you could make QR codes for any webpage that has `jr=on` in the query string and it would work. For example `https://text.npr.org/1100459262?jr=on`.

**Comment by ZachSaucier** [comment]
Changes related to this request were causing issues that I couldn't reproduce for some users so I went ahead and reverted for now.

**Comment by ZachSaucier** [comment]
This was added back in version 5.2.3. Let me know if there are issues!
