### ISSUE TITLE
Toggle Full screen option.

### ISSUE THREAD

**Issue by Naroleptic** [ZachSaucier/Just-Read#395]
I LOVE the extension and use it for virtually all long-reads in browser.

However i miss the option to automatically switch to full screen when opening Just-Read and back when closing.

The very discreet icons in Just-Read does not distract in my white-on dark grey view, while other elements of browser and windows task-bar does. 

So eliminating the need to F11 after every toggle to/from Just-Read would be really nice!

(I would also like to be able to hide the scroll bar to the right, even in full screen mode, if possible. This could be a separate toggle of course.)

Cheers,

Andreas

**Comment by ZachSaucier** [comment]
Hey Andreas, thanks for posting. 

Just Read [used to have this functionality](https://github.com/ZachSaucier/Just-Read/issues/130) but it stopped working in Chrome. I believe that the browser doesn't let iframes do this programmatically any longer so I don't think I will be able add the functionality back. Sorry about that.

**Comment by Naroleptic** [comment]
Gotcha. Gotta play in Googles way on Googles court etc. Sorry to hear it. Cheers!
