### ISSUE TITLE
Lang tag is removed. Breaks hyphenation and is bad for accessibility

### ISSUE THREAD

**Issue by MaxLinWorm** [ZachSaucier/Just-Read#396]
**Describe the bug**
Extension creates a new `html` element that's a descendent of the `iframe` element. This new html element doesn't carry the `lang` tag of the original page.

This means I can't add hyphenation to my themes.

Also bad for accessibility reasons

Cross-posted on the Chrome Store

**To Reproduce**
1. Create/edit CSS theme
2. Add the following rule:

```
.simple-article-container {
  /* Hifens */
  -webkit-hyphens: auto;
  -webkit-hyphenate-limit-before: 3;
  -webkit-hyphenate-limit-after: 3;
  -webkit-hyphenate-limit-chars: 6 3 3;
  -webkit-hyphenate-limit-lines: 2;
  -webkit-hyphenate-limit-last: always;
  -webkit-hyphenate-limit-zone: 8%;
  
  -moz-hyphens: auto;
  -moz-hyphenate-limit-chars: 6 3 3;
  -moz-hyphenate-limit-lines: 2;
  -moz-hyphenate-limit-last: always;
  -moz-hyphenate-limit-zone: 8%;
  
  -ms-hyphens: auto;
  -ms-hyphenate-limit-chars: 6 3 3;
  -ms-hyphenate-limit-lines: 2;
  -ms-hyphenate-limit-last: always;
  -ms-hyphenate-limit-zone: 8%;
  
  overflow-wrap: break-word;
  hyphens: auto;
  hyphenate-limit-chars: 6 3 3;
  hyphenate-limit-lines: 2;
  hyphenate-limit-last: always;
  hyphenate-limit-zone: 8%;
  }
```
3. Activate the theme.

**Expected behavior**
Hyphenation is turned on.

However it doesn't work.

A workaround is adding the `lang` tag to the new `html` element created by the extension

**Screenshots**
1. No hyphenation:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/68432385/167703914-ec7293eb-39e4-4955-9f67-396ed3eac3ed.png">
2. Adding the `lang` tag to the new `html` element
<img width="960" alt="image" src="https://user-images.githubusercontent.com/68432385/167704135-0928848a-d9b7-4874-babd-94c48b516786.png">
3. Hyphenation working:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/68432385/167704327-943a39e8-0c98-4b2c-9415-c17ff47e5f6f.png">

**Please complete the following information:**
 - OS: Windows 10
 - Browser Chrome 
 - Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by ZachSaucier** [comment]
Hey Max. Thanks for posting! 
This seems like a reasonable suggestion. I'll make sure to add it in the next version of Just Read. I hope to get around to working on Just Read this weekend.

**Comment by ZachSaucier** [comment]
`lang` is added to the iframe's `<html>` tag as of version 5.2.0.
