### ISSUE TITLE
Just Stopped Working

### ISSUE THREAD

**Issue by rory-wohl** [ZachSaucier/Just-Read#399]
**Describe the bug**
All of a sudden, the extension just stopped working.

**To Reproduce**
1. Click on Just Read icon in extension toolbar
2. Icon flashes "on" indicator
3. No/unexpected changes in formatting
4. Page locks up

**Expected behavior**
Expected formatting from default-styles.css to be applied to website

**Screenshots**
![JustRead](https://user-images.githubusercontent.com/106269531/170326581-276f60b7-97cd-4d97-a40c-3f08d93df945.gif)

**Please complete the following information:**
 - OS: macOS Monterey Version 12.4
 - Browser: Google Chrome
 - Version: Version 102.0.5005.61 (Official Build) (arm64)

**Additional context**
Uninstalled & reinstalled extension
Re-applied default-styles.css
No change; settings still not being applied

**Comment by ZachSaucier** [comment]
The new version should be released now. Please let me know if it fixes your issue!

**Comment by rory-wohl** [comment]
Perfect! Back to tip-top shape! Thank you!
