### ISSUE TITLE
The selection mode doesn't work

### ISSUE THREAD

**Issue by triplenman** [ZachSaucier/Just-Read#401]
**Describe the bug**
A month or two ago the selection mode stopped working (select text → click right button on mouse "view this selection in Just Read")

**To Reproduce**
1. select text
2. click right button on mouse
3. click "view this selection in Just Read"
4. either nothing happens, or the whole page opens from the beginning of page in reader mode

**Screenshot**
![Animation](https://user-images.githubusercontent.com/85114684/174464226-d0bf779b-82ef-4c47-813e-34c393fc2b56.gif)

**OS**: Windows 10 Home   |   **Version**: 21H1
**Browser**: Chrome   |   **Version**: 102.0.5005.115 (Official Build) (64-bit)
**Browser**: Opera   |   **Version**: 88.0.4412.20 (Official Build) (64-bit)

**Additional context**
Uninstalled & reinstalled the extension on different browsers.
Disabled other extensions.

**Comment by ZachSaucier** [comment]
Hey triplenman. Thanks for posting. Sorry about this issue. I became aware of it last week but hadn't found the time to fix it until now.

It should be fixed as of Just Read version 5.2.4. I'll push to the web stores now and your version should auto-update soon after that 🙂

**Comment by triplenman** [comment]
Hi! The extension has been updated to version 5.2.4.
But now after selecting the text and clicking on it with the right mouse button, there is no item "view this selection in Just Read".
![Animation](https://user-images.githubusercontent.com/85114684/174784010-2c3345d5-0ad9-445a-8562-e07bfd4fd43d.gif)

**Comment by triplenman** [comment]
> Hey triplenman. Thanks for posting. Sorry about this issue. I became aware of it last week but hadn't found the time to fix it until now.
> 
> It should be fixed as of Just Read version 5.2.4. I'll push to the web stores now and your version should auto-update soon after that 🙂

Hi! The extension has been updated to version 5.2.4.
But now after selecting the text and clicking on it with the right mouse button, there is no item "view this selection in Just Read".
![image](https://user-images.githubusercontent.com/85114684/175293219-bb9692e2-1bbf-40ea-ac27-7615e3a18367.png)

**Comment by ZachSaucier** [comment]
Hi. Unfortunately I had to remove this functionality. It seems that something changed with the browser so that I cannot access the highlight when starting Just Read 🙁 

I did fix user selection mode though. So that should be adequate for selecting what you need then you can use deletion mode to delete parts when required.
