### ISSUE TITLE
Just-Read doesn't work for https://www.cnn.com/2022/09/01/business/lukoil-chairman-dies

### ISSUE THREAD

**Issue by ThurstonBT** [ZachSaucier/Just-Read#403]
**Describe the bug**
Just-Read does not work for https://www.cnn.com/2022/09/01/business/lukoil-chairman-dies

**To Reproduce**
1. Go to '.https://www.cnn.com/2022/09/01/business/lukoil-chairman-dies ..'
2. Click on Just-Read icon '....'
3. No test from the CNN article is displayed.

**Screenshots**

**Please complete the following information:**
 - OS: Windows 7
 - Browser Google Chrome
 - Version 104.0.5112.102 (Official Build) (64-bit)
 
![image](https://user-images.githubusercontent.com/30613086/188007562-cf2ae5e9-a7ea-474a-a0ea-139ca7e3202f.png)

**Comment by ZachSaucier** [comment]
Hey Thurston. Thanks for posting and sorry for the trouble.

Just Read successfully autoselects the article content for me, both with and ad blocker on and off. Can you please try to provide additional information to help me recreate the issue? What browser and operating system are you using?

Also if you use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) are you able to select the content successfully?

**Comment by ThurstonBT** [comment]
1)  Per "What browser and operating system are you using?", please see my original report.

2) Just-Read fails with my add-blocker on or off.

3) Using 'user selection mode' Just-Read works correctly.

**Comment by ZachSaucier** [comment]
> please see my original report.

Oops, sorry about that 😅 

> Using 'user selection mode' Just-Read works correctly.

Glad to hear it!

It will likely be a while before I can find a Windows 7 computer to test this.
