### ISSUE TITLE
Nothing happens when linking https://www.pmi.org/disciplined-agile/the-importance-of-having-an-intake-process

### ISSUE THREAD

**Issue by sholtby** [ZachSaucier/Just-Read#404]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

**Additional context**

**Comment by ZachSaucier** [comment]
Hey sholtby. Thanks for making this report!

I've never seen an anchor link like the one that was causing this issue. I adjusted Just Read's code to work in cases like these. I'm pushing the new version (5.2.9) to the web extension stores now.
