### ISSUE TITLE
Can't exit from accidentally enabled Read mode in Google Spreadsheets

### ISSUE THREAD

**Issue by craftersmine** [ZachSaucier/Just-Read#406]
**Describe the bug**
When enabling Read mode in Google Spreadsheets and then disabling and refreshing page, Read mode automatically reenables itself even when extension icon shows that it is disabled (no "On" badge)

**To Reproduce**
1. Go to any Google Spreadsheet document
2. Enable read mode through "Just Read"
3. Disable read mode through "Just Read"
4. Refresh page

**Expected behavior**
When refreshing page after disabling read mode, it should not reenable it

**Please complete the following information:**
 - OS: Windows 11 21H2 (Release Channel)
 - Browser: Vivaldi
 - Version: 5.4.2753.51 (Stable channel) (64 bit)

**Additional context**
The only way right now to exit read mode in Google Spreadsheets is to disable extension only

**Comment by ZachSaucier** [comment]
Hey craftersmine. Just Read isn't intended to use on spreadsheets. 

Most likely what's causing this issue is the `jr=on` parameter that was added to the URL. If you remove that it shouldn't automatically run when you navigate to the page.

**Comment by ZachSaucier** [comment]
Yeah. Instead of adding more UI to address a symptom, I will try to do a better job of handling the core issue. I'll leave this issue open as a reminder until then.

Thanks for posting!

**Comment by ZachSaucier** [comment]
By the way, not sure if you've heard about [Just Read's autorun functionality](https://github.com/ZachSaucier/Just-Read#user-content-autorun). It might be useful if you haven't 🙂

**Comment by craftersmine** [comment]
> I'll leave this issue open as a reminder until then.

I guess it could look like "Force-disable read-mode on page" and like set &jr=force-off parameter, then check that parameter for example, so when you click on extension button, you will be prompted like "Read-mode has been force-disabled to prevent any website issues". Or even have internal exclusion list where read-mode shouldn't be enabled unless user has prompted with dialog to actually enable it?

> By the way, not sure if you've heard about [Just Read's auto-run functionality](https://github.com/ZachSaucier/Just-Read#user-content-autorun).

No I haven't heard about it, but sounds interesting, I need to try it

**Comment by craftersmine** [comment]
Yeah, this basically what my PR does, but requires a user to manually do this by clicking context menu entry
