### ISSUE TITLE
Share function dissapeared

### ISSUE THREAD

**Issue by Yaco** [ZachSaucier/Just-Read#411]
I am a premium user. In the latest version (5.2.13), I am unable to see the Share button and store the page in my dashboard.

I already tried re-installing the plugin. Could you help me?

**Comment by ZachSaucier** [comment]
Hey Yaco, thanks for posting. Sorry for the trouble that you're facing. 

What do you mean "disappeared"? What does the top right of your Just Read view look like?

Did you add a theme that someone else made perhaps? My guess is that CSS is hiding it.

**Comment by ZachSaucier** [comment]
Closing this due to lack of info.
