### ISSUE TITLE
deepl chrome extension not working on just read simplified pages, same for all extensions using a selected portion of text

### ISSUE THREAD

**Issue by emmpcoder** [ZachSaucier/Just-Read#412]
Once a page is run through *just read* then all extensions which use a selected portion of text cease to function.

Examples: 
deepl https://chrome.google.com/webstore/detail/deepl-translate-reading-w/cofdbpoegempjloogbagkncekinflcnj
dictionary lookup chrome-extension://ipdjaafajlfiopcppipdinmcjbcpofhd/options.htm

Deepl is used by 100 millions people and comes handy to read translated part of text.

Could you fix that please?

**Comment by ZachSaucier** [comment]
Hey emmpcoder. This is technically a limitation of other extensions that they could add support for. See #29 for more info. You could reach out to the deepl or dictionary lookup creators to see if they can add support for iframes if you want.

Just Read could technically be reworked to avoid this (see #282) but it's more work than it's worth for me at this point in time. Sorry about that.
