### ISSUE TITLE
PLEASE Help Me FIND a Very SIMPLE CSS Cheat-Sheet For Theme Edits !!

### ISSUE THREAD

**Issue by Chuck-7** [ZachSaucier/Just-Read#414]
Hello Zach! 
After a Lengthy Hiatus – I Have Returned!  (I’m the one who Quite LONG ago designed that Dark Purple Theme.)
Anyway, in the meantime, I Tested “that other reader-view,” but it was problematic – as it would save Only to html, so my saves were quite difficult to edit.

My Issue Today is (Hopefully) a Simple One::  I NEED to design a better theme, BUT being a non-techie:  Could you PLEASE Suggest a Cheat-Sheet that would tell __EVEN A SIMPLE SOUL LIKE ME__ how to make the Most Common CSS Edits —> LIKE:: 
• “Oh, your Linespacing is a bit too short?! Then, Simply Add THIS Line!:: ___”  _**OR:**_ 
• “Oh! You want a more readable Font **_AND_** a slightly Taller font-height? _**SIMPLE**_!!:: Just do The Following:: ____”.

Sooo, Could you Please Point me in the Right Direction So That, Even I, can make those type of Simple changes to my Theme?

Thank You Very Much for Your Kind Assistance!

Chuck Colsch _(aka: LSeek)_

       –– –– –– –– Post Script!::  I would like to ADD one more Brief Question to My Above–MAIN Issue::
You know that “Add a Comment” Bubble that commonly appears at the Right Margin  when I’m viewing a website in Just Read? ---
Well when I Need to Add SUCH a Comment – & SO: I Click that Bubble::  The Add-Comment-Box instantly Drops Down to the VERY Bottom of the Page, & when I go all the way to the bottom to attempt to add a few lines, when I'm typing, that comment-box starts annoyingly jumping up & down::  Is there ANY way I can make the Comment-Bubble NOT DROP to the Bottom? . . .  **_AND::_** After I’ve added a Comment – _Then_ Re-reading it, I Notice I Left Out a Key Word:: IS the Comment that I Had _JUST_ Added Editable??
THANK YOU!!  _– Chuck_

**Comment by ZachSaucier** [comment]
Hey Chuck, thanks for posting and welcome back.

Have you tried using the graphical theme editor? You open it by clicking the paintbrush icon in a Just Read view.

To address your specific questions:

> your Linespacing is a bit too short?! Then, Simply Add THIS Line!

What do you mean by "linespacing"? Do you mean the number of characters per line? If so, that's the `maxWidth` value in the graphical editor.

> You want a more readable Font AND a slightly Taller font-height?

You can import fonts using `@import`. [On a site like Google Fonts](https://fonts.google.com/specimen/Roboto) it provides the code you need to use it if you click the `@import` option in the right column.

> The Add-Comment-Box instantly Drops Down to the VERY Bottom of the Page, & when I go all the way to the bottom to attempt to add a few lines, when I'm typing, that comment-box starts annoyingly jumping up & down:: Is there ANY way I can make the Comment-Bubble NOT DROP to the Bottom?

Hmm, that's a peculiar effect. Any tips on how I can reproduce it? A screen capture would be superb.

**Comment by Chuck-7** [comment]
Zach::
Actually, Linespacing (Or: “Line-Spacing”) is one of the KEY elements that I need to Change —>
“Linespacing” refers to the Vertical GAP that Separates Lines within Single Spacing.  For Example:: The Microsoft Default is “1.08 Lines” for “Single Spacing”;  Because:: with 1.00 Lines, Lines are so Vertically TIGHT which makes it difficult to read. While Double-Space is 2.0 — which is TOO Vertically Spread Out.  SO: I would like to find the Setting for a Linespacing of ~ “**1.10**” Or “**1.15**” for my Default Theme.
______________
For the other issue, I do Not mind that it Bounces. BUT, perhaps the reason it Plummets ALL the way To Page-BOTTOM could be my adblocker.  Anyway:: Can I EDIT a comment that I had already saved?

**Comment by ZachSaucier** [comment]
> “Linespacing” refers to the Vertical GAP that Separates Lines within Single Spacing

Ah, that's [the `line-height` property](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) in CSS. So you could add something like this to your stylesheet in the Just Read options page:

```
.content-container {
    /* line-height: 1.8; */
}
```

> Can I EDIT a comment that I had already saved?

Sorry, not at this time. That's basically the same request as [this request](https://github.com/ZachSaucier/Just-Read/issues/408), which I will note.

**Comment by Chuck-7** [comment]
Zach::
**Thank You for the Line-Height Spec!!**

• **1.**  When I Click the Paint Brush to make a Theme-Edit, ALL I get is:: 

![Image 008](https://user-images.githubusercontent.com/50095404/217651315-7c382585-2285-4fa7-adf9-2e155355bdf2.jpg)

A Totally BLANK Form!!  That is why I did NOT Earlier Reference the Paint Brush::  It does NOTHING! :) 
Secondly::

• **2.**  How do I SAVE a Page Formatted by Just Read, Please?  And Thirdly::

• **3.**  Any idea on how I MIGHT Possibly Counteract the “Plummet-To-End-Of-Page” Comment-Box?

Thank You Again!!
– _Chuck_

**Comment by ZachSaucier** [comment]
> When I Click the Paint Brush to make a Theme-Edit, ALL I get is::

That happens on the occasional website. Try using it on a site like https://text.npr.org/ instead and it should work.

> How do I SAVE a Page Formatted by Just Read, Please? 

Click the printer icon then save as PDF, if that's what you mean.

> Any idea on how I MIGHT Possibly Counteract the “Plummet-To-End-Of-Page” Comment-Box?

Any tips on how I can reproduce it? A screen capture would be superb.

**Comment by Chuck-7** [comment]
THANK YOU ZACH!!

The Plummet occurs **INSTANTANEOUSLY** —>Capture **impossible** — Would you like to see the Box Sitting Disconsolately at the **_EXTREME_** Page Bottom?  It goes JUST as far down as Possible till it crashes at the VERY bottom!!

**Comment by ZachSaucier** [comment]
I'm guessing your browser window size isn't large enough for it to contain the comment next to the article content. Can you make the browser size larger on your screen?

**Comment by Chuck-7** [comment]
Correctamente!! – –>> My Max-Width Left Zero Space for a Comment!!

Thank You Zach!! – – And have a Great Day!!

– _Chuck_

**Comment by ZachSaucier** [comment]
Glad to hear it!

**Comment by ZachSaucier** [comment]
I stumbled upon this old issue. One note: You can now add inline-comments by CTRL + clicking the article. It will add a block in between the paragraphs near where you clicked.
