### ISSUE TITLE
Just Read's Store

### ISSUE THREAD

**Issue by trevinov** [ZachSaucier/Just-Read#415]
congrats for your app!

just a question

where to access Just Read's Store?

im trying to install the mobile extension to firefox or yandex as you explain in the FAQs but i couldnt find the store

**Comment by ZachSaucier** [comment]
Hey trevinov. You should be able to use [the Chrome store page](https://chrome.google.com/webstore/detail/just-read/dgmanlpmmkibanfdgjocnabmcaclkmod) since mobile browsers are currently webkit based.
