### ISSUE TITLE
Quick Question About Browsers

### ISSUE THREAD

**Issue by Chuck-7** [ZachSaucier/Just-Read#416]
Hi Zach!

I Just have a Super-Quick Question about my Frequent use of 2 Different Browsers!  —>

My MAIN Browser in which I use “**Just-Read-Premium**” is Brave —
BUT Occasionally I ALSO use Firefox.
Will my Just-Read Premium Version Automatically Work in **Firefox**, since I have that Subscription in Brave??

Thank You!!

_– Chuck_

**Comment by ZachSaucier** [comment]
Hey Chuck. Yes, your premium version should work in any browser that supports web extensions (which is all of the main ones). You just need to make sure Just Read is installed in a browser and then log into the Just Read website (https://justread.link/) to get the premium features working.

I'm going to close this issue but I will still see follow up posts FYI.
