### ISSUE TITLE
text-decoration doesn't seem to work

### ISSUE THREAD

**Issue by lef-est** [ZachSaucier/Just-Read#418]
**Describe the bug**
I tried to add `text-decoration-style: double` to headings in css but it does not work.

**Screenshots**
![image](https://user-images.githubusercontent.com/9643637/222901382-1cd13ca4-af1b-47f0-9822-f366814c28e6.png)

**Please complete the following information:**
 - Browser: Chrome 110.0.5481.178

**Comment by ZachSaucier** [comment]
Hello and thanks for posting. 

In order to use this property in CSS you must also specify `text-decoration-line: underline`. So the full code would be either:

```
text-decoration-style: double;
text-decoration-line: underline;
```

or the same thing via the shorthand property:

```
text-decoration: double underline;
```

**Comment by lef-est** [comment]
thanks a lot and sorry for submitting a non-bug!

**Comment by ZachSaucier** [comment]
No problem!
