### ISSUE TITLE
Option to remove floating icon to "add a comment"

### ISSUE THREAD

**Issue by mr-rusko** [ZachSaucier/Just-Read#419]
**Is your feature request related to a problem? Please describe.**
I find the floating icon to add a comment (a premium-only feature) distracting to me while I'm reading. I move the mouse around the screen while I'm reading as a method of focus, but having something interacting with it is just a little too busy for me. 

**Describe the solution you'd like**
I think having an option to turn the icon off would be best to solve this problem. A toggle would probably be best. 

**Describe alternatives you've considered**
Turn the feature off entirely and allow commenting to occur only on selected text. 

**Additional context**
Here's a screenshot of the icon I am referring to:
![big screenshot](https://user-images.githubusercontent.com/1444841/226144934-1845032e-3cab-46e1-8509-bf444595deeb.png)

**Comment by ZachSaucier** [comment]
Hey mr-rusko. This is already covered in [the Just Read FAQ](https://github.com/ZachSaucier/Just-Read#user-content-premium-features):

> To hide premium features, adding the following to your stylesheet on the Just Read options page: `.premium-feature { display: none !important; }`
