### ISSUE TITLE
Privacy Statement

### ISSUE THREAD

**Issue by peersil** [ZachSaucier/Just-Read#42]
Please consider a privacy statement (for example in the readme.md) to assure people that this extension will not log any browsing activities nor forward such data to servers in the internet.

**Comment by ZachSaucier** [comment]
I have now included a [privacy statement](https://github.com/ZachSaucier/Just-Read#privacy-statement) to explicitly state that Just Read collects no user information whatsoever. 

Let me know if you think the statement is adequate.

**Comment by peersil** [comment]
Thanks Zach! Like that!

**Comment by ZachSaucier** [comment]
Note that the privacy statement has been updated since the release of the premium version of Just Read to better reflect what Just Read does with user data.
