### ISSUE TITLE
RSS feed for shared pages

### ISSUE THREAD

**Issue by stavnskov** [ZachSaucier/Just-Read#420]
I am looking for a solution to save article content from Chrome on a Windows PC to a clean read version. Later I want to read this in my RSS reader (Inoreader) or Pocket on my tablet.

You would think Pocket supports this, but using the Chrome extension it only sees the link so my premium subscription sites does not include the full content.

My understanding of you extension is that it will save a simplified HTML including images in separate location in a random URL. If that URL could be added to an RSS XML file for my user that would be awesome.

**Comment by ZachSaucier** [comment]
Hey stavnskov and thanks for posting.

This is an interesting request. However, I don't think very many users would use this feature and it wouldn't be trivial to implement. To implement it, I believe I'd need to set up an RSS feed for every Premium user and add to that feed every time a user shares or deletes a page. It seems doable but would generate higher operating costs (not to mention my time to develop the feature). 

I believe that [Save to Pocket](https://getpocket.com/add) should work with shared Just Read pages. So you'd create the shared version of the page, visit it (you can have Just Read automatically open the shared page), then click the "send to pocket" button. Have you tried that?

**Comment by ZachSaucier** [comment]
Closing this due to a potential alternative and a lack of response.
