### ISSUE TITLE
Share Article button not working

### ISSUE THREAD

**Issue by ShawnAIS** [ZachSaucier/Just-Read#421]
When I go to any web page, I can click the JR button and it will render correctly. BUT, then when I click the "share article" button, nothing happens.

Chrome console says:
_Access to fetch at 'https://justread.link/newEntry' from origin 'https://apnews.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

JR version 5.2.14
Chrome version Version 113.0.5672.63

**Comment by ZachSaucier** [comment]
Hey Shawn, thanks for posting and sorry for the issue.

That's quite a curious error. I tried to recreate the error on [this page](https://apnews.com/article/texas-mall-shooting-mauricio-garcia-424607c69a5df0adab64f236924ae4e2) but was able to successfully share the page. Does the issue happen for you on this page also?

**Comment by ShawnAIS** [comment]
Yes it happens on that page. Chrome console says:

texas-mall-shooting-mauricio-garcia-424607c69a5df0adab64f236924ae4e2:1 Access to fetch at 'https://justread.link/newEntry' from origin 'https://apnews.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
content_script.js:2480     POST https://justread.link/newEntry net::ERR_FAILED 428
getSavableLink @ content_script.js:2480
content_script.js:2525 Fetch Error =
 TypeError: Failed to fetch
    at HTMLAnchorElement.getSavableLink (content_script.js:2480:13)
(anonymous) @ content_script.js:2525
Promise.catch (async)
getSavableLink @ content_script.js:2516
6The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by ZachSaucier** [comment]
Hmm. Maybe there's a conflicting extension or anti-virus program installed on your computer? Can you try disabling all other extensions and trying to share a page? Also try disabling anything like Noron/McCaffee if you have them and trying again.

**Comment by ShawnAIS** [comment]
I'm running Win10 with no AV (except for Defender).
I also tried disabling all other extensions but that didn't work.
I tried it on another computer (using my same Google login in Chrome) but that didn't work. 
I also tried the same on a different ISP because why not but no dice.
Thanks

**Comment by ZachSaucier** [comment]
Do you have an account with AP News? If so, if you log out and try again does the issue occur? I still can't reproduce the issue.

**Comment by ShawnAIS** [comment]
I created an AP News account and tried but the issue persists.

**Comment by ZachSaucier** [comment]
Shawn was a saint and did further testing on his own. It turns out this issue was coming from bumping up against the shared article limit that Just Read has (currently 100 shared pages). Chrome failed to show this issue but Firefox showed it. I'll investigate why the error didn't show in Chrome.

Thanks for debugging, Shawn!

**Comment by ShawnAIS** [comment]
My pleasure thanks for a great extension!
