### ISSUE TITLE
Removing highlight colour instead of text

### ISSUE THREAD

**Issue by mrmathkolan** [ZachSaucier/Just-Read#422]
Hello Zach,
I checked FAQ and the video but couldn't find how to remove an existing highlight colour. 
Sometimes, I use the highlighting feature to remember where I left last time. Either you may add 'where I left the reading previous time' feature or I request you to add a 'remove highlight colour' from an existing text. There is one but it removes all text instead of colour only. Thank you.
![Screenshot 2023-05-23 150111](https://github.com/ZachSaucier/Just-Read/assets/52935740/512b9ad5-487e-42ed-bacc-bd24704914e8)

**Comment by ZachSaucier** [comment]
Hey mrmathkolan and thanks for reaching out.

So long as the original Just Read view is still open (e.g. you are not looking at a *shared* Just Read view), you should be able to use the icon next to the trash can, the T with the slash through it, to remove annotations but not delete the text. Does that answer your question?

**Comment by mrmathkolan** [comment]
Yes, exactly. Thank you so much for the swift answer!
