### ISSUE TITLE
Reddit is Borked

### ISSUE THREAD

**Issue by crogonint** [ZachSaucier/Just-Read#423]
**Describe the bug**
It must have been relatively recently.. when I edit a Reddit discussion page to print it, then click the print button, I lose tons of content. The page displays correctly in the "Just Read" view, but in the Print Preview, the title is on one page, the initial post is on the second page (and cropped off), the third page is blank, the fourth page has the next post (and is cropped off), the fifth page is blank.. etc. etc.

**To Reproduce**
1. Go to a reddit.com discussion
2. Click on '.Just Read'
3. Click 'Print'

**Expected behavior**
...all of the content on the Print Preview, without blank pages in the middle.

**Please complete the following information:**
 - OS: Win7 64x
 - Browser Chrome
 - Version 109.0.5414.120

**Additional context**
Can we fix those ginormous Reddit icons while we're giving it some attention?

**Comment by ZachSaucier** [comment]
Hey crogonint and thanks for posting. Would you mind sharing a link to a post that shows this issue?

**Comment by ZachSaucier** [comment]
Closing this for now due to a lack of response/ability to reproduce.
