### ISSUE TITLE
Works great but does not support 'Auto Copy' extension

### ISSUE THREAD

**Issue by PacoH** [ZachSaucier/Just-Read#425]
I am used to the Chrome 'Auto Copy' extension that copies any selection I make automatically. When I switch to 'Just-Read' it no longer functions. It is very frustrating since I am so used to not having to type a keyboard shortcut to copy a selection, that I often forget. When I go to paste the selection, it is not copied and I have to go back and manually copy it. I can't find any setting in either extension that allows 'Auto Copy' to work. Is there one?

**Comment by ZachSaucier** [comment]
Hey Paco, thanks for posting.

This is covered in [this FAQ question](https://github.com/ZachSaucier/Just-Read#user-content-other_extensions):

As covered [in this post](https://github.com/ZachSaucier/Just-Read/issues/29#issue-196499408), this is an issue with the other extension and not Just Read. They will need to modify their code to work with iframe content.

However, most all extensions should work with a *shared* Just Read page, i.e. one on [justread.link](https://justread.link), but this is a [Premium-only feature](https://justread.link/#getJustRead).
