### ISSUE TITLE
Code blocks are condensed into one line

### ISSUE THREAD

**Issue by NobleFlower** [ZachSaucier/Just-Read#429]
**Describe the bug**

**To Reproduce**
1. An example website is https://blog.csdn.net/weixin_39977764/article/details/123310986
3. Click on 'Just Read'
4. See code blocks are condensed into one line
![image](https://github.com/ZachSaucier/Just-Read/assets/119724775/d4eadbaa-51cc-48f6-9263-cfd171a1974a)

**Expected behavior**
Display code blocks and comments inside normally

**Screenshots**
It should be like this picture:
![image](https://github.com/ZachSaucier/Just-Read/assets/119724775/88e9ea1e-b758-415c-8718-d8ecb1acd427)

**Please complete the following information:**
 - OS: Ubuntu 22.04
 - Browser: chrome
 - Version: 118.0.5993.70 (64 bit)

**Comment by ZachSaucier** [comment]
Hey NobleFlower, thanks for posting.

This is caused by this CSS in Just Read's `hide-segments.css`:

```
pre * {
    display: initial !important;
}
```

For the time being, you could uncheck `Use hide-segments.css` on Just Read's options page or add CSS to override this style, something like this:

```
pre li {
    display: list-item !important;
}
```

I will do a deeper investigation into what this CSS should be to appropriately handle more cases (for other pages this helps). Maybe it will end up being a modification to this:

```
pre *:not(li) {
    display: initial !important;
}
```

**Comment by NobleFlower** [comment]
@ZachSaucier , thank you for your prompt reply.
I solved my problem this way: check `Use hide-segments.css`, add the “list-item” code. But there is another problem:

When I only uncheck `Use hide-segments.css`, the website lost its Scroll Bar and some patterns are slightly misaligned like:
Former:
![image](https://github.com/ZachSaucier/Just-Read/assets/119724775/ce24345c-c3c3-49f9-9cb0-2f6583d71324)

Later:
![image](https://github.com/ZachSaucier/Just-Read/assets/119724775/82cbbf56-6edf-44eb-bc3e-4315eff9602d)

**Comment by ZachSaucier** [comment]
Hmm. Affecting Just Read's CSS shouldn't affect the CSS of the website...

**Comment by ZachSaucier** [comment]
I'm change the selector to `pre *:not(li) {` in the next version of Just Read so I'm going to mark this as complete.
