### ISSUE TITLE
Wrong readmode on punto-informatico.it

### ISSUE THREAD

**Issue by micdalco** [ZachSaucier/Just-Read#43]
Hi, thank you for your great extension.

While reading punto-informatico.it, if I enable "read mode" on Chrome, the result is a page without the relevant text content.

Example:
http://punto-informatico.it/4369752/PI/News/adblocker-resistere-inutile.aspx

Default view:
![schermata 2017-02-08 alle 09 24 21](https://cloud.githubusercontent.com/assets/1583334/22728877/7eb777e6-ede0-11e6-8433-261ed4e55041.png)

Read mode view:
![schermata 2017-02-08 alle 09 24 34](https://cloud.githubusercontent.com/assets/1583334/22728894/8d16bffe-ede0-11e6-9515-3cb9629249c0.png)

**Comment by ZachSaucier** [comment]
Thanks for the report! This is caused by the same issue as #27, so I included the site you linked in the list of problematic sites and am going to mark this issue as a duplicate.
