### ISSUE TITLE
allow to specify the openai API endpoint base url

### ISSUE THREAD

**Issue by shuther** [ZachSaucier/Just-Read#432]
**Is your feature request related to a problem? Please describe.**
I would like to use self hosted llm to summarize a page

**Describe the solution you'd like**
if I could specify the base_url for the API endpoint, I could leverage my ollama/openAI API self hosted endpoint.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ZachSaucier** [comment]
Thanks for requesting this! I think this is a fair request and can likely add it to the next round of updates. 

For clarity, you just mean allowing the URL used in [this line](https://github.com/ZachSaucier/Just-Read/blob/b142e4d8772cae8d41a38a174c4f6ef74c5bf278/content_script.js#L1360C12-L1360C54), `https://api.openai.com/v1/chat/completions`, to be overwritten with your own specified endpoint, right? No other parameters need to be changed?

**Comment by ZachSaucier** [comment]
I added the ability to change this URL by specifying `baseUrl` in the summarizer options. I assume this will solve the request so I am going to mark this issue as completed.
