### ISSUE TITLE
Let Summarizer handle additional response types

### ISSUE THREAD

**Issue by Aidan-Huang** [ZachSaucier/Just-Read#434]
When I use the  Summarizer feature, I get the error message    ( Unexpected token '<', " ), and I don't know why.

Here is my GPT APIconfig, I used self hosted llm, (use *** replay my real key) it can connect but not work.

{
    "baseUrl": "https://burn.hair",
    "key": "sk-***",
    "model": "gpt-3.5-turbo",
    "prompt": "Summarize the content you are provided as concisely as possible while retaining the key points.",
    "temperature": 0
}

![image](https://github.com/ZachSaucier/Just-Read/assets/1566679/2fade610-b796-4746-a2f6-82fba4bd916b)

**Comment by Aidan-Huang** [comment]
Oh, I guess you can use my KEY for debugging, so the key is:  sk-1bYkLyn9p1ESvosNEdA051FeEa38483a8920Cc9eE20177F1

**Comment by Aidan-Huang** [comment]
And I can you it in NextChat 
![image](https://github.com/ZachSaucier/Just-Read/assets/1566679/c1864efa-5dc9-47b6-b72c-f378919b0850)

**Comment by ZachSaucier** [comment]
Hey Aidan. This is because the API that you're calling is returning HTML when Just Read is expecting JSON. The summarizer functionality was made for just OpenAI or things that respond with the same format. 

I could update Just Read to allow for an arbitrary HTML response and have that be displayed directly within the Just Read view. Would that work for your use case?

By the way, you shouldn't share your key in public! I deleted the revision history for you. In the future, if you need to share a secure piece of information, something more private like email is better.

**Comment by Aidan-Huang** [comment]
First of all, thank you for your reply, I believe the solution you provided can solve this problem. Really appreicately your greatwork, it's very useful to me and I look forward to your updates.

Will the update provide an option for users to decide whether to return HTML or JSON? 

In addition, thank you for helping me hide the key. If there is a similar situation in the future, I will operate according to your suggestion.

**Comment by ZachSaucier** [comment]
> Will the update provide an option for users to decide whether to return HTML or JSON?

Yeah, it will have to be something like that. It will take me some time to think through how to best handle this sort of thing.

**Comment by ZachSaucier** [comment]
When I attempt to use your service using the way that you provided, this is the response that I get:

```html
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="logo.png"/><link rel="apple-touch-icon" href="/logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="头顶冒火，OpenAI API 接口转发站。"/><title>头顶冒火 🤯</title><script defer="defer" src="/static/js/main.5a762519.js"></script><link href="/static/css/main.54631fc9.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
```

This loads a blank page. Even when I change the response to add the `baseUrl` that you provide, it gives me this page, which is a 404 error:

![Screenshot 2024-04-13 at 5 52 23 PM](https://github.com/ZachSaucier/Just-Read/assets/3966722/c2795bf7-3189-491d-8dde-bb7132cd9644)

As such, while I'm open to adding support for a generic HTML response for this feature, your use case, at least as is, doesn't make work. Unfortunately I don't have the time to try and figure out how to make this endpoint work, especially given it is all in Chinese, haha

**Comment by ZachSaucier** [comment]
The latest version of Just Read should handle a generic HTML response and put it inside of an iframe within the Just Read view. So I'm going to mark this request as completed. 

Good luck figuring out how to get this service working correctly!
