### ISSUE TITLE
Theme switching doesn't work (6.0.4)

### ISSUE THREAD

**Issue by swifterslb** [ZachSaucier/Just-Read#436]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**
Theme switching button doesn't work after upgrading to version 6.0.4.

**To Reproduce**
Activate Just Read and click the "Edit your theme" button. The drop-down menu doesn't appear.

**Expected behavior**
A drop-down menu with theme options.

**Screenshots**

**Please complete the following information:**
 - OS: Windows 11
 - Browser: Chrome beta 64 bit (124.0.6367.60)

**Additional context**
The problem just appeared after the recent upgrade to 6.0.4.

**Comment by ZachSaucier** [comment]
Oops, good catch. Thanks for reporting this! I'll get it fixed soon, hopefully later today.

**Comment by ZachSaucier** [comment]
This should be fixed in 6.0.5. Thanks again for reporting!
