### ISSUE TITLE
summary output to display properly using markdown output from openai 

### ISSUE THREAD

**Issue by umsibaba** [ZachSaucier/Just-Read#441]
Hi, 
the summary output box is like a box with continuous words. would it be possible to leverage the openai summary output in mardown form to display the summary with proper formatting please?
![Screenshot 2024-10-17 at 12 11 21](https://github.com/user-attachments/assets/091e5e40-a092-45fd-943d-a4971ab38bfd)

**Comment by umsibaba** [comment]
i got it working by adding a prompt to output in HTML! thank you!

**Comment by ZachSaucier** [comment]
I'm glad to hear you got it working!
