### ISSUE TITLE
Does not display the full article

### ISSUE THREAD

**Issue by felipe-perestrelo** [ZachSaucier/Just-Read#443]
**Describe the bug**
The page below is not being rendered completely

1. Go to ['...'](https://www.simplypsychology.org/carl-jung.html)
2. Click on Just Read
3. Scroll down to the bottom
4. There's a considerable chunk of the original article missing

**Expected behavior**
To render the whole article

**Please complete the following information:**
 - OS: Windows 10
 - Browser : Chrome
 - Version 129.0.6668.101 (Official Build) (64-bit)

**Comment by ZachSaucier** [comment]
Hey Felipe, thanks for posting.

Just Read makes use of [Mozilla's Readability](https://github.com/mozilla/readability) for its automatic article detection. It looks like it has trouble with this article. 

If you're just reading this one article you can make use of Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read?tab=readme-ov-file#user-selection-mode) to manually select the content.

If you're regularly reading articles on this website and it is regularly failing to select all of the content, you can make use of Just Read premium's [domain-specific selectors](https://github.com/ZachSaucier/Just-Read?tab=readme-ov-file#user-content-selectors) to configure Just Read to select the correct content automatically.

You could also post on [Readability's GitHub issues](https://github.com/mozilla/readability) about the issue to try and get them to fix it. If they do, let me know and I can update the version that Just Read uses.

Let me know if you have any other questions or issues!
