### ISSUE TITLE
Text not appearing properly on some wordpress pages

### ISSUE THREAD

**Issue by c-reghiment** [ZachSaucier/Just-Read#47]
All text is ignored though most of it is in the main container. e.g. https://larspsyll.wordpress.com/

**Comment by ZachSaucier** [comment]
Good catch, there's an error in the stylesheet where a selector is too general: `[class *= "form"]`. Since that site uses a class `format-standard` it's being selected.

**Comment by ZachSaucier** [comment]
This should be fixed in version 1.0.19 / 34607ce
