### ISSUE TITLE
Last part of article cuts off when printing

### ISSUE THREAD

**Issue by kiizu** [ZachSaucier/Just-Read#49]
Example:
http://www.cnbc.com/2017/02/09/for-singapore-globalization-is-still-the-future-despite-dark-shift-to-protectionism.html

![image](https://cloud.githubusercontent.com/assets/25815059/23013868/8221e352-f467-11e6-8a82-1b6affe2628f.png)
^ the end of the print preview is not the end of the article

After deleting some elements, I managed to have the print preview show the whole article, but some of the lines at the page breaks were partially obscured.
![image](https://cloud.githubusercontent.com/assets/25815059/23013839/6053e8d8-f467-11e6-8ddd-92e7b7b6bbe7.png)

Thanks!

**Comment by ZachSaucier** [comment]
I'm not seeing either behavior you describe on my side. 

Are you using Just Read's print button? What operating system are you on?

**Comment by kiizu** [comment]
Windows 7 Enterprise (64 bit). I had been using Ctrl+P to print, but I just tried it again with the Just Read print button and had the same result.

**Comment by ZachSaucier** [comment]
When I was able to test this on a friend's computer, the page printed correctly for me but the preview in Chrome was incorrect as you describe. Could you try printing (or saving to a PDF) to see if it prints (saves) correctly?

If it does do it correctly, it's for sure a Chrome bug within WIndows 7, not an issue with Just Read.

**Comment by kiizu** [comment]
Thanks so much! That worked - the last bit isn't cutting off anymore. But I'm still getting broken lines at page breaks sometimes - here for example: http://www.straitstimes.com/opinion/the-story-of-a-passport-redesign-to-make-singapore-safer - see the end of page 2 and 3 in the PDF attached. This happened on Windows 10 Pro (64-bit).

[The story of how its passport redesign and screening makes Singapore safer.pdf](https://github.com/ZachSaucier/Just-Read/files/784789/The.story.of.how.its.passport.redesign.and.screening.makes.Singapore.safer.pdf)

**Comment by hugke729** [comment]
This bug also occurs with printing on Linux Mint 18. (I'm happy with your suggested work-around though.)

**Comment by version365** [comment]
The same happens to me..
Even after adding that _padding-bottom_ workaround, the texts are still not showing..
sometimes I have to add 1500px to get the whole text, sometimes even more..

Another issue is if the print is more than 15 pages, the next pages are always cut off..

Hope you solve it quick..

**Comment by ZachSaucier** [comment]
I will get to it as soon as I find some free time! It seems to be a proportional issue but only shows on some pages.

**Comment by ZachSaucier** [comment]
This should be fixed as of Just Read version 1.0.22. See #51 for more info.

**Comment by jessica-cobb** [comment]
I also see this happening on Windows 10, JRV free 1.2.8, Chrome Version 69.0.3497.100 (Official Build) (64-bit). I'm using the Just Read print button. I'm trying to use the extension to make offline copies of a web based ebook and some of the elements are not playing well with your extension, but not printing whole lines of text are a deal breaker. Please look into reopening this!

![original text](https://user-images.githubusercontent.com/10890334/46539347-3f6ac400-c884-11e8-97b3-d27376c0edee.PNG)
![cut off text](https://user-images.githubusercontent.com/10890334/46539362-4d204980-c884-11e8-99a0-296a03c804e8.PNG)
