### ISSUE TITLE
Address in the bar not changing.

### ISSUE THREAD

**Issue by aseeon** [ZachSaucier/Just-Read#5]
So there is a problem. When i click links inside the article, the url is not changing.

Here i am reading chapter 494 of a web novel:
![Chapter 494](http://i.imgur.com/Wwm48Ic.png)

When i click next chapter, the address in the bar stays the same:
![Chapter 495](http://i.imgur.com/Sz4UJIT.png)

And this is a problem because when i switch Just Read on again, it will again show Chapter 494, not the "correct" one.

**Comment by ZachSaucier** [comment]
I thought I had fixed this already... Good catch. It should be live within the hour in version 0.0.26

Fixed in c9d2fa1
