### ISSUE TITLE
Page not rendered catingham-palace

### ISSUE THREAD

**Issue by TheOne320** [ZachSaucier/Just-Read#50]
http://catingham-palace.com/archives/3359

does not give me a readable output.

**Comment by ZachSaucier** [comment]
Thanks for taking the time to create a report! 

Could you please post a screenshot of your output? It seems to work correctly for me on a Chromebook. Also what operating system are you using?

**Comment by TheOne320** [comment]
I just noticed that if I manually select the text it works so I would not consider it a bug but more of an improvement recommendation.

Windows 7, Chrome 56
![catingham](https://cloud.githubusercontent.com/assets/7705568/23271724/dcfc6fd6-f9f8-11e6-87e1-76d159baf11f.PNG)

**Comment by ZachSaucier** [comment]
I was able to reproduce this on this URL: http://catingham-palace.com/female-fencer/ch5/part3  The problems is the same as #47, so make sure you've either updated your custom stylesheets with [the most recent update for the problematic section](https://github.com/ZachSaucier/Just-Read/commit/34607ce649e35be1b61d234c852186611857c21a#diff-5903bc0c1841da176789d74440156b66L202) or that your default stylesheet is up to date (Just Read does this automatically, but you need to be on at least version 1.0.19).
