### ISSUE TITLE
Remember previous reader location

### ISSUE THREAD

**Issue by domingohui** [ZachSaucier/Just-Read#52]
Should we add a feature that remembers the last viewed location on the reader on the same page? So when the reader is closed and reopened, it will scroll to the previous location?

**Comment by ZachSaucier** [comment]
Hello and thanks for the request, but I'm not clear on exactly what you're suggesting.

Are you suggesting that Just Read should auto-run on URLs that it has already been ran on? Or that *if* Just Read runs on a page with the same URL as one it has ran on before, then scroll to the same position as before? Or that if Just Read is ran on a page then closed, reopen to the same spot it was just scrolled to?

**Comment by domingohui** [comment]
I was thinking about the last one 

> Or that if Just Read is ran on a page then closed, reopen to the same spot it was just scrolled to

But now that you mentioned the second option, that would be great too I guess :)

**Comment by ZachSaucier** [comment]
I don't know if there is a big enough use case to warrant implementation. How often do you close Just Read and open it again? Why would a user want to do that in the first place?

Implementation wise, the biggest problem I can think of right now storage of this information (it'd have to be the user's browser cache): Is it stored to a different location per URL (this could take up a good bit of memory in comparison to the functionality of Just Read)? Does it only track the most recently used Just Read page (this has problems when multiple pages are open with Just Read at the same time)?

**Comment by domingohui** [comment]
Sometimes certain elements (e.g. formatted code) are not rendered properly in Just Read, so I'd just close the reader and look at the actual page, and go back to the reader. 

In terms of implementation, I'm just thinking that the storage can be per visit. So if the user closes the webpage or gets redirected to another stie, the storage will be 'reset'.

**Comment by ZachSaucier** [comment]
You can try enabling "Don't reformat pre tags" under Options -> Additional options to keep code formatting.

**Comment by domingohui** [comment]
Syntax highlighting is gone sometimes tho... But if you don't see the necessity of this functionality, please feel free to close this :) 

Thanks again for building something neat like this!

**Comment by ZachSaucier** [comment]
This is similar to #241.
