### ISSUE TITLE
Script errors relating to context menu

### ISSUE THREAD

**Issue by WildTbag** [ZachSaucier/Just-Read#56]
The errors always show up, with or without the advanced option selected.
![2017-03-03_012035](https://cloud.githubusercontent.com/assets/26153143/23533209/847ba2f6-ffb0-11e6-9c21-4498de0b6e74.png)
![2017-03-03_012021](https://cloud.githubusercontent.com/assets/26153143/23533210/84815d40-ffb0-11e6-9a3c-560d60688456.png)

**Comment by ZachSaucier** [comment]
Hey and thanks for the report! That's an interesting error you're getting. I'll implement a check for that on the next iteration.

In the mean time, you can copy your current stylesheets, anything in your auto-run domain list, and take note of your advanced options and reinstall to fix the issue.

**Comment by WildTbag** [comment]
Hi, wow, thanks for the instant reply! Well, i reinstalled and the error did not show up.. until i unselected all context menu options in advanced settings (i prefer to just click the button). I should also mention i use Opera 44.

**Comment by ZachSaucier** [comment]
I didn't even know Opera _could_ run Just Read, haha.

The options don't seem to be doing what I meant for them to do anyway, not sure what's up. I'll give it some testing and post back here. Thanks again for the report!

**Comment by WildTbag** [comment]
I use the Opera extension 'Download Chrome Extension' to install any Chrome extension. It just bypasses the browser check on the Google playstore i guess.
https://addons.opera.com/de/extensions/details/download-chrome-extension-9/?display=en
![2017-03-03_015114](https://cloud.githubusercontent.com/assets/26153143/23533883/97271440-ffb4-11e6-95ce-9031d9790c40.png)

Regarding the script error i will leave the advanced options alone in the meantime. Thank you again.

**Comment by ZachSaucier** [comment]
I figured after searching about it. I'll have to give it a try sometime to see what features it can handle!

**Comment by ZachSaucier** [comment]
I accidentally had `==` when I should have had `!=` in two places which gave you the errors shown and prevented the option from working. Fixed now, changes will be live in version 1.0.10.

I still need to try out that Opera extension sometime though...
