### ISSUE TITLE
Non breaking spaces are just being deleted

### ISSUE THREAD

**Issue by aseeon** [ZachSaucier/Just-Read#6]
It's a very straightforward problem. When there are \&nbsp; (it is helpful with intricate text formatting) in the article, when Just Read is switched on, they are deleted, and words are clumped together.

Example:
`<p>The road was very very very&nbsp;long</p>`
Becomes:
`<p>The road was very very verylong</p>`

**Comment by ZachSaucier** [comment]
I am doing this purposefully, though I'm open to discussion on whether or not to keep this functionality. I've come across some sites that use `&nbsp;`  for pseudo-margins/padding and thus wished to remove those.

Though I suppose it would be better to convert them to regular spaces if there's not another space around it. Is that the functionality you want, or are you asking for them to remain completely?

**Comment by aseeon** [comment]
When there is one non breaking space i would just leave it "alone" and not convert it at all. When there are many non breaking spaces right next to each other i would do it like you do it now, and remove them. What do you think about that?

**Comment by ZachSaucier** [comment]
Maybe so. Do you have a (or several) website that you noticed this on? I'll look for the one(s) that I created the behavior based on

**Comment by aseeon** [comment]
http://www.mp.pl/pacjent/pierwsza_pomoc/145496,udar-cieplny (but it's in Polish, sorry).
When you see the source of the article you will see how it is formatted. It tries to conform to the rules of written polish. For example "o tym" should never be broken in the middle to crate new line and that's why they have \&nbsp; in that place.

**Comment by ZachSaucier** [comment]
Polish uses it a lot, huh? :D 

I'll update it to act as you suggest, though it'll likely be a day or two until it comes out because of the weekend.

Thanks for the report!

**Comment by aseeon** [comment]
Maybe not a lot. But it does happen, especially when someone tries to format text according to print rules.

**Comment by ZachSaucier** [comment]
This should be fixed in 3b4c619. All no breaking spaces are allowed until use cases for removing some start showing up

**Comment by ZachSaucier** [comment]
I came across a page that was using it as spacing. It had something like

```
<p>&nbsp;</p>
```

So, as of a56b275 / 0.0.31 I remove all elements that only have `&nbsp;`s in them. Let me know if I broke something, haha
