### ISSUE TITLE
Error with World Economic Forum Website

### ISSUE THREAD

**Issue by JackHigh** [ZachSaucier/Just-Read#61]
when i press the just read button i see nothing but the title

https://www.weforum.org/agenda/2017/03/how-to-turn-a-co-worker-who-sees-you-as-a-threat-into-an-ally/

**Comment by ZachSaucier** [comment]
Hello and thanks for the report! This is the same issue as #32, which I've yet to come up with a good solution for. Hopefully I'll have some time to sit down and figure out a solution in the next month or two.

The current work around is the same - use user selection mode. I added the site you linked onto the running list that cause the problem in the linked issue. As such, I'll go ahead and close this issue as a duplicate.
