### ISSUE TITLE
Large section of text is missing

### ISSUE THREAD

**Issue by victor9000** [ZachSaucier/Just-Read#65]
A large section of text is being omitted when you enable the reader on the page below:

https://library.oreilly.com/book/0636920052289/hands-on-machine-learning-with-scikit-learn-and-tensorflow/11.xhtml

In particular, the section titled "Types of Machine Learning Systems" is missing.

Chromium 57.0.2987.98, Ubuntu 16.04 LTS

**Comment by ZachSaucier** [comment]
Sorry, I don't see any real article on that page. Are you sure that the link is correct? Am I missing something?

**Comment by victor9000** [comment]
You can find a screenshot of the original content below, is this what you see on your end?

https://cloud.githubusercontent.com/assets/1413651/24834192/4d3e6af8-1c93-11e7-9c54-30e7f1b7ab3f.png

**Comment by ZachSaucier** [comment]
I didn't last time I loaded the page, but now I do... Last time it only showed the cover page. Weird.

This is a duplicate of #32, which I've yet to find a good solution to :/

**Comment by victor9000** [comment]
Ok, I'm closing this since it's a dup.  I'll go read through that issue, instead.  Thanks for the quick response!
