### ISSUE TITLE
Main article not being shown - "next article" selected instead

### ISSUE THREAD

**Issue by IDNIndia** [ZachSaucier/Just-Read#66]
Content unrelated to the actual URL is displayed when "Just Read" is used! 
The URL in question:
http://timesofindia.indiatimes.com/world/us/use-diplomacy-not-proxies-us-nsa-to-pakistan/articleshow/58220689.cms

**Comment by ZachSaucier** [comment]
Related to #32. 

This is due to the site showing more articles at the bottom of the page. Just Read is selecting the longest article on the page. You can use user-selection mode to solve this issue. As for potential fixes, keep watching #32.

**Comment by iandunn** [comment]
I think this is happening on cnet.com too. e.g., https://www.cnet.com/news/how-to-assign-applications-to-desktops-in-os-x/

**Comment by IDNIndia** [comment]
Hi,

Thanks for the information. However, I have stopped using the App!

Best Regards,
JB

**Comment by ZachSaucier** [comment]
This should be more or less fixed in the latest version (1.2.0) with Just Read's new auto-selection algorithm (although the site has a lot of ugly distractions in it).
