### ISSUE TITLE
Junk Data Displayed instead of Original

### ISSUE THREAD

**Issue by IDNIndia** [ZachSaucier/Just-Read#67]
https://sputniknews.com/asia/201704191052794212-india-launch-carrier-rocket/

**Comment by ZachSaucier** [comment]
Looks like the problem is caused by the site using more paragraphs in a signup form than it does in the actual article's content. Use user selection mode to select the article.

**Comment by ZachSaucier** [comment]
List of problematic sites that share this issue:

- https://www.epo.org/law-practice/legal-texts/html/guidelines/e/f_vi_1_5.htm

**Comment by IDNIndia** [comment]
Sorry to say that I do not use your extension anymore as I have found a
better alternative.

Best Regards,
JB

**Comment by ZachSaucier** [comment]
This should be more or less fixed in the latest version (1.2.0) with Just Read's new auto-selection algorithm.
