### ISSUE TITLE
Paragraph rendering issue

### ISSUE THREAD

**Issue by IDNIndia** [ZachSaucier/Just-Read#68]
The first paragraph is broken into several lines for this output:

http://economictimes.indiatimes.com/news/politics-and-nation/most-places-renamed-by-china-have-dalai-lama-tibet-links-expert/articleshow/58301680.cms

**Comment by ZachSaucier** [comment]
Good catch. This should be fixed in version 1.0.27

**Comment by IDNIndia** [comment]
Thank You! Happy to have such an interactive session, no other Extension has such an arrangement! Cheers!
