### ISSUE TITLE
Comments are new being as "author" section

### ISSUE THREAD

**Issue by aseeon** [ZachSaucier/Just-Read#7]
Before 0.0.28 the main article is the only thing that is properly displayed:
![Before 0.0.28](http://i.imgur.com/Wwm48Ic.png)

After 0.0.28 - sometimes only one, sometimes more comments are displayed at the top:
![After 0.0.28](http://i.imgur.com/Rw2Glkj.png)

**Comment by ZachSaucier** [comment]
I haven't come across this behavior. In fact, I've seen less comments and things because of some changes on the default stylesheet. 

Could you please provide a link to the pages that are causing this error?

**Comment by aseeon** [comment]
It's on the first screen:
http://www.wuxiaworld.com/atg-index/atg-chapter-494/

**Comment by aseeon** [comment]
it took those comments as the "author" section - odd.

**Comment by ZachSaucier** [comment]
This should be fixed in 3b4c619
