### ISSUE TITLE
Shortcut key not working

### ISSUE THREAD

**Issue by sheonhan** [ZachSaucier/Just-Read#72]
I'm trying to enable to reader mode with CTRL+SHIFT+L but it's not working.
Do you have any plan to add it as an option? Also, is the shortcut for Mac or Windows?

**Comment by ZachSaucier** [comment]
Sorry to hear that. You might need to [set the shortcut yourself](https://github.com/ZachSaucier/Just-Read#how-to-use) (look at the Note).

The shortcut should work on both platforms (though I haven't used a Mac to test the shortcut, so it could possible be Command+Shift+L

Try that out and get back to me.
