### ISSUE TITLE
Pages rendering as one massive paragraph

### ISSUE THREAD

**Issue by mxyzplx** [ZachSaucier/Just-Read#73]
On at least two websites now, vox.com and lawfareblog.com, pages are being rendered as one massive paragraph instead of displaying paragraph breaks. This happens with the default.css and with any adjustments I've made. I don't think it's the pages themselves, because they render fine with Firefox's Reader View.

The one thing that's different is if there are blockquotes in the article, then some (or all) of the rest of the paragraphs render separately, as normal. 

For instance, on [this Lawfare article](https://www.lawfareblog.com/what-james-comey-told-me-about-donald-trump), the article begins with a few blockquotes, and renders paragraphs normally until about a quarter of the way down the article, then the rest is one massive paragraph.

However, on [this Lawfare article](https://www.lawfareblog.com/what-can-congress-do-if-flynn-or-anyone-else-refuses-comply-subpoena), there are blockquotes scattered throughout the page, and all the paragraphs render as they should. 

The same happens on [this Vox article](https://www.vox.com/policy-and-politics/2017/5/18/15657688/trump-special-counsel-russia-flynn-mccarthy); the entire piece renders as one massive paragraph until you reach the only blockquote, and that renders the only actual paragraph break.

EDIT: The same also happens on [this Wired article](https://www.wired.com/2015/11/i-turned-off-javascript-for-a-whole-week-and-it-was-glorious), the only paragraph breaks that are rendered occur at embedded image in the article.

**Comment by ZachSaucier** [comment]
Thanks for the report! This is my fault, due to a change in the last commit.

 This should be fixed as of version 1.0.28.

**Comment by mxyzplx** [comment]
Thanks -- that was very quick. All those pages look good now. 

Can I add one more? Seem to be having a similar issue with the latest version on CNN, [like with this article](http://edition.cnn.com/2017/05/26/politics/james-comey-fbi-investigation-fake-russian-intelligence/index.html).

**Comment by ZachSaucier** [comment]
The issue with CNN articles is actually different. It's because they use divs instead of ps most of the time. I'll keep it in mind, but I already have a CNN article on my list of problematic sites. 

Hopefully I'll get around to redoing Just Read's selection sometime this summer, which should fix issues like the one you mention in addition to several other issues.
