### ISSUE TITLE
Article doesn't load properly due to <article> not being around the main content

### ISSUE THREAD

**Issue by Zzl320** [ZachSaucier/Just-Read#78]
## Error
First of all, thank you for reading this comment, I am writing to inform you of the inconvenience or error with the extension Just Read, **which I honestly found in these 3 days of use was incredible**, where I notice that the error in the content section is By the defective reading of the same, this error is something that I sincerely know that must be normal, but, because the extension seems very interesting I decided to divulge this error in the page of: [http://www.telesurtv.net/news/FIFA-defiende-uso-de-tecnologia-en-Copa-Confederaciones-20170621-0012.html](http://www.telesurtv.net/news/FIFA-defiende-uso-de-tecnologia-en-Copa-Confederaciones-20170621-0012.html)

## Possible solution
Before this error I dedicate myself to analyze an alternative possibility of how to fix or to introduce the section of correct content, _and I think that a great benefit would be to give the possibility to publish in itself the content, something that the header and the title already possess_

**Comment by ZachSaucier** [comment]
Thanks for the report! I was familiar with this as an issue. I will hopefully have enough time later this summer to improve how Just Read does article selection to fix this along with other similar bugs. 

For now you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to view content in Just Read on pages like this.

**Comment by ZachSaucier** [comment]
This should be more or less fixed in the latest version (1.2.0) with Just Read's new auto-selection algorithm.
