### ISSUE TITLE
Doesn't work on this article.

### ISSUE THREAD

**Issue by shrinidhi111** [ZachSaucier/Just-Read#80]
http://main.poliquingroup.com/ArticlesMultimedia/Articles/Article/1143/Eight_Common_but_Dangerous_Mistakes_of_A_High-Fat_.aspx

I felt this page is pretty straightforward and a surprise that Just Read didn't work.

**Comment by ZachSaucier** [comment]
Thanks for the report! 

This is a mix of #32 and somewhat #82 (which is really more of a symptom than the real cause). As such, I've added it to the list of problematic sites on #32 and will close this issue as a dupe.
