### ISSUE TITLE
Article not auto-selected when <p> tags are not used

### ISSUE THREAD

**Issue by xiaoming1112** [ZachSaucier/Just-Read#82]
http://www.rxyj.org/item_20160619195003QugAA4

**Comment by ZachSaucier** [comment]
Thanks for the report! For now you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select content when Just Read's selection fails.

**Comment by ZachSaucier** [comment]
This should be more or less fixed in the latest version (1.2.0) with Just Read's new auto-selection algorithm.
