### ISSUE TITLE
Unable to read articles.

### ISSUE THREAD

**Issue by amitlokhande109** [ZachSaucier/Just-Read#84]
![screenshot_20170715_093603](https://user-images.githubusercontent.com/30190694/28236324-1a9ac722-6941-11e7-8f10-3643d6741a89.png)

The web address is http://www.insightsonindia.com/2017/07/15/insights-daily-current-affairs-14-july-2017/

**Comment by ZachSaucier** [comment]
Very interesting. The problem is not immediately obvious, unlike most sites.

Thanks for the report! I'll look into it more deeply, hopefully sometime soon.

**Comment by amitlokhande109** [comment]
This really means a lot to me.
Thank You.

**Comment by ZachSaucier** [comment]
This should be more or less fixed in the latest version (1.2.0) with Just Read's new auto-selection algorithm.
