### ISSUE TITLE
Secondary title chosen instead of main title

### ISSUE THREAD

**Issue by adishavit** [ZachSaucier/Just-Read#88]
Try [this](https://kirit.com/How%20C%2B%2B%20coroutines%20work/Yielding%20Generators).
For some reason the 2nd header is chosen as the title.

**Comment by ZachSaucier** [comment]
Thanks for the report! You can edit the incorrect title by hovering over it and then clicking the pencil icon.

I'll look into a fix for this at a later date.

**Comment by adishavit** [comment]
Cool. Keep up the good work!

**Comment by ZachSaucier** [comment]
This should be fixed as of JR version 1.1.4.
