### ISSUE TITLE
Abnormal size for certain images.

### ISSUE THREAD

**Issue by 8lall0** [ZachSaucier/Just-Read#90]
In some sites images are rendered almost at full-size.
Would be a great improvement if it can keep the original size that's inside the article (or a reasonable one).

[Example page](https://blog.samwhited.com/2017/08/musings-on-the-future-of-go-package-management/)

**Comment by ZachSaucier** [comment]
Why keep them at the original size? Currently they are set to a max width of Just Read's container. If they were allowed to be bigger then they could overflow into the side of the screen, which isn't usually desired.

You can override these settings for your version by customizing your stylesheet. The code below should do it:

```
img {
    max-width: none;
}
```

**Comment by ZachSaucier** [comment]
Closing this due to a lack of response and confusion on what it's reporting in the first place.
