### ISSUE TITLE
Sections of webpage not rendered

### ISSUE THREAD

**Issue by manuelgomes** [ZachSaucier/Just-Read#91]
In https://martinfowler.com/articles/201701-event-driven.html , the "Further Reading", "Footnotes", and "Updates" are not rendered.

**Comment by ZachSaucier** [comment]
Hey Manuel, and thanks for the report! The sections like "further reading" and "footnotes" are not *exactly* part of the article, and, in this case, a bit separated in the markup. As such, Just Read isn't really setup to handle situations like this currently and there'd need to be some serious changes to the selection algorithm to get content like that generically, so I don't think this is a situation that I'll attempt to fix right now.

However, you can still use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the content you want to read, including the footnotes. Hopefully that's satisfactory for your needs!

**Comment by manuelgomes** [comment]
Thanks for your lightning-fast response, Zach.

Looking at the markup, I can see it is indeed a separate div, at the same depth as the article itself... I can see why it would be a bit of a stretch to elicit its relevance and contiguity from the DOM structure. I suspect doing a buttload of NLP to make this determination would be... an awkward scope :) 

Thanks for this extension, it makes my old tired eyes sigh with relief on a regular basis!

**Comment by ZachSaucier** [comment]
I may end up adding a "select more generally" button which could help fix issues like this with one click once JR is open... I've thought about it in a previous issue. I think I'll play around with it sometime hopefully soon.

I'm glad it's helpful to you!
