### ISSUE TITLE
read mode not displaying my entire content ? 

### ISSUE THREAD

**Issue by kfostano** [ZachSaucier/Just-Read#93]
Trying to read a blog post and for some reason, the entire text is not displaying?

**Comment by ZachSaucier** [comment]
Can you please provide a link to the blog post? Otherwise I can't really help fix the issue.

Most likely it's that content is being selected but is then being hidden by Just Read attempting to hide superfluous content.

**Comment by kfostano** [comment]
I am sorry for the delay.
http://rebecca-anne-stempel.tumblr.com/post/73620643562/this-has-been-a-long-time-coming

Here is the blog


On Thu, Aug 17, 2017 at 9:09 AM, Zach Saucier <notifications@github.com>
wrote:

> Can you please provide a link to the blog post? Otherwise I can't really
> help fix the issue.
>
> Most likely it's that content is being selected but is then being hidden
> by Just Read attempting to hide superfluous content.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZachSaucier_Just-2DRead_issues_93-23issuecomment-2D323068545&d=DwMFaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=7HQfZikOdlRCkMYT387F6WAUKMoJbbgAcu52veKihwg&m=lxZDpCMiviCPpVoAw2x91JwB2psaIHDT3ES2MzIwyK0&s=t_p69kW6SCZ7oZ4ymLobxvgYoZq0OSpeZCv4Pryu3Pw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZPXzM-2DBcCKYaNf9zvZNxxyo7K9Pf3hzks5sZDt-2DgaJpZM4O5CBx&d=DwMFaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=7HQfZikOdlRCkMYT387F6WAUKMoJbbgAcu52veKihwg&m=lxZDpCMiviCPpVoAw2x91JwB2psaIHDT3ES2MzIwyK0&s=fxYAiCI1iVqBmxct9LV-cJKGAZFzneNb9ThUEVh7_Zc&e=>
> .
>



-- 

Katherina Fostano, MSLIS
Visual Resources Curator
Department of Art History and Music
[image: http://www.fordham.edu/info/20810/art_history]
<http://www.fordham.edu/info/20810/art_history>
kfostano@fordham.edu
Office: FMH 459
Tel: 718-817-4753
   <https://www.facebook.com/FordhamArtHistoryDepartment?fref=nf>
<https://www.pinterest.com/visualresou0618/>
<http://twitter.com/Art_Ramblings>

**Comment by ZachSaucier** [comment]
What text is missing? All of the article content seems to show to me.

**Comment by kfostano** [comment]
http://rebecca-anne-stempel.tumblr.com/post/75788074216/6-am

On Wed, Aug 23, 2017 at 12:25 PM, Zach Saucier <notifications@github.com>
wrote:

> What text is missing? All of the article content seems to show to me.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZachSaucier_Just-2DRead_issues_93-23issuecomment-2D324388965&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=7HQfZikOdlRCkMYT387F6WAUKMoJbbgAcu52veKihwg&m=rL-eGTuncxCfgoxsuT0nLNOp7x8--_5EtanyK9sOQjI&s=E7TCudyVHWAasNFZxgY04oOaz4GECIitwmph-IRAL50&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZPXzGiSem9cuHLkSTps4e9pbFVUq-5Fbgks5sbFJugaJpZM4O5CBx&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=7HQfZikOdlRCkMYT387F6WAUKMoJbbgAcu52veKihwg&m=rL-eGTuncxCfgoxsuT0nLNOp7x8--_5EtanyK9sOQjI&s=bBCGMDjjKIxKww2acfmsWpTQOyd2M4zqEvP1VDV4CO0&e=>
> .
>



-- 

Katherina Fostano, MSLIS
Visual Resources Curator
Department of Art History and Music
[image: http://www.fordham.edu/info/20810/art_history]
<http://www.fordham.edu/info/20810/art_history>
kfostano@fordham.edu
Office: FMH 459
Tel: 718-817-4753
   <https://www.facebook.com/FordhamArtHistoryDepartment?fref=nf>
<https://www.pinterest.com/visualresou0618/>
<http://twitter.com/Art_Ramblings>

**Comment by kfostano** [comment]
http://rebecca-anne-stempel.tumblr.com/post/75724658096/blarg

On Wed, Aug 23, 2017 at 1:33 PM, Katherina Fostano <kfostano@fordham.edu>
wrote:

> http://rebecca-anne-stempel.tumblr.com/post/75788074216/6-am
>
> On Wed, Aug 23, 2017 at 12:25 PM, Zach Saucier <notifications@github.com>
> wrote:
>
>> What text is missing? All of the article content seems to show to me.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZachSaucier_Just-2DRead_issues_93-23issuecomment-2D324388965&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=7HQfZikOdlRCkMYT387F6WAUKMoJbbgAcu52veKihwg&m=rL-eGTuncxCfgoxsuT0nLNOp7x8--_5EtanyK9sOQjI&s=E7TCudyVHWAasNFZxgY04oOaz4GECIitwmph-IRAL50&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZPXzGiSem9cuHLkSTps4e9pbFVUq-5Fbgks5sbFJugaJpZM4O5CBx&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=7HQfZikOdlRCkMYT387F6WAUKMoJbbgAcu52veKihwg&m=rL-eGTuncxCfgoxsuT0nLNOp7x8--_5EtanyK9sOQjI&s=bBCGMDjjKIxKww2acfmsWpTQOyd2M4zqEvP1VDV4CO0&e=>
>> .
>>
>
>
>
> --
>
> Katherina Fostano, MSLIS
> Visual Resources Curator
> Department of Art History and Music
> [image: http://www.fordham.edu/info/20810/art_history]
> <http://www.fordham.edu/info/20810/art_history>
> kfostano@fordham.edu
> Office: FMH 459
> Tel: 718-817-4753
>    <https://www.facebook.com/FordhamArtHistoryDepartment?fref=nf>
> <https://www.pinterest.com/visualresou0618/>
> <http://twitter.com/Art_Ramblings>
>
>
>
>



-- 

Katherina Fostano, MSLIS
Visual Resources Curator
Department of Art History and Music
[image: http://www.fordham.edu/info/20810/art_history]
<http://www.fordham.edu/info/20810/art_history>
kfostano@fordham.edu
Office: FMH 459
Tel: 718-817-4753
   <https://www.facebook.com/FordhamArtHistoryDepartment?fref=nf>
<https://www.pinterest.com/visualresou0618/>
<http://twitter.com/Art_Ramblings>

**Comment by ZachSaucier** [comment]
Ah, ya, I can fix that. I'll get around to it within this week.

Thanks for the report and getting back to me!

**Comment by ZachSaucier** [comment]
The commit for this change should be live in version 1.1.2 within the next 5 hours or so.

**Comment by kfostano** [comment]
Thank you very much, Zach!


On Mon, Aug 28, 2017 at 5:47 AM, Zach Saucier <notifications@github.com>
wrote:

> The commit for this change should be live in version 1.1.2 within the next
> 5 hours or so.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZachSaucier_Just-2DRead_issues_93-23issuecomment-2D325310496&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=7HQfZikOdlRCkMYT387F6WAUKMoJbbgAcu52veKihwg&m=n1MUTEnYvINlc3J44dpXRvJcj5zHhVP8_hAXcQE_xVo&s=6rObe3LAYsc6gZQVe7IAOfAux1UFwlWHxJe8VuFBhBo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZPXzMECP6epA52Qslw6lb5-2DMn-2DCoTu4ks5scoy7gaJpZM4O5CBx&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=7HQfZikOdlRCkMYT387F6WAUKMoJbbgAcu52veKihwg&m=n1MUTEnYvINlc3J44dpXRvJcj5zHhVP8_hAXcQE_xVo&s=JfJ240bI2w7BLYn8SWbVr_kuQdfaVWgcghX9gEY3ep0&e=>
> .
>



-- 

Katherina Fostano, MSLIS
Visual Resources Curator
Department of Art History and Music
[image: http://www.fordham.edu/info/20810/art_history]
<http://www.fordham.edu/info/20810/art_history>
kfostano@fordham.edu
Office: FMH 459
Tel: 718-817-4753
   <https://www.facebook.com/FordhamArtHistoryDepartment?fref=nf>
<https://www.pinterest.com/visualresou0618/>
<http://twitter.com/Art_Ramblings>
