### ISSUE TITLE
Comment section auto-selected instead of main article content.

### ISSUE THREAD

**Issue by chriscz** [ZachSaucier/Just-Read#94]
On the following page only the comment section is rendered. 

http://www.raptitude.com/2017/03/only-thing-get-good-at/

**Comment by ZachSaucier** [comment]
Thanks for the report! I'll look into it as soon as I get some free time. Until then, you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to read article's content where JR fails to select the correct content.

**Comment by chriscz** [comment]
Thanks for the quick response and the title change; you're doing good!

**Comment by ZachSaucier** [comment]
Another site with this same issue: 

- https://medium.com/personal-growth/5-mental-biases-that-cause-poor-decisions-6ebe559aaf8f

**Comment by ZachSaucier** [comment]
Merging this into #331 which is a larger issue that contains this issue.
