### ISSUE TITLE
Portion of article missing using auto selection

### ISSUE THREAD

**Issue by charliecalvert** [ZachSaucier/Just-Read#95]
When viewed in Juist Read, this article starts several paragraphs in, after an ad:

https://www.nytimes.com/2017/08/22/books/review/campus-confidential-jacques-berlinerblau.html

In short, the first few paragraphs are missing and the text begins here: "Berlinerblau is best when he expresses moral outrage over the condition of "

**Comment by ZachSaucier** [comment]
Thanks for the report! For now you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) when Just Read fails selecting the article content.

**Comment by dodgyb** [comment]
Similar issue - the extension is not displaying the first paragraph of this [page](http://www.cmegroup.com/education/featured-reports/evolving-economics-of-bitcoin-gold-currencies.html)

User selection mode loads the full page, minus the selected paragraph.  I have noticed this on a couple of other sites too. See example output:

![capture](https://user-images.githubusercontent.com/1958461/32277471-76d9f962-bf0a-11e7-8577-66a5f52ba63f.PNG)

**Comment by megadr01d** [comment]
Just to report another website that outputs unwanted sections (menus, buttons, etc.).
http://www.healthy-holistic-living.com

**Comment by ZachSaucier** [comment]
@megadr01d Thanks for the report! Can you please [create a separate issue](https://github.com/ZachSaucier/Just-Read/issues/new) for that problematic website since the nature of the issue is pretty different than the issue in this thread?

**Comment by megadr01d** [comment]
@ZachSaucier Sure thing, moved to https://github.com/ZachSaucier/Just-Read/issues/125. Thanks.

**Comment by ZachSaucier** [comment]
Merging this into #331 which is a larger issue that contains this issue.
