### ISSUE TITLE
Auto-run Community List

### ISSUE THREAD

**Issue by avere001** [ZachSaucier/Just-Read#96]
I have created a repository for a community ran auto-run list. 
Everyone, please submit your lists as an issue or a pull request [here](https://github.com/avere001/just-read-autorun-community-list).
Feel free to submit an issue for websites that you would like added even if you don't know how to only filter just articles (I can handle that part for you).
The list is currently small but I will periodically update it with my list of sites.

**Comment by ZachSaucier** [comment]
Although I like the idea, I'm going to close this due to lack of maintenance and interest.
