### ISSUE TITLE
Some problem web sites

### ISSUE THREAD

**Issue by jack94707** [ZachSaucier/Just-Read#97]
The following sites don't render correctly for my Chrome browser:

http://www.newyorker.com/books/page-turner/an-intimate-history-of-antifa
https://www.nytimes.com/2017/08/24/opinion/trump-talks-and-talks-and-talks-and.html
https://www.nytimes.com/2017/08/24/opinion/obama-trump-charlottesville-moral.html

Many of the nytimes.com articles break, but some are OK.

**Comment by ZachSaucier** [comment]
Thanks for the report! I'll look into the issue ASAP. For now you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) when Just Read fails selecting the article content.

**Comment by jack94707** [comment]
Here's one more from the nytimes.com. It has a graph that gets scrambled beyond recognition, and the 1st few paragraphs are missing. 

I noticed the competing extension, Clear Read, has no trouble seeing the first paragraphs, but it leaves the graph out completely. Maybe looking at it will help.

**Comment by ZachSaucier** [comment]
I'm going to merge this issue with #95 because it's the same core issue. Watch for updates over there.
