### ISSUE TITLE
Plugin Support?

### ISSUE THREAD

**Issue by zybzzc** [ZachSaucier/Just-Read#98]
Actually, I want to use the `afterGetContainer` hook, but it's still a considerable proposal.

**Comment by ZachSaucier** [comment]
Are you wanting Just Read to support more plugins or are you wanting to make a plugin for Just Read? If so, what sort of thing are you looking to do? Most likely it'd be better just to modify Just Read to do what you want your plugin to do.

**Comment by zybzzc** [comment]
I want to separate every word into a `SPAN` element and add some operations for english learner(it's me🐶). I also need to use some other webExtension api to interact with server/user, so I had forked this useful project, thank you.

**Comment by ZachSaucier** [comment]
Let me know if you need any help understanding what's what! I'll close this issue as it doesn't deal with changing the core functionality of Just Read.
